### ISSUE TITLE
[Bug] Entities with UI Component (billboards) lag game when close to camera position.

### ISSUE THREAD

**Issue by makotech222** [stride3d/stride#101]
Use Case:
I have a prefab that is simply an Entity with a UI Component. The UI Page is just a Grid with a text box in it. It is used to show damage text when a player is hit. My code spawns the prefab, animates it, and removes from scene after await Task.Delay(2000). Game is an isometric diablo-like action rpg game.

Where my camera normally sits, spawning about 15 instances of the entity causes absolutely no problem whatsoever. However, if I zoom my camera in so that the camera is very close to the Entities (Even if they are not in view!), The FPS drops to <50 (from 100)

This is just a bug report. I haven't tried to investigate where the hotspot is or anything. Let me know if you need more information.

**Comment by Eideren** [comment]
Covered by #455, closing this one
