### ISSUE TITLE
Hope to add ACES option for tone mapping

### ISSUE THREAD

**Issue by D3ZAX** [stride3d/stride#1016]
The Academy Color Encoding System is a very famous opration for tone mapping, and it has been supported by many popular game engine such as Unreal, Unity and Godot, hope it can't be used in stride too!

**Comment by tebjan** [comment]
@D3ZAX it is very easy to add your own tone map, just make a copy of one, rename it and adjust the formula. it should get picked up by the engine automatically. if it works, it would be great if you can make a pull request. stride is a community project.

**Comment by D3ZAX** [comment]
OK, I will try it, thank you!

**Comment by tebjan** [comment]
solved by #1037
