### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by sebas77** [stride3d/stride#1022]
**Release Type**: Official Release/GitHub (please choose appropriate option)

official

**Version**: Version number and/or git branch

4.0.1.1400

**Platform(s)**: Does the problem occur on Windows, Android...?

windows

**Describe the bug**
![image](https://user-images.githubusercontent.com/945379/108370980-2f55a400-71f5-11eb-8b51-57cb55b54767.png)

**stack**
Exception
``` Error code 1 while running install package process [C:\Users\nig\.nuget\packages\stride.gamestudio/4.0.1.1400\tools\packageinstall.exe]
Error: System.InvalidOperationException: Visual Studio 2019 install failed with error 5007 Please manually install the following workloads/components using "Visual Studio Installer": - .NET core cross-platform development - Development Tools plus .NET Core 2.1 at Stride.PackageInstall.Program.CheckVisualStudioAndBuildTools() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\tools\Stride.PackageInstall\Program.cs:line 164 at Stride.PackageInstall.Program.Main(String[] args) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\tools\Stride.PackageInstall\Program.cs:line 53
 at Stride.Core.Packages.NugetStore.RunPackageInstall(String packageInstall, String arguments, ProgressReport progress) at Stride.Core.Packages.NugetStore.OnPackageInstalled(Object sender, PackageOperationEventArgs args) at Stride.Core.Packages.NugetStore.InstallPackage(String packageId, PackageVersion version, ProgressReport progress) at Stride.LauncherApp.ViewModels.PackageVersionViewModel.<>cDisplayClass55_0.<<Download>b0>d.MoveNext() 
```

**Additional context**
I am not sure why stride is so dependent on visual studio, I have installed, but I use Rider.

**Comment by sebas77** [comment]
![image](https://user-images.githubusercontent.com/945379/108383158-6f228880-7201-11eb-935c-4ff0b445c758.png)

also this doesn't seem to exist in the visual studio installation

**Comment by tebjan** [comment]
> also this doesn't seem to exist in the visual studio installation

did you have a look into the individual components in visual studio installer?

![image](https://user-images.githubusercontent.com/1094716/108408875-e0743280-7225-11eb-8b95-921b693ef203.png)

(sorry for german lang)

**Comment by sebas77** [comment]
That is not true same is it? Where does it say cross platform compilation?

**Comment by tebjan** [comment]
it appears that you were trying to install an older version, this issue apparently got fixed before the release: https://github.com/stride3d/stride/pull/988

the correct name is: Development Tools plus .NET Core 2.1

which you can also see in the diff of the PR.

**Comment by manio143** [comment]
![VS_DevTools](https://user-images.githubusercontent.com/10709060/108419257-947bba80-7232-11eb-8444-bedc0b6e46ae.png)

**Comment by sebas77** [comment]
Sorry and older version  of what? Stride? If so that is not the case. It's the only non beta 4 version

**Comment by manio143** [comment]
@sebas77 As you can see on the image I posted above, the _.NET Core cross-platform development_ is the workload and _Development Tools plus .NET Core 2.1_ one of it's component you need to select.
You're installing the right version of Stride. Also no need to install full VS, just the Visual Studio Build Tools.

**Comment by sebas77** [comment]
not sure what didn't work yesterday but now it does thanks
