### ISSUE TITLE
Fullscreen with Vulkan appears to be Broken

### ISSUE THREAD

**Issue by herocrab** [stride3d/stride#1024]
@Eideren: [This issue has a bounty](https://github.com/stride3d/stride/issues/1024#issuecomment-1065571362)
---
**Release Type**: Official Release

**Version**: 4.0.1.1400

**Platform(s)**: Windows

**Describe the bug**
I am not able to go full screen using Vulkan. My project is setup using SDL context, but I tested with the default and found the same results. I am only making calls to Window:

            var window = Game.Window;
            _windowPosition = window.Position;
            window.IsBorderLess = true;
            window.Position = Int2.Zero;
            window.SetSize(resolution); // Breaks Vulkan

            // window.PreferredFullscreenSize = resolution;
            // window.IsFullscreen = true; // Breaks Vulkan

With both approaches the game window goes full screen size but the draw call ceases to run. There is no crash or exceptions thrown within my IDE.

**To Reproduce**
1. Create a new project.
2. Add <StrideGraphicsApi>Vulkan</StrideGraphicsApi> to .csproj.
3. Attempt any of the methods above.

**Expected behavior**
I expect Vulkan to be able to go full screen.

I will create a repo of this and upload when I sit down to code again.

**Comment by herocrab** [comment]
I was able to reproduce this with a default project, targeting Vulkan and then setting Game.Window.Fullscreen to true. Unfortunately I can't upload the repo as it's larger than 10MB.

**Comment by herocrab** [comment]
I found this issue on Focus engine (Stride Fork):

https://github.com/phr00t/FocusEngine/issues/70#issuecomment-782376470

A workaround is to set the screen resolution and fullscreen flag in a configuration file and use it on launch. Apparently resizing Stride when using Vulkan is very complex.

**Comment by Eideren** [comment]
### This issue has a [$200,-](https://opencollective.com/stride3d/projects/bug-bounty-vulkan-fullscreen) bounty, if you are interested please follow the steps described [here](https://github.com/stride3d/stride/wiki/Bounty)

**Comment by tamamutu** [comment]
@stride3d Willing to give this a look if this hasn't been fixed.

**Comment by tebjan** [comment]
sounds great and would be really appreciated. To work on an issue, create a branch and make a draft PR without code so everyone can see that you are working on it. Then start committing to that branch and convert to regular PR when you are ready for review. Thanks!

**Comment by Eideren** [comment]
Fixed in PR #1709

**Comment by Aggror** [comment]
Hi @tamamutu,

Would you be interested in more paid project work for Stride. We have Open collective projects available but if there are other ideas that you ware willing to contribute with, we are all ears. We can have a chat via Discord or another channel if you are up for it.
