### ISSUE TITLE
Syntax highlighting issues in .NET 5

### ISSUE THREAD

**Issue by manio143** [stride3d/stride#1033]
**Release Type**: Official Release

**Version**: 4.0.1.1401

**Platform(s)**: N/A

**Describe the bug**
The syntax highlighting and intellisense of RoslynPad is broken again (see #786, #894, #1012).

**Additional context**
The RoslynPad services are dependent on System.Reactive. Initially there was an issue with that dependency missing (included in .NET Framework by default and not .NET Core). Later the issue was regarding the netcoreapp3.1 version being resolved into a non-standard way and that was fixed by upgrading to version 5.0 (or at least I was sure I finally fixed it). But now it seems to broken yet again (possibly with changes introduced around the new VS 16.9).

**Comment by manio143** [comment]
I checked this recently and it seems to be all good.

**Comment by Hsyenoh05** [comment]
it still doesn't work
