### ISSUE TITLE
"Color Space" setting change to "Linear" will get wrong display

### ISSUE THREAD

**Issue by D3ZAX** [stride3d/stride#1035]
Get wrong display when changing "Color Space" in "Game settings" from "gamma" to "Linear"!
Will be correct after reopen scene.

Engine Version: 4.0.1.1401

Correct:
![image](https://user-images.githubusercontent.com/15343372/111630767-a77fab80-882d-11eb-9b4d-3fae424fb5c1.png)

Wrong:
![image](https://user-images.githubusercontent.com/15343372/111631036-e9a8ed00-882d-11eb-8b0a-83cb06bb14db.png)

**Comment by Artromskiy** [comment]
Started doing this issue
