### ISSUE TITLE
Installing Stride on Windows 10 gives Error Code 5007

### ISSUE THREAD

**Issue by lonnietc** [stride3d/stride#1036]
Hello,

I have a 64-bit Windows 10 system that has Visual Studio 2019 Community Edition. 

I have installed a number of different .NET frameworks:

PSChildName                      Version
-----------                      -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.8.04084
Full                             4.8.04084
Client                           4.0.0.0

Including the latest 5.0 version.

I have had Stride installed in the past with exactly the same setup and it runs perfectly fine, but when I uninstalled Stride and then re-installed it, I get an error screen and it seems that the install fails with the message:

"The installation of Visual Studio returned with code 5007"

![image](https://user-images.githubusercontent.com/15264930/112210173-c2b53700-8bf0-11eb-9cbb-7fd72400eec2.png)

Additionally, I get the ERROR MESSAGES:

Exception
``` Error code 1 while running install package process [C:\Users\lonni\.nuget\packages\stride.gamestudio/4.0.1.1401\tools\packageinstall.exe]
Error: System.InvalidOperationException: Visual Studio 2019 install failed with error 5007 Please manually install the following workloads/components using "Visual Studio Installer": - .NET core cross-platform development - Development Tools plus .NET Core 2.1 at Stride.PackageInstall.Program.CheckVisualStudioAndBuildTools() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\tools\Stride.PackageInstall\Program.cs:line 164 at Stride.PackageInstall.Program.Main(String[] args) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\tools\Stride.PackageInstall\Program.cs:line 53
 at Stride.Core.Packages.NugetStore.RunPackageInstall(String packageInstall, String arguments, ProgressReport progress) at Stride.Core.Packages.NugetStore.OnPackageInstalled(Object sender, PackageOperationEventArgs args) at Stride.Core.Packages.NugetStore.InstallPackage(String packageId, PackageVersion version, ProgressReport progress) at Stride.LauncherApp.ViewModels.PackageVersionViewModel.<>cDisplayClass55_0.<<Download>b0>d.MoveNext() ```

This suggest that I need to add in:

Please manually install the following workloads/components using 

"Visual Studio Installer": - .NET core cross-platform development - Development Tools plus .NET Core 2.1

Which I tried to do and still the same errors occur.

Any ideas as to what is happening and how to fix this as the installation of Stride should not have any bearing with if Visual Studio is installed or not.

Additionally, I will to use a built-in Editor of Stride instead of the Visual Studio C# as an editor. How can I do this?

Thanks in advance

**Comment by vchirikov** [comment]
It's better to provide a manual installation option, the launcher doesn't work for me too.

**Comment by Eideren** [comment]
This issue is likely out of date given the changes we've had in the installer and runtime and the lack of recent activity, I'll close this one off but feel free to open a new one if you happen to have it again.
