### ISSUE TITLE
What is the current status of Linux support?

### ISSUE THREAD

**Issue by UltraBurstXD** [stride3d/stride#1044]
Hi,

Can I know the current status of Linux support? Can Stride GE run little well on Linux?

**Comment by ykafia** [comment]
You can compile your games only on windows ( due to the wpf editor and the asset compiler being windows only), but you can target linux.

**Comment by UltraBurstXD** [comment]
But isn't Microsoft making many parts of Windows open source to integrate them in MAUI? Will things change perhaps with .NET6 release?

**Comment by ykafia** [comment]
The editor is written using WPF which is windows only technology even if it's an open source solution. There are discussions about the editor that you can check on the discord and might have been extended to some existing issue

**Comment by UltraBurstXD** [comment]
Geez... What a hassle. Is Microsoft financing this project? WPF for cross platform solution? Or wait till MS decides to extend support of it's legacy framework?

**Comment by herocrab** [comment]
@ykafia has answered the question and this is discussed here: https://github.com/stride3d/stride/issues/8

@UltraBurstXD can this issue be closed?

**Comment by Eideren** [comment]
Closing: duplicate, see @herocrab 's reply, thanks @herocrab
