### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by dmacka** [stride3d/stride#1046]
I am going to upgrade my client with this engine but I have to redo the structure to 4.72 Net Framework instead of using Net 5. The number one reason is that Net 5 does not support Windows forms and that is what my project is design with as it uses Windows forms and is done in Net Framework. I made all new project files to fit my project but then there was a problem on compile that has me scratching my head.

As of this time I am just scanning in files looking for links I missed and  overall structure. I am seeing errors in code regards to some class functions not being accessible. I went and checked the function and it is internal function. Well, that is not good that one is trying to access a internal function form another class. Okay, so how did Net 5 compile this? If it is being compiled without errors or without some override it definitely is a bug. I actually sent a bug report to Microsoft because you should not ever access internal data in a class from another class.

This is the question.

What happens if I change these to public access?

PropertyContainer.cs line 615

PropertyContainer.cs line 620

Utilities.Interop.cs line 33

I still have a number of files to scan but so far these three cause 65 errors across 10 projects all related to these functions..

**Comment by dmacka** [comment]
Never Mind. I see what you did It's all fixed

**Comment by herocrab** [comment]
@dmacka Can this issue be closed?

**Comment by Eideren** [comment]
Net5 supports windows forms anyway, see: https://docs.microsoft.com/en-us/dotnet/desktop/winforms/?view=netdesktop-5.0
Closing it, feel free to reopen/create a new one if you other questions.
