### ISSUE TITLE
Unable to build assembly reference Error

### ISSUE THREAD

**Issue by crd-dclsoftware** [stride3d/stride#1052]
**Release Type:**
GitHub - cloned on apr 17, 2021

**Version:**
Master

**Platform(s):**
WIndows 10

**Describe the bug:**
Receiving the "Unable to build assembly reference" error when trying to instantiate a New Game project when running the compiled application. The application hangs/pauses at this point.

This is identical to an earlier open and closed bug, but I couldn't find it to reopen it.

**Steps to reproduce the behavior:**

1. Using VS2019 community with all required workloads and dependencies installed
2. Clone the Stride repository
3. Start VS2019 and Load Stride project
4. Build and run the project

**Expected behavior**
The New Game project is instantiated and the Stride Game Editor launches.

**Screen Shots**

The screen shots show:
1. The Stride UI result
2. A snapshot of the loaded modules window from the VS Debugger showing conflicting versions of NuGet packages.

![image](https://user-images.githubusercontent.com/24495523/115120321-c32bbe00-9f61-11eb-9e03-a26e07d09245.png)

![image](https://user-images.githubusercontent.com/24495523/115120358-e2c2e680-9f61-11eb-8d82-caf02ece6820.png)

**Snippets from the VS Output Window:**

...
'Stride.GameStudio.exe' (CoreCLR: clrhost): Loaded 'D:\LocalProjects\StrideEditor\stride\sources\editor\Stride.GameStudio\bin\Debug\net5.0-windows\NuGet.Common.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
...
'Stride.GameStudio.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\sdk\5.0.202\NuGet.Common.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
...

**Additional context**

1. The error is generated external to the program code (during a call to  Microsoft.Build.Execution.BuildManager.Build())
2. This seems to be a common problem - a running application can't resolve conflicting package versions.

If this is not a bug in the application code or configuration, any advice/insight on how to resolve the issue will be appreciated.

**Comment by crd-dclsoftware** [comment]
Is the problem related to this checkin on March-2021 ?


ID: e0d5aaa3cb3e5e63911e217012527f25b8a2d66c	
Author: Virgile Bello <virgile@xenko.com>	
Date: 2021-03-11 2:48:06 AM +00:00
Message:	 [Build] Force .NET version so that NuGet doesn't get upgraded behind our back. Later, we should probably use a AssemblyLoadContext to load either NuGet or MSBuild so that they can have different versions.

**Comment by xen2** [comment]
What is your version of Visual Studio? 16.9 RTM or 16.10 preview?

**Comment by crd-dclsoftware** [comment]
Microsoft Visual Studio Community 2019
Version 16.9.4
VisualStudio.16.Release/16.9.4+31205.134

**Comment by crd-dclsoftware** [comment]
This issue is fixed.
I have been able to compile and run StrideEditor with no issues.

It seems the work done by Virgile Bello, f4653293, on May 6, 2021:
 MSBuild is now loaded with an AssemblyLoadContext ...

Thanks
