### ISSUE TITLE
How can I show my model collider?

### ISSUE THREAD

**Issue by iRumba** [stride3d/stride#1053]
Hi. I have a model. And I want create box collider around the model, but i don't see collider bounds. How can I select and see collider?
Solution with showing all colliders in a scene is useless for this case.

**Comment by Eideren** [comment]
From within the editor or in your game ? 
If from within the editor why wouldn't showing all colliders work in your case ? I'm not aware of any other solution besides that one, or using a cube model as a guide and scaling that one with the box collider.

**Comment by iRumba** [comment]
> From within the editor or in your game ?
In editor.

> If from within the editor why wouldn't showing all colliders work in your case ?
Because I'm designing the model. Because I want to see once collider and my model when I design the model.

**Comment by herocrab** [comment]
Have you tried opening the prefab in single view mode by double clicking it?

**Comment by iRumba** [comment]
> Have you tried opening the prefab in single view mode by double clicking it?

Of course.

**Comment by Eideren** [comment]
And what was the issue with herocrab's solution ?

**Comment by Aggror** [comment]
Is this still an issue, otherwise this can be closed.
