### ISSUE TITLE
Incorrect rendering of dynamically loaded transparent textures

### ISSUE THREAD

**Issue by HordeResurrection** [stride3d/stride#1059]
**Release Type**: Official Release

**Version**: 4.0.1.1401

**Platform(s)**: Windows

**Describe the bug**
Dynamically loaded textures with transparency are incorrect rendered.

**To Reproduce**
1. Load texture with transparency from stream: `Texture.Load(GraphicsDevice, stream)`
2. Draw this texture with using spritebatch: `spriteBatch.Draw(texture, new Vector2(20, 20));`
3. You can see incorrect rendering now

**Expected behavior**
I expect what transparency textures will be rendered correctly.

**Screenshots**
- Source image:
![2021-04-28_23-48-26_xnviewmp](https://user-images.githubusercontent.com/65279361/116588517-84d2bf00-a8d0-11eb-8550-015765a1ba98.png)
- Actual result (incorrect behavior):
![2021-04-28_23-47-05_devenv - Copy](https://user-images.githubusercontent.com/65279361/116588590-96b46200-a8d0-11eb-84e1-42c74d196c16.png)
- What I expected:
![2021-04-28_23-47-05_devenv](https://user-images.githubusercontent.com/65279361/116588621-9fa53380-a8d0-11eb-9203-7cef79c905d5.png)
- Source image is really transparent:
![2021-04-29_18-52-02_xnviewmp](https://user-images.githubusercontent.com/65279361/116589190-3e319480-a8d1-11eb-9aa7-6956841ff114.png)

**Render code**
```
public class MyGame : Game
{
    private Texture _texture;
    private SpriteBatch _spriteBatch;

    protected override Task LoadContent()
    {
        using (var stream = File.OpenRead("Content/image.png"))
            _texture = Texture.Load(GraphicsDevice, stream);

        _spriteBatch = new SpriteBatch(GraphicsDevice);

        return base.LoadContent();
    }

    protected override void Draw(GameTime gameTime)
    {
        base.Draw(gameTime);
        GraphicsContext.CommandList.Clear(GraphicsDevice.Presenter.BackBuffer, Color.Black);
        GraphicsContext.CommandList.Clear(GraphicsDevice.Presenter.DepthStencilBuffer, DepthStencilClearOptions.DepthBuffer | DepthStencilClearOptions.Stencil);
        _spriteBatch.Begin(GraphicsContext);
        _spriteBatch.Draw(_texture, new Vector2(20, 20));
        _spriteBatch.End();
    }
}
```

**Additional context**
Full project: [LoadAndDrawIssue.zip](https://github.com/stride3d/stride/files/6400317/LoadAndDrawIssue.zip)

**Comment by HordeResurrection** [comment]
I checked same code on the Stride 3.1.0.2. It works fine!!

**Comment by HordeResurrection** [comment]
Hello!

Is there any workaround here?
Whole my game based on dynamical texture loading.

I can't downgrade to the Stride 3.1.0.2 because I fully migrate to .Net 5..
Is there different way to draw dynamically loaded textures in Stride 4.0?

Please help me!

**Comment by xen2** [comment]
Can't you just fix the image to have 0,0,0,0 in this area (like all other transparent areas) rather than 255,255,255,0?

**Comment by vdvman1** [comment]
I am not seeing an option in `Texture.Load` for premultiplying

**Comment by tebjan** [comment]
Right, It's not an option of the low level function. but the stride asset pipeline has it. So you can use the texture converter tool or the asset compiler.

But you can also use any C# image lib to premultiply and then use the data as initial data for the texture.

**Comment by HordeResurrection** [comment]
There is a good article about premultiplied alpha and artifacts:
http://www.adriancourreges.com/blog/2017/05/09/beware-of-transparent-pixels/
