### ISSUE TITLE
Is rotation fail?

### ISSUE THREAD

**Issue by iRumba** [stride3d/stride#1060]
![image](https://user-images.githubusercontent.com/12796309/116783637-fb7ee080-aab9-11eb-8fce-a54a9cc0a0a9.png)
Look at this script. Expected, that this script will rotate entity around Y axis on 45 degrees. But it doesn't happen. 

when i start game with my entity with added script on scene, i see my entity rotated by 45 degrees and standed. In debug i see that quaternion changes, but i don't see it on scene. Why?

**Comment by tebjan** [comment]
this will rotate the entity by 45° every frame... also make sure that `Entity.Transform.UseTRS = true` and no other script is writing to the rotation property and that you run the game executable. Scripts don't run in Game Studio.

**Comment by iRumba** [comment]
Entity.Transform.UseTRS == true

no other script is writing to the rotation property

Also, quaternion properties change after multiply. But it doesn't affect to view

**Comment by ykafia** [comment]
Did you attach the rotation script to the correct entity? For instance if the model is on the parent entity and you rotated a child entity you'd end up not rotating the parent

**Comment by iRumba** [comment]
> Did you attach the rotation script to the correct entity? For instance if the model is on the parent entity and you rotated a child entity you'd end up not rotating the parent

script is attached to correct entity. Model is child of rotated entity. And **first iteration of rotation is happened**. When scene loaded, i see that entity rotated to 45 degrees (without script 0 degrees) and freeze.

**Comment by salahchafai** [comment]
Your code **does** work, it rotates the entity 45° every frame. Maybe it's happening too fast that you didn't notice it? if you want it to rotate 45° per second you'll need to multiply with the deltaTime, so your code would be:
![Capture4](https://user-images.githubusercontent.com/64394387/125479636-cfdcb255-e611-4398-bd0c-b3531fe6f074.PNG)
this should be closed (i tested it and it works)

**Comment by iRumba** [comment]
> Your code **does** work, it rotates the entity 45° every frame. Maybe it's happening too fast that you didn't notice it? if you want it to rotate 45° per second you'll need to multiply with the deltaTime, so your code would be:
> ![Capture4](https://user-images.githubusercontent.com/64394387/125479636-cfdcb255-e611-4398-bd0c-b3531fe6f074.PNG)
> this should be closed (i tested it and it works)

Yeah, I see changes of Entity.Transform.Rotation object every frame in debug, but don't see it by visual (in game window). I thank, that changes so fast, thats why I can't see it, but I tryed decrease angle to 1 degree, to 0.5 degree, 0.001 degree. It looked same as with 45 degrees. My entity rotated on choosen angle only. I just tryed rotation mathematic in action without time reference.
