### ISSUE TITLE
The setup says i dont have the net framework, but i do have it.

### ISSUE THREAD

**Issue by Robotsrule4545** [stride3d/stride#1062]
**Release Type**: Official Release/GitHub (please choose appropriate option)

**Version**: Version number and/or git branch

**Platform(s)**:
windows
**Describe the bug**
it says that i dont have net but i do
**To Reproduce**
1. open setup

**Expected behavior**
small window pops up
**Screenshots**
![Install missing prerequisites_ 5_12_2021 7_11_47 PM](https://user-images.githubusercontent.com/77372650/117966324-5b954280-b356-11eb-852f-7de05c284ad1.png)

**Additional context**
I downloaded net 4 times already...

**Comment by Eideren** [comment]
This is probably referring to the SDK, did you try to install it manually ?

**Comment by Eideren** [comment]
This issue is likely out of date given the changes to runtime we've had since then, I'll close this off but feel free to open a new one if you stumble on this issue again
