### ISSUE TITLE
Asset compiler crashes on project referencing mixed-mode assembly

### ISSUE THREAD

**Issue by azeno** [stride3d/stride#1066]
**Release Type**: Official Release

**Version**: 4.0.1.1400

**Platform(s)**: Windows

**Describe the bug**
Referencing a mixed-mode assembly containing Fixups causes the asset compiler to crash due to https://stackoverflow.com/questions/5005409/exception-with-resolving-assemblies-attempt-to-load-an-unverifiable-executable - it seems it's simply not possible to load such an assembly from a byte array.

**To Reproduce**
1. Create a new game and reference https://www.nuget.org/packages/Microsoft.Kinect.Face.x64/
2. On build you get a `FileLoadException` with the above linked exception

**Expected behavior**
Should not crash. The assembly should be skipped and a warning/error logged - like it was done by my [PR](https://github.com/stride3d/stride/pull/965) a while ago? That PR was closed and never merged because we found a better solution for that problem back then.

It seems there're cases where loading from a byte array is simply not possible. Logging the failed attempt instead of crashing sound reasonable to me. Especially when it's only about testing whether or not the assembly contains any asset compilers.

**Screenshots**
![image](https://user-images.githubusercontent.com/573618/118472110-c228b080-b708-11eb-9ad9-64df9617a608.png)

**Additional context**
For reference I'll also link the [forum thread](https://discourse.vvvv.org/t/export-problem-gamma-3-2-and-anything-skia/19448/32) where this issue came up.

**Comment by xen2** [comment]
I see, it seems there is no other choice than to allow those exception then.
Would it be possible to filter this specific case (by checking some Exception property) or is the exception impossible to differentiate?
