### ISSUE TITLE
`ViewportRestore` incorrectly saving current state

### ISSUE THREAD

**Issue by vdvman1** [stride3d/stride#1069]
**Release Type**: Official Release

**Version**: 4.1.0.1459-beta (also affects 4.0.1.1401)

**Platform(s)**: Tested on windows, almost certainly affects all platforms

**Describe the bug**
When calling `RenderContext.SaveViewportAndRestore()` to save the viewport the `ViewportRestore` class only stores a reference to the current `ViewportState` class. As a result any changes to the current viewport state will affect the "saved copy", and when it is restored nothing is changed. Overall this means the viewport state changes will bleed outside the `using` block.

This can be seen affecting the `RenderTextureSceneRenderer`, any renderers invoked after this renderer finishes will see the viewport state set by the `RenderTextureSceneRenderer` rather than the original, leading to incorrect aspect ratios

**To Reproduce**
1. Create a new project using the `Sample: Animation` sample
2. Run and observe the correct aspect ratio for the main model in the middle of the screen
3. Change the width or height of the `RenderTexture` asset
4. Run again and notice the main model in the middle of the screen stretches the same way as the render textures

Alternative reproduction steps:
1. Create a new game project
2. Follow the official [manual](https://doc.stride3d.net/latest/en/manual/graphics/graphics-compositor/render-textures.html) for render textures, except place the `Camera Renderer` for the render texture prior to the main camera renderer
3. Run and observe the incorrect aspect ratio of the sphere

**Expected behavior**
`ViewportRestore` should either make a deep copy of the `ViewportState` or replace the current state with a new instance so that the original viewport is not modified
The aspect ratio of a render texture should not affect independent renderers in the parent scene collection

**Screenshots**
With the default `RenderTextureSceneRenderer` which calls  `RenderContext.SaveViewportAndRestore()` which creates an instance of the default `ViewportRestore` class:
![default-rendertexture](https://user-images.githubusercontent.com/2172023/120950071-4eb71380-c789-11eb-9f18-f5369747a85c.png)

With a custom `ViewportRestore` class which copies the `Viewport0` value rather than the `ViewportStatus` reference:
![fixed-rendertexture](https://user-images.githubusercontent.com/2172023/120950165-8de56480-c789-11eb-9072-8dec3bf65b8d.png)

These are in the exact same scene with the same graphics compositor other than the change to the custom render texture scene renderer script

**Log and callstacks**
N/A

**Additional context**
This is the custom `ViewportRestore` class that I used to fix the issue. I am currently unable to build Stride from source to submit a pull request. The optional `copy` parameter is used to potentially optimize cases where the original contents of `context.ViewportState` are not needed by the caller, and so a deep copy can be avoided.
May want to create a `Clone` or a `Copy` method in the `ViewportState` class to avoid resynchronization regarding the number of viewports supported

```csharp
    public struct ViewportRestore : IDisposable
    {
        private readonly RenderContext context;

        private readonly ViewportState previousValue;

        public ViewportRestore(RenderContext context, bool copy = true)
        {
            this.context = context;
            if(copy)
            {
                previousValue = new ViewportState
                {
                    Viewport0 = context.ViewportState.Viewport0
                };
            }
            else
            {
                previousValue = context.ViewportState;
                context.ViewportState = new ViewportState();
            }
        }

        public void Dispose()
        {
            context.ViewportState = previousValue;
        }
    }
```

**Comment by Artromskiy** [comment]
Started doing this issue
