### ISSUE TITLE
VS 2019 Compile error

### ISSUE THREAD

**Issue by Alad53** [stride3d/stride#1081]
![213](https://user-images.githubusercontent.com/86076716/122684026-d0885180-d20b-11eb-92ba-f6c2b42ff1a3.JPG)

**Comment by dmacka** [comment]
I have the same issue since the last update. Was compiling before that.

**Comment by xen2** [comment]
I did a fix for GameStudio in d7c5ed5 (but maybe it might be related to those subprojects?)
Did you compile `master` or `master-4.0`?

**Comment by dmacka** [comment]
> I did a fix for GameStudio in [d7c5ed5](https://github.com/stride3d/stride/commit/d7c5ed5a9228c0eeecbbb58222ca750e464a0987) (but maybe it might be related to those subprojects?)
> Did you compile `master` or `master-4.0`?

I built off my fork which is the same as master. I just narrowed it to Stride.GameStudio project that gives the errors. Like I said I had this completely compiling before Microsoft did an update back in April. I been doing some work on conversion to 4.7 framework for my project so I had not made any report.
