### ISSUE TITLE
Xenko won't start

### ISSUE THREAD

**Issue by AdityaSrivastava2819** [stride3d/stride#109]
Hi,
I am new to Xenko and have been trying to start it. I tried opening the templates but whenever I try to do so, it show this,
![2018-08-14_20-45-59](https://user-images.githubusercontent.com/37951362/44100915-c17f0b8a-a003-11e8-9ec8-d541774d5f1a.png)
Can anyone help me with this issue?

**Comment by xen2** [comment]
Seems to be a duplicate of #43.
Either follow the instructions of that issue, or try to install Xenko from website (this might install some missing dependencies).

**Comment by AdityaSrivastava2819** [comment]
Well, I had installed Xenko from the website itself. Will try the given
steps in #43 though.

**Comment by Eideren** [comment]
Duplicate of #43 as stated above, closing this one.
