### ISSUE TITLE
[Math] Quaternion API improvement

### ISSUE THREAD

**Issue by ykafia** [stride3d/stride#1097]
**Is your feature request related to a problem? Please describe.**
It's frustrating to have to go through matrix everytime i need a LookAt function

**Describe the solution you'd like**
Add a Quaternion static function that returns a look at rotation

**Describe alternatives you've considered**
Keep using the matrix function

**Comment by Eideren** [comment]
Changed this issue to include one more requests from discord: ``Quaternion * Vector -> Vector`` shorthand for ``Quaternion.Rotate()``

**Comment by AmbulantRex** [comment]
I've looked at this one in the past. I'm also interested in a "RotateAround" type function which is a common use case for a LookAt type function.

**Comment by AmbulantRex** [comment]
> 
> 
> Changed this issue to include one more requests from discord: `Quaternion * Vector -> Vector` shorthand for `Quaternion.Rotate()`

I'm worried about the implications of this. Multiplying a quaternion by a vector isn't a rotation and would require conjugation like we do in the `Quaternion.Rotate()`. I think adding this as a `*` operator would be mathematically incorrect unless I misunderstood what you meant.

**Comment by ykafia** [comment]
I think we should have a "LookAt" function for TransformTRS since Transform Component already has it by extension

**Comment by Eideren** [comment]
@AmbulantRex 
> I think adding this as a `*` operator would be mathematically incorrect unless I misunderstood what you meant.

Quaternion operators have never been element-wise operation, ``quat * quat`` is not returning a new quat with the product of each element of the quats multiplied together. 
So given that, if ``quat * quat`` rotates a given rotation by another, it is expected that ``quat * vector`` would return the result of rotating the Vector by the Quaternion. 
This is common to most of the engines out there now and even before like it was in UE3.

**Comment by Eideren** [comment]
This request has been implemented and merged in, I'll close this off
