### ISSUE TITLE
web docs say .net framework 4.7.2 is required

### ISSUE THREAD

**Issue by jasonswearingen** [stride3d/stride#1110]
**Release Type**: docs website

**Version**: latest

**Platform(s)**: N/A

**Describe the bug**
the getting started --> install stride page is out of date.  it says .net 4.7.2 is required:  https://doc.stride3d.net/latest/en/manual/get-started/install-stride.html

**To Reproduce**
Steps to reproduce the behavior: visit https://doc.stride3d.net/latest/en/manual/get-started/install-stride.html

**Expected behavior**
mention that .net 5 is supported

**Additional context**
would be more attractive to new users to know that net5 is supported

**Comment by AmbulantRex** [comment]
This issue should be under the documentation project here: https://github.com/stride3d/stride-docs

**Comment by jasonswearingen** [comment]
will reopen issue on stride docs repo
