### ISSUE TITLE
VS2022 support

### ISSUE THREAD

**Issue by jasonswearingen** [stride3d/stride#1119]
Tracking issue.     Support VS2022 in addition to VS2019.   

There is a bug in VS2022 Preview 3.1 that prevents MSVC v142 projects from building:  https://developercommunity.visualstudio.com/t/C-projects-are-targeting-Visual-Studio/1506031

**This bug in VS2022 needs to be fixed**, then supporting VS2022 should be straight forward, with the exception of the VS Plugin project, which needs dev work to target VS2022 as it's 64bit.

Stride engine via VS2022 is supported today (2021.08) if you change the ```<PlatformToolset>v142</PlatformToolset>``` lines in ```*.vcxproj``` to ```<PlatformToolset>v143</PlatformToolset>```.   But this will break VS2019 as it does not currently support MSVC v143.

Also FYI, when the VS2022 bug gets fixed, You will still need to manually add the the MSVC v142 toolchain via the VS Installer.

**Comment by jasonswearingen** [comment]
Regarding the VS Plugin, the Error I get when building is is:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	VSSDK1000	Failed to load 'C:\Users\Jason\.nuget\packages\microsoft.vssdk.buildtools\15.0.26201\tools\VSSDK\bin\VSCT.exe' Assembly. Could not load file or assembly 'file:///C:\Users\Jason\.nuget\packages\microsoft.vssdk.buildtools\15.0.26201\tools\VSSDK\bin\VSCT.exe' or one of its dependencies. An attempt was made to load a program with an incorrect format.	Stride.VisualStudio.Package	C:\Users\Jason\.nuget\packages\microsoft.vssdk.buildtools\15.0.26201\tools\VSSDK\Microsoft.VsSDK.Common.targets	128	
```

The problem is VSCT.exe is a 32bit program, and it is trying to be invoked by the 64bit build chain.  If the build chain can be invoked in 32bit mode then it should work.  **This needs a contributor proficient in the Stride build system to fix.**

**Comment by xen2** [comment]
Supposedly fixed in preview 5+ and RC3+
https://developercommunity.visualstudio.com/t/C-projects-are-targeting-Visual-Studio/1506031#T-N1565178

**Comment by xen2** [comment]
Anyway it looks like VS2019 + .NET 6 is not supported anymore:
https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md
So we'll probably have to do the same (VS2022 required, which is probably OK because I think it's go-live since RC1)
