### ISSUE TITLE
[Net6] Update Stride to target DotNet6.0

### ISSUE THREAD

**Issue by jasonswearingen** [stride3d/stride#1125]
# Tracking issue.  
This will need to happen eventually.    This issue outlines:
- the current state of the Net6 update work
- the blocking issues preventing merging into master
- breaking changes
- Why this is needed

# Current State of Net6 Update
- **Functional**  working upgrade can be found at:  https://github.com/jasonswearingen/stride/tree/vs2022-net6
   - Engine (all Stride.sln) runtime projects ported to Net6 and build is successful
   - Basic "End to End Scenario" successful.  
     - Build Stride.Sln
     - run Stride.GameStudio
     - create new CSharpBeginner tutorial from Template
     - open the created CSharpBeginner projects in VS2022 and run them
- The way the upgrade was approached was solving each break on an as-it-happens basis.  There is most likely features outside of the above described Roundtrip that are currently broken.  known breaks are described below

# Blocking issues preventing merge to ```master```
I suggest pulling the ```vs2022-net6``` branch into the Stride repo, but keeping it out of ```master```
- Net6 only works on VS2022 right now, and VS2022 has a bug preventing backwards compat with VS2019.  see https://github.com/stride3d/stride/issues/1119
- The VSPlugin is broken.  Likely cause is that VS2022 is 64bit and the plugin targets 32bit.  A contrib familiar with the plugin needs to do this work.
- Net6 is in preview.  The NuGet references will need to be updated once it's RTW in November 2021.
- ~Error when running a project from within GameStudio.  (Nuget, Microsoft.Net.HostModel does not have a v6.0.0.0 available)~

# Breaking changes
- Net6 upgrade should be very similar to Net5, though some external references in game projects may break.
- There are some opportunities that Net6 presents, such as the new Vector Structs (optimized for each platforms hardware by default), which if used would be considered a breaking change.  But this PR does not include any of that.  just basic runtime support.

# Why this is needed
- Net6 is an LTS version that will be supported for 3 years from it's RTW date (Nov'21).  The current Net5 will leave support around April'22.
- Msft has locked language levels to runtime.  So, to support C# 10.0 features the runtime needs to be Net6
- Further reading: 
  - https://github.com/stride3d/stride/issues/1044
  - https://github.com/stride3d/stride/issues/912

**Comment by Eideren** [comment]
This issue has been taken care of
