### ISSUE TITLE
Get the actual character velocity

### ISSUE THREAD

**Issue by abgenullt** [stride3d/stride#1127]
# Question and/or Comment
Hi,
I'm currently working with the "CharacterComponent".
You can set the desired velocity with the "SetVelocity" function.
**But is there a way to get the actual velocity?**

E.g. if you run into a wall, the character will stop. So, I need the actual velocity to create the reaction and slow the animation down or anything like that..

thx,
abgenullt

**Comment by Eideren** [comment]
The PR has been merged in, looks like that's what you were looking for, I'll close this one off then.
