### ISSUE TITLE
[Net6] UpdateEngine codegen broken on Net6

### ISSUE THREAD

**Issue by jasonswearingen** [stride3d/stride#1136]
**Release Type**:  Unofficial Net6 build.   see https://github.com/stride3d/stride/pull/1126

**Platform(s)**: Windows, Net6, VS2022

**Describe the bug**
I am trying the TopDownRPG sample using Net6 and it is crashing when trying to invoke what appears to be some code replaced by AssemblyProcessor
```Stride.Engine\Updater\UpdateEngine.cs:line 510```
```
 nextObject = ((UpdatableProperty)operation.Member).GetObject(currentPtr);
System.InvalidProgramException
  HResult=0x8013153A
  Message=Common Language Runtime detected an invalid program.
  Source=Stride.Engine
  StackTrace:
   at Stride.Updater.UpdatableProperty.GetObject(IntPtr obj) in C:\repos\_stride\stride\sources\engine\Stride.Engine\Updater\UpdatableProperty.cs:line 43
   at Stride.Updater.UpdateEngine.Run(Object target, CompiledUpdate compiledUpdate, IntPtr updateData, UpdateObjectData[] updateObjects) in C:\repos\_stride\stride\sources\engine\Stride.Engine\Updater\UpdateEngine.cs:line 510
```

just glancing but it seems this is some custom IL injected into binaries to do lower-level / unsafe code.     I can't debug into or view the actual code that is crashing.

**To Reproduce**
1. run GameStudio using net6 build.  
2. construct project from TopDownRPG sample
3. try to run sample

**Expected behavior**
no unhandled exception

**Mitigation**
You can catch the thrown exception but animations won't play.

**Comment by jasonswearingen** [comment]
further diagnosis:

--------
can someone figure out what this IL code does?
https://github.com/stride3d/stride/blob/7e836297cb5930c01e6dfa0183e7f3cc64748fb6/sources/engine/Stride.Engine/Updater/UpdatableProperty.cs#L36-L41
it's IL that the AssemblyProcessor is supposed to inject into Stride.Engine `UpdatableProperty.GetObject()`

Here is the AssemblyProcessor code that actually emits it:
https://github.com/stride3d/stride/blob/7e836297cb5930c01e6dfa0183e7f3cc64748fb6/sources/core/Stride.Core.AssemblyProcessor/UpdateEngineProcessor.IL.cs#L176-L180

I can't look at the actual IL emitted, because it's injected at runtime. :frowning:

I want to try rewriting that in C#, because the injected IL is crashing in net6:  
```
System.InvalidProgramException
  HResult=0x8013153A
  Message=Common Language Runtime detected an invalid program.
  Source=Stride.Engine
  StackTrace:
   at Stride.Updater.UpdatableProperty.GetObject(IntPtr obj) in C:\repos\_stride\stride\sources\engine\Stride.Engine\Updater\UpdatableProperty.cs:line 43
   at Stride.Updater.UpdateEngine.Run(Object target, CompiledUpdate compiledUpdate, IntPtr updateData, UpdateObjectData[] updateObjects) in C:\repos\_stride\stride\sources\engine\Stride.Engine\Updater\UpdateEngine.cs:line 514
```

to me, it looks like it's pinning the input `currentPtr` parameter and returning it as an object.   But I don't know if my conversion is correct.   what I did is simply:
```
var handle = GCHandle.FromIntPtr(currentPtr);
nextObject = handle.Target;
```
which doesn't crash, but the `nextObject` is some invalid memory that can't be read.   Later on some code using it fails with `System.AccessViolationException  HResult=0x80004003  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`

So, I wonder if my code is a "correct" conversion of the IL.

**Comment by jasonswearingen** [comment]
That's the extent I'm going to be able to investigate this issue.  someone else needs to take over from here.

as it stands, animations will crash the engine due to this.    You can `catch` the thrown exception but animations won't play.

**Comment by jasonswearingen** [comment]
This issue has been repro'd using the current `Net5` version of Stride with a game project targeting `Net6`.

**Comment by xen2** [comment]
I think I could fix it.
Please cherry-pick https://github.com/xen2/stride/commit/5e82e0c8379808d6bf5ef1499dc390df7e01f670
(you might need to add my repo as a remote so that LFS can pick up binaries properly)

**Comment by jasonswearingen** [comment]
it fails when building the `TopDownRPG.Windows` project, but I think due to a merge from master that removed CompilerApp.exe
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Stride AssetCompiler could not be found (Command: "C:\Users\Jason\.nuget\packages\stride.core.assets.compilerapp\4.1.0.1-net6\buildTransitive\..\lib\net6.0-windows7.0\Stride.Core.Assets.CompilerApp.exe")	TopDownRPGNet6.Windows	C:\Users\Jason\.nuget\packages\stride.core.assets.compilerapp\4.1.0.1-net6\buildTransitive\Stride.Core.Assets.CompilerApp.targets	115	
```

How can this be fixed?  I am pretty sure I merged that properly.

**Comment by jasonswearingen** [comment]
I can't repro this with [de0a0cb] so it is an interaction with it and net6.

**Comment by jasonswearingen** [comment]
I will need to rollback changes from [de0a0cb] as the build-time errors are in an assembly executed at build time.  This is not debuggable and no error information is provided.

**Comment by jasonswearingen** [comment]
I figured out the bug(s).   Some paths in the build system were not updated to `net6-windows7.0` properly
