### ISSUE TITLE
[Graphics] AllowMultipleComponents on LightComponent

### ISSUE THREAD

**Issue by Eideren** [stride3d/stride#1138]
**Is your feature request related to a problem? Please describe.**
Easy to work around but no reason to prevent users to add multiple lights on the same entity.
Use case:
Ambient and directional light to have just one entity handling 'sun light', directional for direct and ambient for indirect.
Spot and point light for a lighthouse's beam.

**Comment by Artromskiy** [comment]
Started doing this issue
