### ISSUE TITLE
[Build] AssetCompilerApp package should not have non-IL executable in the lib folder

### ISSUE THREAD

**Issue by manio143** [stride3d/stride#1139]
**Release Type**: GitHub

**Version**: 4.1

**Platform(s)**: Windows

**Describe the bug**
The `Stride.Core.Assets.CompilerApp` is built as an executable which under .NET Core/5 means it has a .NET DLL and a Win32 EXE which serves as a runtime host. Having this native executable in the lib folder makes MSBuild try to load it as a reference for any project that includes a package reference to the CompilerApp. But since it's not a valid assembly we get an error `MSB0001: Internal MSBuild Error: Unexpected CopyLocal flag`. This has been mitigated for user projects by making them only include `build` and `buildTransitive` folders. However, if a project references a dependent of the CompilerApp, such as Stride.Assets.Presentation there is no way to prevent it from trying to load the executable (as it's among libraries that are required).

**To Reproduce**
1. Create an empty .NET project
2. Reference `Stride.Assets.Presentation` or `Stride.Core.Assets.CompilerApp`
3. Have VS flip out, or run msbuild to see the internal exception

**Expected behavior**
There should be a separate folder in the package for the executable, and only DLLs in the `lib` folder.

**Log and callstacks**
```
error MSB4018: The "ResolveAssemblyReference" task failed unexpectedly
error MSB4018: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Unexpected CopyLocal flag.
error MSB4018:    at Microsoft.Build.Tasks.CopyLocalStateUtility.IsCopyLocal(CopyLocalState state)
error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.LogResults(ReferenceTable dependencyTable, List`1 idealAssemblyRemappings, List`1 idealAssemblyRemappingsIdentities, List`1 generalResolutionExceptions) 
error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists fileExists, DirectoryExists directoryExists, GetDirectories getDirectories, GetAssemblyName getAssemblyName, GetAssemblyMetadata getAssemblyMetadata, GetRegistrySubKeyNames getRegistrySubKeyNames, GetRegistrySubKeyDefaultValue getRegistrySubKeyDefaultValue,GetLastWriteTime getLastWriteTime, GetAssemblyRuntimeVersion getRuntimeVersion, OpenBaseKey openBaseKey, GetAssemblyPathInGac getAssemblyPathInGac, IsWinMDFile isWinMDFile, ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader)
error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Additional context**
I got inspired to come to this conclusion by https://github.com/dotnet/sdk/issues/9981 and was able to make the error go away by going into the nuget package folder `~\.nuget\packages\stride.core.assets.compilerapp\4.1.0.1-beta\lib\net5.0-windows7.0` and changing the extension from `exe` to `exe_`.

**Comment by xen2** [comment]
Interesting bug, thanks for the investigation.

I just did a quick test, and it looks possible to move the launcher part (`Stride.NuGetLoader`) into the `tools` subfolder while keeping the rest in the `lib` folder. So I guess we should just do that.
