### ISSUE TITLE
[Suggestion] Launcher should install latest stable release by default instead of beta

### ISSUE THREAD

**Issue by MeharDT** [stride3d/stride#1144]
**Is your feature request related to a problem? Please describe.**
The Stride Launcher will prompt the user to install the latest version of the engine if no existing install is detected (i.e., first run).

**Describe the solution you'd like**
If the user accepts the prompt the Launcher will automatically install the latest beta release, it may be better for new user experience if the latest stable release is installed (i.e., 4.0 instead of 4.1-beta).

**Describe alternatives you've considered**
Ask the user if they'd like to install the latest stable release or beta.

**Comment by Aggror** [comment]
Good idea. Probably even better to have the distinguished option to choose between latest stable and latest beta.

**Comment by Eideren** [comment]
Closing this off, we don't release betas anymore.
