### ISSUE TITLE
DebugText.Print(string msg, Int2 pos, Color4 col) doesn't display given color

### ISSUE THREAD

**Issue by DrBellubins** [stride3d/stride#1155]
**Release Type**: Official Release

**Version**: 4.1.0.1459-beta

**Platform(s)**: Windows

**Describe the bug**
DebugText.Print() has an overload which takes a Color4, yet isn't reflected in-game.

**To Reproduce**
1. Use DebugText.Print(string message, Int2 position, Color4 color) overload.

**Expected behavior**
Given color be reflected in-game.

**Comment by MeharDT** [comment]
Line 103 in DebugTextSystems.cs is always false even when the colours are different.

`msg.TextColor` != currentColor`

Will have a PR ready shortly.

**Comment by TheKeyblader** [comment]
maybe close the issue ?
