### ISSUE TITLE
Xenko won't start

### ISSUE THREAD

**Issue by FrodoDragons** [stride3d/stride#117]
I've looked at the other issues (one linked #43 and the other was #43 ) that concerned this, but their solutions didn't work for me (or I couldn't understand what they meant so I did it wrong). Maybe someone here can help? 

(Note: I did replace my name after C:\Users\ with a "..." here because its an embarrassing name kid-me made and has no relevance to the issue here. I also added some space between specific lines so it isn't a mes to read.)

This is everything that comes up when I click "Start 3.0.0.3", and then choose "New Game":

Edit: Sorry for the same name as #109 , didn't know I chose the same words

`Verbose: Loading Assets from Package [Xenko.xkpkg]
Verbose: Loading Assets from Package [MyGame6.xkpkg]
Verbose: Generating MyGame6.Game...
Verbose: Generating MyGame6.Windows...
Verbose: Loading Assets from Package [MyGame6.xkpkg]
Verbose: Restore NuGet packages...`

`
[C:\Users\...\OneDrive\Documents\Xenko Projects\MyGame6\MyGame6.sln.metaproj(0,0)]: Error: The specified solution configuration "Debug|MCD" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration.`

`
[C:\Users\...\OneDrive\Documents\Xenko Projects\MyGame6\MyGame6.sln.metaproj(0,0)]: Verbose: Compiling game assemblies...`

`[C:\Program Files\dotnet\sdk\2.1.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(198,5)]: Error: Assets file 'C:\Users\...\OneDrive\Documents\Xenko Projects\MyGame6\MyGame6\MyGame6.Game\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.`

`
[C:\Users\...\OneDrive\Documents\Xenko Projects\MyGame6\MyGame6.sln.metaproj(0,0)]: Error: Unable to build assembly reference [C:\Users\...\OneDrive\Documents\Xenko Projects\MyGame6\MyGame6\MyGame6.Game\bin\Debug\net461\MyGame6.Game.dll]`

`
[C:\Users\...\OneDrive\Documents\Xenko Projects\MyGame6\MyGame6.sln.metaproj(0,0)]: Verbose: Game assemblies compiled...`

`
[C:\Users\...\OneDrive\Documents\Xenko Projects\MyGame6\MyGame6.sln.metaproj(0,0)]: Warning: Can't load Game assembly`

`
[C:\Users\...\OneDrive\Documents\Xenko Projects\MyGame6\MyGame6.sln.metaproj(0,0)]: Verbose: Restore NuGet packages...
`

`
[C:\Users\...\OneDrive\Documents\Xenko Projects\MyGame6\MyGame6.sln.metaproj(0,0)]: Error: The specified solution configuration "Debug|MCD" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration.`

`[C:\Users\...\OneDrive\Documents\Xenko Projects\MyGame6\MyGame6.sln.metaproj(0,0)]: Verbose: Compiling game assemblies...`

`
[C:\Users\...\OneDrive\Documents\Xenko Projects\MyGame6\MyGame6.sln.metaproj(0,0)]: Verbose: Game assemblies compiled...`

Thanks in advance!

**Comment by Kryptos-FR** [comment]
From the logs: what is this "Debug|MCD" target in the project? And what is a `.metaproj`? @xen2 ever heard of that?

As far as I know, that's not something that we ship with Xenko. You might have some plugins in Visual Studio or else be doing some weird stuff. 

Also, I don't think that directly creating a created in a OneDrive folder is wise as it will keep trying to synchronize the files. When doing development, one should not use such backup systems (Google Drive, OneDrive...). Source control (git, SVN) is the way to go.

**Comment by FrodoDragons** [comment]
@Kryptos-FR I have no idea what Debug|MCD or .metaproj is. I'm very new to Xenco (haven't even gotten in yet, as you can tell), and only a beginner in C# (been learning for a few months)

And thanks for the tip, I wasn't planning on making it in OneDrive, but it got created there. Don't know if I just skimmed over it or what. If I move the whole folder, will it still work?
>

**Comment by xen2** [comment]
This might be fixed in latest Xenko 3.0.0.7 and 3.1 beta.
Can you give another try after updating to one of those versions?

**Comment by Eideren** [comment]
I'll close this one since it's unlikely the poster will get back to us and it's probably fixed by now.
