### ISSUE TITLE
Project disappears from launcher if project is exited without saving

### ISSUE THREAD

**Issue by AndreiNego** [stride3d/stride#1184]
**Release Type**: Official Release

**Version**: Launcher v5.0.5

**Platform(s)**: Windows

**Describe the bug**
Project disappears from projects in launcher if exited without saving

**To Reproduce**
0. Check 'close the launcher after starting stride'
1. Create a project
2. Save project and close stride 
3. open stride launcher and launch the project
4. wait until the save icon can be pressed
5. hit the close button on stride
6. in the save prompt choose 'don't save'
7. open the stride launcher again

**Expected behavior**
Projects should still appear in launcher in the order that they were last opened

**Screenshots**

**Log and callstacks**

**Additional context**

**Comment by AndreiNego** [comment]
Stride version 4.1.0.1459-beta

**Comment by Eideren** [comment]
Fixed through #1880
