### ISSUE TITLE
Add Open Collective Button to the Launcher

### ISSUE THREAD

**Issue by VaclavElias** [stride3d/stride#1187]
This needs to be done for these branches:

- [x] master - Pull Request created
- master-4.0 - It is not going to be port to this version

This was discussed here https://discord.com/channels/500285081265635328/727168636770582581/907948594970099733

Link: https://opencollective.com/stride3d
Image filename: opencollective-24.png
![opencollective-24](https://user-images.githubusercontent.com/4528464/141687187-0f0c566b-6961-4b8f-b80e-a56fb6bec939.png)

Question: BitmapScalingMode HighQuality style seems to create a better/sharper image than using existing NearestNeighbor. Not sure if it is only my PC. I will add some screenshots here.

```xaml
                  <Button Style="{StaticResource TransparentButtonStyle}" HorizontalAlignment="Left"
                        Command="{Binding OpenUrlCommand}"
                        CommandParameter="{x:Static r:Urls.OpenCollective}" SnapsToDevicePixels="True" Margin="2"
                        ToolTipService.IsEnabled="False"
                        ToolTip="{Binding CommandParameter, RelativeSource={RelativeSource Self}, Converter={sskk:FormatString}, ConverterParameter={x:Static r:Strings.ToolTipOpenLink}}"
                        Content="{sskk:Image {StaticResource ImageOpenCollective}, 24, 24, HighQuality}">
                    <i:Interaction.Behaviors>
                      <sskk:BindCurrentToolTipStringBehavior ToolTipTarget="{Binding CurrentToolTip}"
                                                     DefaultValue="{x:Static r:Strings.ToolTipDefault}"/>
                    </i:Interaction.Behaviors>
                  </Button>   
```

**Comment by VaclavElias** [comment]
@Eideren, @xen2. Please feel free to change BitmapScalingMode in the Button XAML.

Not sure if it is my PC but when I use **HighQuality** (see Twitter and OpenCollective) then it looks like this

![image](https://user-images.githubusercontent.com/4528464/142740741-c47db76c-ab7e-47c1-b672-7ee7c4d5951e.png)

If I leave the previous code **NearestNeighbor** it looks like this

![image](https://user-images.githubusercontent.com/4528464/142740775-0e50f047-26a8-4722-9258-91d6b0600871.png)

**Comment by Eideren** [comment]
In the screenshot you sent they are 30x30 instead of the 24x24 they should be at, nearest would look fine if that was the case. 
I checked it on master again just to be sure and they are 24x24 for me, is your screen scaling not set to 100%, not sure if that would affect it though ?

**Comment by VaclavElias** [comment]
They are 24x24 but it just loos like that on my screen I guess 
![image](https://user-images.githubusercontent.com/4528464/142741655-2c02aad4-445d-41d7-8217-e62875142bcc.png)

**Comment by Eideren** [comment]
They are 30x30 on this screenshot though

**Comment by VaclavElias** [comment]
I see now! It must be done by Windows then? I have got 4K screen so it is just my screen scaling it like that and then I assumed it looks wrong while it is not.

![image](https://user-images.githubusercontent.com/4528464/142741933-921ed712-e4af-48ca-bb68-87ecbf88b750.png)

**Comment by Eideren** [comment]
There's barely any difference at 24x24 between the two so you can set them to HighQuality in your PR to look better when display scaling is on.
![image](https://user-images.githubusercontent.com/5742236/142742641-cf922e60-6f63-49c1-99b6-3fb571bb3ef2.png)

**Comment by VaclavElias** [comment]
Done!

@Eideren, shall I do this PR also for master-4.0?

**Comment by Eideren** [comment]
Yes, thanks a bunch ! Don't forget to set highquality for the other icons as well though ! ( facebook, reddit, discord, github, etc.)

**Comment by Aggror** [comment]
Nice work @VaclavElias

**Comment by VaclavElias** [comment]
@Eideren, @Aggror, I will do that in a separate PR regarding the remaining icons.

**Comment by VaclavElias** [comment]
@Eideren, please, could you confirm this is also needed for master-4.0. I wasn't able to test it because master-4.0 Launcher starts 5.0.4 version where are my changes and instantly it is updated with 5.0.5 launcher which is not in the master-4.0?

Also, Manio143 said:

> I don't think it makes sense to port launcher changes to master-4.0

**Comment by Eideren** [comment]
I agree with Manio on this, no need to port it over to 4.0. The launcher auto-updates to the latest, so if users have access to the internet, which they would need to use those links, they'll have the latest launcher installed with your fix in it

**Comment by VaclavElias** [comment]
Thanks, in that case, closing this.
