### ISSUE TITLE
Array not serialize and deserialize properly causing editor crash

### ISSUE THREAD

**Issue by D3ZAX** [stride3d/stride#1189]
When array with some elements is a public property of a script, save the project and reopen the project will crash the editor.

It was caused by the set support pr, and I have pushed a new pr to fix this bug, hope it can be merged soon.

Fixed pr: [D3ZAX:ArrayFix](https://github.com/stride3d/stride/pull/1178)

**Comment by Eideren** [comment]
PR merged
