### ISSUE TITLE
Stride Net6 - Master - Exceptions when building new game/GameStudio

### ISSUE THREAD

**Issue by joe88ds** [stride3d/stride#1219]
**Release Type**: master branch

**Version**: 4.1.0.1-net6

**Platform(s)**: Windows 10 x64

**Describe the bug**
multiple exceptions, probably something to do with texture loading

**To Reproduce**
[stride-net6.zip](https://github.com/stride3d/stride/files/7713223/stride-net6.zip)
1. Run GameStudio from Visual Studio 2022 (Debug | Mixed Platforms)
2. Run MyGame2-net6 from Visual Studio 2022 (Debug | Mixed Platforms)

**Log and callstacks**
log files inside zip

**Additional context**
I also tried running the build/Stride.Launcher.sln and I get this exception (which may or may not be related to above issues):
System.Windows.Markup.XamlParseException: ''Initialization of 'System.Windows.Media.Imaging.BitmapImage' threw an exception.' Line number '43' and line position '44'.' COMException: The component cannot be found. (0x88982F50)

**Comment by Eideren** [comment]
Can't reproduce on latest after changing nuget version target from ``4.1.0.1-net6`` to ``4.1.0.1-beta``, probably unrelated to your issue though. Could you try again on latest ?

**Comment by joe88ds** [comment]
I've not had any of these exceptions when running latest. At this point, I will close this issue.
