### ISSUE TITLE
PrimitiveProceduralModelBase - Overload for Generate

### ISSUE THREAD

**Issue by VaclavElias** [stride3d/stride#1258]
**Is your feature request related to a problem? Please describe.**
Simplifying creation of primitive objects, it will improve code-only approach and also just saving a few lines of code generally for anyone. @Eideren mentioned this in his comment (https://github.com/stride3d/stride/discussions/1253) and I think it is easy to implement.

**Describe the solution you'd like**
One option should be easy, just adding an overload for existing **Generate** method in **PrimitiveProceduralModelBase.cs** 

And another improvement could be adding a helper to simplify a call even further. Unity has a static class CreatePrimitive which is on GameObject. 
![image](https://user-images.githubusercontent.com/4528464/147957359-6879b8f4-d662-4980-8c3d-e711773c71f9.png)

You can assign this to me. When I start working on this, we can discuss further.

**Comment by VaclavElias** [comment]
Is this implementation ok and shall I create a test for it?

```c#
public Model Generate(IServiceRegistry services)
{
    var model = new Model();

    Generate(services, model);

    return model;
}
```
Lines 79-86 added here

![image](https://user-images.githubusercontent.com/4528464/149639284-e8455b6e-ac8e-4544-b58f-b08ce42fa77a.png)

**Comment by Eideren** [comment]
Looks good ! I wouldn't bother with a test given how simple that implementation is
