### ISSUE TITLE
Adding Light areas + spherical lights enhancements

### ISSUE THREAD

**Issue by ykafia** [stride3d/stride#1269]
Stride's light calculations are partly based on [this Frostbite presentation.](https://www.ea.com/frostbite/news/moving-frostbite-to-pb)

Disc, rectangular and tube shaped lights can be implemented based on these presentation.
We could also use [LTC for area of light's BRDF](https://eheitzresearch.wordpress.com/415-2/) for a faster computation.

Another more recent implementation of [linear light shading](https://hal.archives-ouvertes.fr/hal-02155101) can also be useful to create tube lights using LTC.

**Comment by ykafia** [comment]
I've already started some work on area light shading, but I will write a little post on how to get started with creating a new light for anyone that wants to understand the lighting system and help with this issue. 

I forgot there was #800 which one should we keep?

**Comment by Eideren** [comment]
Let's close this one, you could edit your messages over there if you need to add more info
