### ISSUE TITLE
Default SceneInstance and Scene

### ISSUE THREAD

**Issue by VaclavElias** [stride3d/stride#1290]
We have been discussing here https://github.com/stride3d/stride/discussions/1253 code-only approach and we are looking for options to update engine if possible to simplify certain defaults being created without Stride Game Studio.

**Describe the solution you'd like**
We are going to add else branch so we can ensure that Scene is never null here 

https://github.com/stride3d/stride/blob/b9b2dbb380f39ea02dab3c65cc0ae1b68e7c2f51/sources/engine/Stride.Engine/Engine/SceneSystem.cs#L115-L121

```c# 
else
{
   SceneInstance ??= new SceneInstance(Services) { RootScene = new Scene() };
}
```

**Describe alternatives you've considered**
We discussed an alternative to create a default Scene in the extension also described in the discussion above but decided rather to update engine instead in this case.

**Additional context**
Empty scene is created when using Stride Game Studio so if the code-only approach is used there should also be a default empty Scene created.

**Comment by VaclavElias** [comment]
You can assign this to me. Thanks.

**Comment by najak3d** [comment]
Wow, sweet.  I just came here planning to submit this issue.  Glad to see you "already on it!" :)   Looks like we're of similar mindset here.

Along with this change, should also come "Game.DefaultSettings" concept, so that we don't require the ".sdgamesettings" asset from Stride Editor.

**Comment by VaclavElias** [comment]
@najak3d, thanks for your comments and suggestions here and in the discussion. In the working code-only prototype **Game.DefaultSettings** is not needed 😀. The plan is that you literally just create a new .NET 6 console app, reference Stride package(s) and you are done.

I will further elaborate on your other comments from the discussion separately. 

I am going to create a new issue "Code-Only implementation" where I summarise all from the discussion https://github.com/stride3d/stride/discussions/1253. 

And ask the community for further updates and suggestions. 

Thanks 😀

**Comment by najak3d** [comment]
Can you create this as a Samples Suite - that starts out with a scrollable menu of samples.   Click one, and it takes you to that sample scene.  Then you can have several for GUI, some for Physics, some for 1st person controller, etc... 

Once you have a structure like this, it makes it trivial to add new samples, and makes it easier to collaborate.  Call the solution "StrideCodeSamples" -- and it can have 50-100 such samples in the list.   Might even have a double-layered list -- to categorize them by topic -- e.g.   Physics, vs UI vs Material Effects .   Then each of those groups has 2+ samples.

**Comment by najak3d** [comment]
Once you have a structure in place like that, we can make the list of "desired samples", then anyone (like me) with some time to implement one, can go ahead and add it.

**Comment by najak3d** [comment]
Urho has something like this with like 60 samples..  It was very appealing, and gave us the immediate perception of "Completeness" and "Quality" -- because all samples ran equally well on Windows, iOS, and Android.    That should be the goal of this whole project --- always work on the main platforms.   Download the zip, unzip  and double-click the .sln -- and poof, you see it working perfect everywhere.   BOOM!   You'll have more customers quickly.

In open-source world, of course, that means more pain/headaches, because customers are a pain.   But then, money-making opportunity arise, which then makes customers a very sweet prospect.

**Comment by najak3d** [comment]
And most likely, "more customers" will mean "more contributors", which helps everyone.
