### ISSUE TITLE
Renaming a new asset in a new unsaved folder crashes editor

### ISSUE THREAD

**Issue by Aggror** [stride3d/stride#1299]
**Release Type**: Master 4.1

**Version**: 4.1.0.1-beta

**Platform(s)**: Windows

**Describe the bug**
It has happened several times now, that during development, I create a new entity (model, material and scene) and I want to rename it by pressing F2. At that moment the editor crashes.

**To Reproduce**
Steps that reproduce the behavior:
1. Open project
4. Add a new folder to the assets (but dont save yet)
4. Add a new scene to the newly created folder
5. Press F2 to rename scene
6. Editor crashes

**Log and callstacks**
[bugreport renaming.txt](https://github.com/stride3d/stride/files/7928782/bugreport.renaming.txt)

**Comment by acastrodev** [comment]
@Aggror Is it still occurring in version 4.1.0.1898? I couldn't replicate the issue.

**Comment by NicusorN5** [comment]
I can't seem to reproduce this either.

**Comment by Eideren** [comment]
Thanks for checking @acastrodev @NicusorN5 , I'll close this one off then
