### ISSUE TITLE
InputManager and  DownButtons return incorrect collection

### ISSUE THREAD

**Issue by dawnmichal** [stride3d/stride#1303]
**Release Type**: Official Release

**Version**: 4.1.0.1459-beta

**Platform(s)**: Windows

**Describe the bug**
When pressing two buttons and then only one is released Input.DownButtons is empty.

**To Reproduce**
1. Nothing is pressed = Input.DownButtons is empty
2. pressed RMB = Input.DownButtons contains Right
3. pressed LMB and still holding RMB = Input.DownButtons contains Right and Left. So far so good, but now...
4. release only LMB = Input.DownButtons is empty?

**Expected behavior**
Input.DownButtons should contain Right mouse button at step 4.

**Comment by Eideren** [comment]
Could repro, see #1304

**Comment by dawnmichal** [comment]
Just FYI study case. RMB is used for getting ready (rise) weapon from lower pose. LMB is for fire. So because of this bug character goes to lower state after fire though player still holding RMB.
