### ISSUE TITLE
Can't isntal Visual Studio extension from launcher

### ISSUE THREAD

**Issue by KuraiAndras** [stride3d/stride#1306]
**Release Type**: Official Release

**Version**:
- Launcher: 5.0.5
- Stride: 4.1.0.1459-beta

**Platform(s)**: Windows 11, Visual Studio 2022 17.0.5

**Describe the bug**
VSIX installer fails.

**To Reproduce**
1. Install Stride launcher
2. Click `Install Visual Studio plugin`

**Expected behavior**
VSIX installs without an error

**Screenshots**
![image](https://user-images.githubusercontent.com/19240945/151660522-d369dbbd-6f50-450c-876e-2b56f659b9b1.png)
![image](https://user-images.githubusercontent.com/19240945/151660552-85a60070-fa2f-43cb-927e-429028d5dd7b.png)

**Log and callstacks**
[dd_VSIXInstaller_20220129131228_8368.log](https://github.com/stride3d/stride/files/7963624/dd_VSIXInstaller_20220129131228_8368.log)
[dd_VSIXInstaller_20220129130651_0c78.log](https://github.com/stride3d/stride/files/7963625/dd_VSIXInstaller_20220129130651_0c78.log)

**Comment by MistahJ26** [comment]
I ran into this same issue, I reinstalled VS 2019 instead and didn't get the error message. So it's an issue related to using the new version of VS.

**Comment by ericwj** [comment]
Is it difficult to release the .vsix to Visual Studio Marketplace? I had issues before 4.1 released over first not being able to install the 2022 extension and second the button in the launcher only picking an old VS2017 which I didn't want to change. After 4.1 released I got stuck again with the new button disabled for non-apparent reasons. Third having it published to the marketplace will sync installation with my Visual Studio account, allow me to pick which exact version to install, allow changing the version between published and built from source. Etc

**Comment by ericwj** [comment]
I think the project should have an account on the marketplace and just publish the vsix whenever Stride is released?
