### ISSUE TITLE
Support for visual code/scripting . .

### ISSUE THREAD

**Issue by charlesmlamb** [stride3d/stride#1340]
**Is your feature request related to a problem? Please describe.**
Hello, I use visual script in other engines, I realize it's a difficult feature, to code well, wanted to ask, thx . . .

**Describe the solution you'd like**
In essence, I'd like a visual scripting system, similar to Unreal, or Cryengine . . .

**Describe alternatives you've considered**
Well, it's very nice for beginners, to be able to LEARN, or understand code, using visual script, I'd like it primarily as a teaching tool, if possible, also make it into C#, or so . . .

**Additional context**
Well, it makes engines much more beginner - friendly, I'd use it as a teaching tool, so, it mainly helps people learn C#, and, understand how code works, or, how systems, or, some logic works, etc . .

**Comment by ykafia** [comment]
Hi! I think it's better if the discussion continues in #19

**Comment by Eideren** [comment]
Yep, duplicate
