### ISSUE TITLE
Use new flip model for dx11 swapchain

### ISSUE THREAD

**Issue by tebjan** [stride3d/stride#1344]
**Is your feature request related to a problem? Please describe.**

According to this article, 3d applications shouldn't use the old "blt" mode anymore:
https://devblogs.microsoft.com/directx/dxgi-flip-model/

**Describe the solution you'd like**

Change the swapchain mode when flip model is available.

**Additional context**

This would be a free performance improvement.

**Comment by azeno** [comment]
Just did a quick test rendering a quad in a 1920x1200 window and the GPU load on a RTX 2070 went down from 20% to 0% using `FlipDiscard`.
