### ISSUE TITLE
Easy one here -- Need Null Check in ModelRenderProcessor.UpdateMaterial

### ISSUE THREAD

**Issue by najak3d** [stride3d/stride#1366]
This might be indicative of another bug, but I'm seeing a frequent null-exception occur on this line of code (marked "HERE" below).   The "renderMesh.MaterialPass" is NULL, and thus it throws, when it should probably drop to the final line of this method where it assigns it to non-Null.
===

        private void UpdateMaterial(RenderMesh renderMesh, MaterialPass materialPass, MaterialInstance modelMaterialInstance, ModelComponent modelComponent)
        {
            var isShadowCaster = modelComponent.IsShadowCaster;
            if (modelMaterialInstance != null)
                isShadowCaster &= modelMaterialInstance.IsShadowCaster;

            if (isShadowCaster != renderMesh.IsShadowCaster
                || materialPass.HasTransparency != renderMesh.MaterialPass.HasTransparency)   // <<+===== HERE!
            {
                renderMesh.IsShadowCaster = isShadowCaster;
                VisibilityGroup.NeedActiveRenderStageReevaluation = true;
            }

            renderMesh.MaterialPass = materialPass;
        }

**Comment by Eideren** [comment]
Perhaps related to @tebjan's #1346

**Comment by tebjan** [comment]
Yes, looks like a missing null check in my PR, thanks for the report.
