### ISSUE TITLE
Release notes for version 4.1

### ISSUE THREAD

**Issue by ykafia** [stride3d/stride#1386]
Push the release notes for the version 4.1

Current work on it : https://hackmd.io/CzSvxiluSaK9CHHLNWvIgQ

**Comment by Aggror** [comment]
@ykafia I can provide you with some images for the release notes. I will add the images in the hackmd file, but the actual images will have to be donwloaded to the specific local folder, once the release notes are added to the site. Is it okay if I post them here?

**Comment by ykafia** [comment]
Yes sure!

**Comment by Eideren** [comment]
I fixed a bunch of typos, reworded a couple of sentences and left comments on the hack.md document

**Comment by ykafia** [comment]
Thanks a bunch, i will working on it today hopefully

**Comment by Eideren** [comment]
Yes, I should have a bit more time to work on the two clauses I added at the end of the document

**Comment by Aggror** [comment]
Should we included the amount that people have donated? 
I made a csv export and organised the relevant data. Added some base text for the (financial) contributors. https://docs.google.com/spreadsheets/d/1fxsZqYBJUuSZ8lH05FjcHzx-8saIs_NBW77azKEnb_g/edit?usp=sharing

**Comment by ykafia** [comment]
Could be a great idea to add this info on the call for action section, something like a "thank you" note and a reminder that this money is here for contributors.

**Comment by Aggror** [comment]
updated the release notes slightly, with the call to arms. Eideren had a good argument regarding 'what is strider' (ergo removing this section).  How about the listing of the Github contributors?

**Comment by Eideren** [comment]
Removed the aforementioned section, rewrote a couple of sentences. Where do we want to go from there ? Write sections for the major features / changes ? Tutorial needs one I think but what about the rest ?

**Comment by Aggror** [comment]
Added some more details, screenshots and videos underneath the summary.

**Comment by VaclavElias** [comment]
This is a checklist from another version of the above document..

## Existing Pages need to be updated?
- [ ] Manual - [Requirements](https://doc.stride3d.net/latest/en/manual/requirements/index.html)
    - Update IDE to VS 2022
    - Update Run games made with Stride section?
- [ ] Manual - [Install Stride](https://doc.stride3d.net/latest/en/manual/get-started/install-stride.html)
    - New screenshots?
    - No need .NET 4.7.2?
- [ ] Manual - [Launch Stride](https://doc.stride3d.net/latest/en/manual/get-started/launch-stride.html)
- [ ] Manual - [Visual Studio extension](https://doc.stride3d.net/latest/en/manual/get-started/visual-studio-extension.html)
- [ ] Stride Web - Home Page
    - Mention C# 10, .NET 6 (web search / SEO purpose)
- [ ] Manual - Features Page
    - Mention C# 10, .NET 6 (web search / SEO purpose)

**Comment by xen2** [comment]
Added latest version to doc and website repo
