### ISSUE TITLE
Found a fix for the error "The reference assemblies for framework [nameofframework] were not found"

### ISSUE THREAD

**Issue by SeleDreams** [stride3d/stride#142]
Hello, i'm posting this issue since it could help people who get this error, i got this error for a long time and finding a fix was really a pain but i've finally be able to fix it, it's not that hard
You must set an environment variable named "ReferenceAssemblyRoot" and set it to the path where you have installed your .NET Framework, in my case it was "D:\Program Files (x86)\Reference Assemblies\Microsoft\Framework"
after doing that, xenko ended up finding the references and building correctly my project

I wasn't sure if posting it here was the right way but i feel like maybe adding a kind of Q&A with fixes to this kind of errors could help a lot of people

**Comment by Eideren** [comment]
This should not happen, if you have a repro please create a new issue with it ! Closing this one off until then.
