### ISSUE TITLE
VRSandbox does not compile, editor does not launch

### ISSUE THREAD

**Issue by breakerofbuilds** [stride3d/stride#1457]
**Release Type**: Official Release

**Version**: 4.1.0.1731

**Platform(s)**: Windows

**Describe the bug**
1. Syntax errors in the VRSandbox template 
2. Stride editor fail to launch based on above error

**To Reproduce**
1. Create a new project based on the VRSandbox template

**Expected behavior**
1. Project should compile
2. Editor should still be able to launch with syntax errors in the project C# code.

**Screenshots**
![image](https://user-images.githubusercontent.com/104224536/179399856-d9dd6e51-2b36-4d1e-a63d-7d93efbfdc3d.png)
![image](https://user-images.githubusercontent.com/104224536/179399859-82be0586-2117-446b-882e-f06bc3431777.png)
![image](https://user-images.githubusercontent.com/104224536/179399861-84e2e633-1ec7-481b-adf4-edcce375b120.png)
![image](https://user-images.githubusercontent.com/104224536/179399863-b986a913-8aba-4add-a0c6-05442f66370f.png)
![image](https://user-images.githubusercontent.com/104224536/179399865-c5e5ff69-64a3-46bf-bc3a-e075d7ae84d2.png)
![image](https://user-images.githubusercontent.com/104224536/179399871-3ad5bda0-f762-4fe8-973b-fb7bf64b1631.png)

**Log and callstacks**
[log.txt](https://github.com/stride3d/stride/files/9127697/log.txt)

**Additional context**
After fixing the syntax errors in the source file, [removing the two '?'](https://github.com/stride3d/stride/blob/ff876066ac4fc5fa1c8e67efebe54b5365e98c0d/samples/Templates/VRSandbox/VRSandbox/VRSandbox.Game/Player/HandController.cs#L117), I can load the project.

**Comment by tebjan** [comment]
Hey, thanks for the detailed report. It looks like the data type has changed from class to struct. Should be an easy fix. thanks!
