### ISSUE TITLE
Prefab.instantiate() seems to not use the same material instance as the prefab.

### ISSUE THREAD

**Issue by justStand** [stride3d/stride#149]
I've created a simple computecolor shader that will change the color depending on the x position of the camera.

I created a prefab with a material that has this shader on it.

The shader only responds to the camera position if the prefab was added to the scene using the scene editor, or the prefab was added directly to the scene (not instantiated.)
``
            Prefab prefab = Content.Load<Prefab>("TestPrefab");
            SceneSystem.SceneInstance.RootScene.Entities.AddRange(prefab.Entities);
``

If I use prefab.instantiate and add the objects that this creates to the scene, they don't respond to the camera position.

**Comment by Eideren** [comment]
Instantiate is similar to a deep copy so this should be expected behavior, closing this one off.
The solution to that would be to set the material of the instantiated model to that of the original.
