### ISSUE TITLE
PhysicsComponent created with `GetOrCreate<T>` is unusable

### ISSUE THREAD

**Issue by manio143** [stride3d/stride#1504]
**Release Type**: Official Release

**Version**: any

**Describe the bug**
When a physics component, such as `RigidbodyComponent` is obtained through `GetOrCreate<T>` method on an entity, it is attached before the user had a chance to configure it. There's checks in the internal `Attach` method on the physics component which checks if a collider shape is set and if not, it exits without performing additional step - this makes the component enter a state where setting any of the properties afterwards results in no-op.

**To Reproduce**

```csharp
var body = Entity.GetOrCreate<RigidbodyComponent>();
body.ColliderShape = new SphereColliderShape(false, 1.0f);
Debug.Assert(body.ColliderShape != null);
```

**Expected behavior**
Either we should allow the user to add a physics component in this way and modify the internals such that if a collider shape is set after attachment it performs work to bring the component back into good shape; Or we need to allow component creators to disallow them being instantiated with `GetOrCreate` and force users to create the component themselves, by throwing an explanatory exception.

**Additional context**
https://github.com/stride3d/stride/blob/b11317c9389b33bce5bc2de550a0e501dc024694/sources/engine/Stride.Physics/Engine/PhysicsComponent.cs#L685-L689
This makes us not call OnAttach a few lines later which means we don't execute
https://github.com/stride3d/stride/blob/b11317c9389b33bce5bc2de550a0e501dc024694/sources/engine/Stride.Physics/Elements/RigidbodyComponent.cs#L305-L309
And thus `InternalRigidBody` is `null`
https://github.com/stride3d/stride/blob/b11317c9389b33bce5bc2de550a0e501dc024694/sources/engine/Stride.Physics/Elements/RigidbodyComponent.cs#L103-L117

**Comment by dloe** [comment]
Hello! If possible I would like to work this issue! Had a quick question, in the reproduction of this bug I'm assuming this is done in just an simple example project and not in the test suites. Is there an expectation that the Debug.Assert displays a message?

Other than that, I understand and see the issue with InternalRigidBody and other code not being set up properly.

In terms of which of the two suggested solutions to go for, maybe a good starting place could be adding some type of verification on the RigidBodyComponent setter that could properly run the missing OnAttach setup?

**Comment by IXLLEGACYIXL** [comment]
https://github.com/stride3d/stride/pull/2131
As physics is getting reworked is it worth to fix bullet implementation?

**Comment by Doprez** [comment]
> #2131 As physics is getting reworked is it worth to fix bullet implementation?

I would say yes, there is no defined release for the Bepu PR so far and there are still going to be projects that use Bullet that will benefit from this even when Bepu is released.

> Hello! If possible I would like to work this issue! Had a quick question, in the reproduction of this bug I'm assuming this is done in just an simple example project and not in the test suites. Is there an expectation that the Debug.Assert displays a message?

I would say yes if there is something useful to say, more info will never hurt. When a new user looks at this code a message could give a good hint of guidance.

> In terms of which of the two suggested solutions to go for, maybe a good starting place could be adding some type of verification on the RigidBodyComponent setter that could properly run the missing OnAttach setup?

This sounds like a reasonable solution but Ill let @Eideren or @manio143 confirm on that since there may be another way.

**Comment by Eideren** [comment]
Yep, that's what we're doing for bepu, it would still log the issue initially but that's fine

**Comment by Eideren** [comment]
It can get a bit tricky to cover that issue properly, don't hesitate to have a look at how we're doing it in bepu. The main method is this one https://github.com/stride3d/stride/blob/7c9662b3949214c4781e365cdf32ab433c08ac32/sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/CollidableComponent.cs#L195 probably best to clone it locally so you can have a look at the callers and such
