### ISSUE TITLE
Editor architecture, keep interface centric or flatten?

### ISSUE THREAD

**Issue by MechWarrior99** [stride3d/stride#1507]
I am working on cleaning up the editor/presentation/game studio code to make it more streamlined, easier to read, and expand so that it can be switched over to using Avalonia UI.

Currently the architecture is very interface centric. This of course makes it very flexible, and extensible. But also can make it much harder to follow the code and tell exactly what is going on at a given point. What is being passed to methods or being accessed, etc.

So my question is, should the architecture be flattened in some places, removing some of the interfaces. Or would it be better to leave  it with its current design using many interfaces?

**Comment by manio143** [comment]
Can you provide some examples, like where the interfaces are used (especially regarding cross project boundaries), which ones you see as viable for removing, etc?

From my memory there was heavier use of abstract classes than interfaces overall, and I don't remember there being many single implementation interfaces - which is exactly the point of having the abstraction in place.

My stance is: well defined abstractions will make code more universal and easier to write when things behave according to the interface. If there need to be workarounds/abstraction is leaking then the interface is only making things more complicated.
I'd be for keeping the abstraction, or potentially rewriting some of it to be cleaner and only if it's not necessary (there would only be one implementation and we don't see that changing soon) removing it.

**Comment by MechWarrior99** [comment]
> Can you provide some examples, like where the interfaces are used (especially regarding cross project boundaries), which ones you see as viable for removing, etc?

Sure, a really simple example is the[ IUndoRedoService](https://github.com/stride3d/stride/blob/master/sources/presentation/Stride.Core.Presentation/Services/IUndoRedoService.cs) which is only implemented by the [UndoRedoService](https://github.com/stride3d/stride/blob/master/sources/presentation/Stride.Core.Presentation/Services/UndoRedoService.cs).

Another slightly more involved example is the [IDialogService](https://github.com/stride3d/stride/blob/master/sources/presentation/Stride.Core.Presentation/Services/IDialogService.cs). It is only inherited from by  other interfaces and a single class. And the only classes that implement those interfaces also inherit from the one class.

A more complicated example is the Quantum [IGraphNode](https://github.com/stride3d/stride/blob/master/sources/presentation/Stride.Core.Quantum/IGraphNode.cs). The only class that directly implements it is the [GraphNodeBase](https://github.com/stride3d/stride/blob/master/sources/presentation/Stride.Core.Quantum/GraphNodeBase.cs). But there are a number of other interfaces that also implement it like the Assets.Quantum [IAssetNode](https://github.com/stride3d/stride/blob/master/sources/assets/Stride.Core.Assets.Quantum/IAssetNode.cs). However the only class that implements _that_ interfaces also ultimately inherits from `GraphNodeBase`.
There is a lot of this in Quantum.

A bit off topic, but I also wonder for things like the `UndoRedoService`, where only a single instance is ever created in a session if using a static class would be easier to use?

**Comment by MechWarrior99** [comment]
The general consciences is to keep the abstraction and interfaces, so will do. Closing the issue.
