### ISSUE TITLE
Stride Launcher - Start causing error

### ISSUE THREAD

**Issue by VaclavElias** [stride3d/stride#1509]
The Stride Launcher silently dies when I click on the button **Start 4.1.1.1734**  but the error is in the Event Viewer.

Visual Studio 2022 wasn't installed. .NET 6 Runtime was installed.

Application: Stride.GameStudio.exe
CoreCLR Version: 6.0.822.36306
.NET Version: 6.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Stride.Rendering.BackgroundCubemapShaderKeys' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Stride.Core.Native.NativeInvoke' threw an exception.
 ---> System.InvalidOperationException: Could not load native library libcore using CPU architecture x64.
   at Stride.Core.NativeLibraryHelper.PreloadLibrary(String libraryName, Type owner) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Native\NativeLibraryHelper.cs:line 137
   at Stride.Core.Native.NativeInvoke..cctor() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Native\NativeInvoke.cs:line 24
   --- End of inner exception stack trace ---
   at Stride.Core.Native.NativeInvoke.Setup() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Native\NativeInvoke.cs:line 50
   at Stride.Native.Module.Initialize() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Native\NativeInvoke.cs:line 46
   at .cctor()
   --- End of inner exception stack trace ---
   at Stride.Core.DataSerializers.Stride_GraphicsSerializerFactory.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
   at Stride.Rendering.BackgroundCubemapShaderKeys..cctor()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(RuntimeTypeHandle type)
   at .cctor()
   --- End of inner exception stack trace ---
   at Stride.Core.Serialization.AssemblyScan.Stride_EngineAssemblyScan.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
   at Stride.Core.DataSerializers.Stride_AssetsSerializerFactory.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
   at Stride.Core.DataSerializers.Stride_EditorSerializerFactory.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
   at Stride.GameStudio.Program.Main()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.AppDomain.ExecuteAssembly(Assembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at Stride.NuGetLoader.Program.Main(String[] args) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\tools\Stride.NuGetLoader\Program.cs:line 24

**Update 30/09/2023** 

The same error happens with **code-only** approach if Microsoft Visual C++ Redistributable is not installed.

**Comment by VaclavElias** [comment]
Once I installed VS 2022, the error is gone and all is working.

This test was done to update accordingly Install Stride page https://doc.stride3d.net/latest/en/manual/get-started/install-stride.html. 

The page needs to have some prerequisites mentioned..

**Comment by manio143** [comment]
This sounds like VCRedist missing

**Comment by VaclavElias** [comment]
Thanks, I will double check it and test further the instructions above from the manual.

There is this step, which didn't work and probably needs to be done manually...

12. The Stride Launcher checks if the prerequisite Visual C++ Redistributable is installed. If it's not installed, follow the prompts to install it.

**Comment by VaclavElias** [comment]
This is an additional related error. Testing the same on the clean Windows install.

```
C:\Users\Vacla\.nuget\packages\stride.core.assets.compilerapp\4.1.0.1838\buildTransitive\Stride.Core.Assets.CompilerApp.targets(132,5): error MSB3073: The command ""C:\Users\Vacla\.nuget\packages\strid
e.core.assets.compilerapp\4.1.0.1838\buildTransitive\..\tools\net6.0-windows7.0\Stride.Core.Assets.CompilerApp.exe"  --disable-auto-compile --project-configuration "Debug" --platform=Windows --project-
configuration=Debug --compile-property:StrideGraphicsApi=Direct3D11 --output-path="C:\Users\Vacla\Downloads\examples\example01\bin\Debug\net6.0\data" --build-path="C:\Users\Vacla\Downloads\examples\exa
mple01\obj\stride\assetbuild\data" --package-file="C:\Users\Vacla\Downloads\examples\example01\example01.csproj" --msbuild-uptodatecheck-filebase="C:\Users\Vacla\Downloads\examples\example01\obj\Debug\
net6.0\stride\assetcompiler-uptodatecheck"" exited with code -532462766. [C:\Users\Vacla\Downloads\examples\example01\example01.csproj]
```

**Comment by VaclavElias** [comment]
As of today, I only installed this one **Microsoft Visual C++ 2015-2022 Redistributable** https://aka.ms/vs/17/release/vc_redist.x64.exe to make it working for code-only.

The problem is for sure missing VCRedist.

Closing as resolved as the prerequisites must be followed.

**Comment by Eideren** [comment]
Should we change this to an enhancement to include/fix the redist in the installer ?

**Comment by VaclavElias** [comment]
This below is now the bare minimum to run Stride code only on the clean Windows installation. There would be more needed for the Stride Installer and Game Studio. Let's reopen because I will be testing these scenarios on clean Windows installation and maybe I can confirm if the **Microsoft Visual C++ 2015-2022 Redistributable** is enough or we need also those previous versions.

![image](https://github.com/stride3d/stride/assets/4528464/0657693b-2dce-4951-9d97-5e070acc19d7)

**Comment by VaclavElias** [comment]
Closing this as this specific issue can't be recreated. I will create a new issue related to my new findings.

**Comment by xen2** [comment]
When you reference `Stride.Core`, it supposedly include this target in the build file that checks for VC 2019 redist
https://github.com/stride3d/stride/blob/4aba569074393fb38329a07a82d5001c8c7523e6/sources/core/Stride.Core/build/Stride.Core.targets#L16
Maybe we need to bump the version checked? Or verify the check is happening in this case?

**Comment by VaclavElias** [comment]
I can't reproduce the original issue anymore, however, the related issue is this, see the screenshot. It happens only on clean win 11 pc, when .NET 8 SDK was installed. When I reopen the Stride Launcher, then all is ok. So it seems that, when the PATH is updated, Stride Launcher is not able to find it, till it is restarted. I might have been related with the original issue here but at least now we get this error message. If it is our error, we could sugggest to restart the Stride Launcher, or PC.

![image](https://github.com/user-attachments/assets/b7f89a84-de83-4783-953b-335b84720ec3)

> Maybe we need to bump the version checked? Or verify the check is happening in this case?

Probably, the Runtime 2022 might be enough, as that is all I need for codd-only. I can try to test it if it is enough also for Stride Launcher and a regular Stride project.
