### ISSUE TITLE
Matrix.Decompose(yaw/pitch/roll) method not always correct

### ISSUE THREAD

**Issue by Basewq** [stride3d/stride#1528]
**Release Type**: Official Release

**Version**: 4.1.0.1734 (and any previous)

**Platform(s)**: Windows

**Describe the bug**
Rotation matrix won't always output correct yaw/pitch/roll values on certain angles from a Quaternion for the method `Decompose(out float yaw, out float pitch, out float roll)`
[This method is used by Game Studio in the entity transform Rotation property](https://github.com/stride3d/stride/blob/7e836297cb5930c01e6dfa0183e7f3cc64748fb6/sources/presentation/Stride.Core.Presentation/Controls/RotationEditor.cs) which is why I noticed it.

**To Reproduce**
This can be seen in the Editor:
1. Select an entity
2. Change Transform.Rotation to (90, 0, 90)
3. Select another entity
4. Select previous entity and review the Transform.Rotation (which is now shows (89.972, 0, 0))

Alternatively, code to reproduce this issue:
```
var yaw = MathUtil.DegreesToRadians(90);
var pitch = 0f;
var roll = MathUtil.DegreesToRadians(90);
var quat = Quaternion.RotationYawPitchRoll(yaw, pitch, roll);

var mat = Matrix.RotationQuaternion(quat);
mat.Decompose(out float decomposedYaw, out float decomposedPitch, out float decomposedRoll);

Assert.Equal(yaw, decomposedYaw);    // Technically fails due to precision loss
Assert.Equal(pitch, decomposedPitch);
Assert.Equal(roll, decomposedRoll);  // Not matching (returns 0 instead of Pi/2)
```

**Expected behavior**
Decompose should output the same as input (or close enough since precision loss may occur).

**Additional context**
Note that `Quaternion.RotationYawPitchRoll` and `Matrix.RotationQuaternion` are probably not the issue (except for the low precision due to being floats), as they are fairly standard code (I've looked around online). 
The relevant method is this:
https://github.com/stride3d/stride/blob/ca3dc903f72d586c95311049bdc8c16d571ac718/sources/core/Stride.Core.Mathematics/Matrix.cs#L630-L643

I have no idea how this method actually works and does not appear to be some standard solution, I suspect the code is not correctly handling certain edge case values, which may be exacerbated due to the precision loss from using floats (eg. `MathUtil.DegreesToRadians(90)` involves Pi).

**Comment by ShadowTeolog** [comment]
Look like RotationYawPitchRoll one side operatation, (yaw, pitch, roll) can't be restored, more then one (yaw, pitch, roll) set gives same Quaternion result

**Comment by Basewq** [comment]
> Look like RotationYawPitchRoll one side operatation, (yaw, pitch, roll) can't be restored, more then one (yaw, pitch, roll) set gives same Quaternion result

You're right. For the editor to restore it properly (in the Rotation property) it needs to also store the user's actual yaw/pitch/roll values.
For the time being I am fixing it so it would still at least return a valid combination of yaw/pitch/roll since it's not doing so in the edge cases.
