### ISSUE TITLE
.Net 6.0 framework not detected and launcher crash

### ISSUE THREAD

**Issue by ChanceVincent** [stride3d/stride#1556]
**Release Type**: Latest version
**Version**: 4.1.0.1734
**Platform(s)**: Windows

**Describe the bug**
Two issue:
Issue #1) The launcher prompted me to install .Net 6.0 framework. I installed it, but it still says I need .Net framework. I rebooted this computer in case that did anything for the .Net installation, the launcher still says the same thing.

Issue #2) The launcher crashes if the updater fails.

**To Reproduce**
#1) First-time install of stride launcher, installed latest stride version, and then this happened. I have not yet been able to run stride game studio because of the .Net framework error I get instead.

#2) Unplug your internet and try to run the launcher. It will give an error saying the update failed and then crash.

**Expected behavior**
I expected the stride game studio to run after I installed the .Net 6.0 framework and clicked the red "start..." button.

**Screenshots**
![StrideError](https://user-images.githubusercontent.com/117070772/198963623-0a68b7ed-0d6f-4869-8e53-7a2db8a03bea.jpg)
Note that clicking either button only closes the message box. The previous box that named ".Net 6.0" opened the proper webpage when clicked "yes".

**Comment by manio143** [comment]
@ChanceVincent can you please share details which version of Windows you're running and the output of `dotnet --info`?

**Comment by ChanceVincent** [comment]
Hi manio143, thank you for replying.

Windows version: (windows 10) 19044.1348

dotnet --info says the following:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by manio143** [comment]
I can see from the output you provided that you have installed .NET 6 runtime, but not .NET 6 SDK. I'm not 100% sure it will solve the problem you're seeing, but it's definitely a prerequisite to build a Stride game.

**Comment by ChanceVincent** [comment]
That's what I needed, the stride game studio works now. Thank you for your help!
