### ISSUE TITLE
Can't create new game for Android platform

### ISSUE THREAD

**Issue by Feralnex** [stride3d/stride#1562]
**Release Type**: Official Release/GitHub (please choose appropriate option)
Official Release

**Version**: Version number and/or git branch
4.1.0.1734

**Platform(s)**: Does the problem occur on Windows, Android...?
Windows

**Describe the bug**
Tried to create New game (from template) and i've got some errors indicating to use dotnet workload restore command, which i did by opening project via Visual Studio and executing command. Android SDK's were installed but the problem persists and error inidicating to use dotnet workload restore command still occurs (used google translate to translate some of the lines).

[StrideLog.txt](https://github.com/stride3d/stride/files/10041851/StrideLog.txt)

When trying to build Android project via Visual Studio there was an error. 

[VisualStudioLog.txt](https://github.com/stride3d/stride/files/10041861/VisualStudioLog.txt)

It was pointing at Resources/values/strings.xml inside project:

```xml
<resources>
  <string name="app_name"><#= Properties.PackageGameDisplayName #></string>
</resources>
```

So i just changed value to MyGame2 (name of the project) and new errors occurred.

[VisualStudioLog2.txt](https://github.com/stride3d/stride/files/10041909/VisualStudioLog2.txt)

Changing android:text="@string/app_text" is easy, but to fix other errors is a hard one and i still don't know what's wrong. Project opens inside Stride but it's empty (blank screen when running on Windows).

**To Reproduce**
1. Clean installation of Visual Studio 2022 Version 17.4.1 + Xamarin as Single component
2. Clean installation of Stride Version 4.1.0.1734 + Visual Extension
3. Try to create New game (from template) for Android platform

**Expected behavior**
Create New game (from template) in Stride for Android platform.

**Comment by Feralnex** [comment]
After changing android:text="@string/app_text" to android:text="@string/app_name" (temporarily) in Resources/layout/activity_main.xml and changing all variables from const to static in Resource.designer.cs project builds in Visual Studio but still fails to properly run inside Stride (still the same errors as in StrideLog.txt)

**Comment by ykafia** [comment]
There's a PR for that, still unfinished. Needs some help for the xamarin issue
