### ISSUE TITLE
Provide a 2D screen

### ISSUE THREAD

**Issue by teamjistory** [stride3d/stride#1564]
HI,
I want to develop a 2D game. So in the engine(game studio),
It would be nice to provide a 2D screen.

Or, is there a way to set it to a 2D screen?

**Comment by NicusorN5** [comment]
There are 2D project samples. For example, see the SpriteStudio project example or the example game called JumpyJet.

![image](https://user-images.githubusercontent.com/20599225/202874296-4dc5dc58-a8d4-416a-9202-fdce13d30b34.png)

**Comment by teamjistory** [comment]
> There are 2D project samples. For example, see the SpriteStudio project example or the example game called JumpyJet.
> 
> ![image](https://user-images.githubusercontent.com/20599225/202874296-4dc5dc58-a8d4-416a-9202-fdce13d30b34.png)

I want to know how to use tilemap driven 2D screen.

**Comment by manio143** [comment]
Stride doesn't have many specific tools for making 2D games. It supports orthogonal camera which can be used for 2D views (both in editor and in game). There's a SpriteSheet editor that can allow you to implement the tile map yourself.
The engine is supported by the community which means that features are implemented by volunteers who needed that for their own project and shared a generic enough solution for others to use.

**Comment by Fydar** [comment]
I recommend that we **close** this issue.

"Locking" a scene to "2D" would limit developers ability to utilise the third dimension for sorting and visual effects.

If we need better support for 2D games, I recommend taking inspiration from Unity and supporting a "2D" toggle on the scene view to view the scene in 2D.

![image](https://github.com/stride3d/stride/assets/19309165/12668d4e-0bd5-455f-9087-c8217724a397)

**Comment by Eideren** [comment]
We technically already have this, select `Orthographic` in the camera menu and one of the orientation below:
![image](https://github.com/stride3d/stride/assets/5742236/cbbaa2f1-545a-4162-848a-bfd1f21d72ee)
