### ISSUE TITLE
[Question] Where is the silent install for Stride3D?

### ISSUE THREAD

**Issue by Zliced13** [stride3d/stride#1572]
# Question and/or Comment
I just want to know how to silently install Stride3D silently using the installer **StrideSetup.exe** from your website. Hopefully, this question should not be too hard to answer.

**Comment by ykafia** [comment]
The installer installs the editor to your computer, there's no silent installer to my knowledge. But you could still develop games without installing the editor, stride is broken down into nuget packages, and games are just c# projects

**Comment by Zliced13** [comment]
I am talking silent installer switches like, `-s`, `/S`. Are there silent switches for **StrideSetup.exe**?
