### ISSUE TITLE
Animation Import with .fbx file leads to permanent asset loading

### ISSUE THREAD

**Issue by Pain9971** [stride3d/stride#1584]
**Release Type**: Official Release

**Version**: Version number 4.1.0.1734

**Platform(s)**: Windows

**Describe the bug**
Created an animation in Cascadeur and imported the created .fbx file to blender. Exported the File to an .fbx and tried to import it in Stride. 
If I try to import the FBX as an animation it permantently loads the asset... see image

**To Reproduce**
1. Import attached FBX File as Animation

**Expected behavior**
Import Animation
**Screenshots**

**Additional context**
 Bone scale is pretty high because ofscale difference from blender to cascadeur.

FBX File Download Link (30 days)
https://filetransfer.dataphone.at/message/2zRRMTara0BYxY90dZF9HG
![Screenshot 2023-01-12 190501](https://user-images.githubusercontent.com/91824284/212144648-d7738382-35fb-49dc-a966-6988ac52e808.png)

**Comment by NicusorN5** [comment]
Same as https://github.com/stride3d/stride/issues/1567 except waiting for few hours results in the error in the screenshot

**Comment by NicusorN5** [comment]
Hi, the link is dead, can you send a new one so I can test your model with the PR I made a while ago? Thanks.

**Comment by anan1213095357** [comment]
> 嗨，链接失效了……你能发一个新的吗，这样我就可以用我刚才做的 PR 测试你的模型了？谢谢。

Hello sir, has this issue been fixed. I am facing the same problem now

**Comment by NicusorN5** [comment]
Hi, @Pain9971 @anan1213095357, are you both still available so I can receive a copy of the 3D models that cause this issue?

I think this was initially fixed in #1653, but I want to be sure.

Assuming you used Cascadeur to create the animation, can I get started with the Basic plan?

**Comment by Eideren** [comment]
Given the lack of files and the changes in the importer from #2163 I will be closing this one
