### ISSUE TITLE
[Rendering] Look into MSAA support for flipmodel rendering

### ISSUE THREAD

**Issue by Eideren** [stride3d/stride#1595]
**Release Type**: Latest as of writing

**Version**: https://github.com/stride3d/stride/commit/441fb473dc30caa44e8fa25acccad5cd39e95ba4

**Platform(s)**: Windows

**Describe the bug**
See conversation and link in PR #1594

**Comment by tebjan** [comment]
I was under the impression that the final render target displayed on the screen via the swap chain has no MSAA. Stride resolves the MSAA even before the post fx chain. So I thought it wasn't an issue:

https://github.com/stride3d/stride/blob/57936e3a9576f52c3e6f5122771f60f374258ca1/sources/engine/Stride.Engine/Rendering/Compositing/ForwardRenderer.cs#L570

**Comment by Eideren** [comment]
I should have mentioned it but this issue was made specifically to investigate whether that was the case, thanks for confirming.
