### ISSUE TITLE
Change binary serialization due to microsoft security concerns

### ISSUE THREAD

**Issue by Doprez** [stride3d/stride#1596]
**Release Type**: GitHub

**Version**:  https://github.com/stride3d/stride/pull/1593
based on a PR updating Stride to .NET 7 

**Platform(s)**: 
Windows 10

**Describe the bug**
https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0011
SYSLIB0011: BinaryFormatter serialization is obsolete

With the new release of .NET 5 Microsoft has found a vulnerability with the BinaryFormatter Class and is telling people to switch to using JsonSerializer or XmlSerializer where applicable.

**To Reproduce**
When updating stride projects to .NET 7 the compiler throws an error due to the security concern in 
sources/core/Stride.Core.Tests/TestSerialization.cs

**Additional context**
Currently I have suppressed the warning in the dotnet 7 PR as shown in the linked commit 
https://github.com/stride3d/stride/pull/1593/commits/54268eaefb82a5d54a06daeab51d2efaa050dc1b
with the added TODO comment.

**Comment by manio143** [comment]
I believe it will be a correct behavior to keep this suppression in place. This is limited in scope to a Unit test which verifies the Stride serialization of .NET primitives preserves the behavior of `BinaryFormatter`. There's no security implications for this specific use case.
