### ISSUE TITLE
Native Editor & VS2020 cannot recognize namespaces & modules

### ISSUE THREAD

**Issue by DraftedDev** [stride3d/stride#1608]
**Release Type**: Official Release

**Version**: 4.1

**Platform(s)**: Windows, but probably also other platforms

**Describe the bug**
When opening the native Stride Code Editor or VS2022, IntelliSense cannot recognize anything and throws a bunch of intelliSense Errors, however the game compiles without an Error.

**To Reproduce**
1. Fresh Stride Install
2. Open Project
3. Open Native Editor or VS2022

**Expected behavior**
The Editor/VS2022 recognized the assemblies and highlights code correctly.

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)

**Additional context**
This Issue is related to many similar Issues like #786, however every 2nd comment on the Issue is "dupe of xyz", which links to another issue where people are pointing to the issue before, since dupe and this Issue cant be solved, if 99% of the comments are "Dupe of xyz".

**Comment by DraftedDev** [comment]
**NOTE** Please do not just comment "Dupe of XYZ", since the issue you are pointing to is probably a dupe of another issue which is a dupe of the issue before and so begins an endless loop of clicking links.
Thanks.

**Comment by Doprez** [comment]
I know there is a known issue with Stride editor but I havent had any issues using vs2020, vscode or rider myself. 

Have you tried cleaning and rebuilding from the vs2020 ide directly? maybe its having a weird time with the nuget packages.

**Comment by DraftedDev** [comment]
I tried rebuilding and cleaning, also reinstalled vs tools and vs plugin

**Comment by Doprez** [comment]
That is very strange. In a new VS 2022 project can you install the same nuget packages and see if you can access the code from that project? The benefit of stride is that it should just be a typical dotnet project so this could narrow the issue a bit.

You may be able to follow the code only test just to make sure it isnt the vs2022 config being funky.
https://github.com/stride3d/stride/discussions/1253

**Comment by manio143** [comment]
I'm going to treat #1453 as the main issue. Please close this once you feel the VS related issue is solved.

**Comment by DraftedDev** [comment]
Solved!
Thanks for your reply, didn't helped that much, but still thanks for your time :D

**By the way, if anyone passes by... HERE IS HOW I SOLVED IT**
It seems Stride or .NET or whatever needs a C++ Redistribution, but not just any.
It needs the 2013 Edition, which is an important info.

So download the vcredist executable from [https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2013-vc-120](the official site).
Make sure to download the 2013 Version.
Now install it and restart Stride.
There we go!

If it still does not work, make sure the NuGet packages are installed by going to `Project -> Manage Nuget-Packages` in VS2022.
Make sure the packages are really installed by clicking on them and pressing "Install".

If it still does not work, try to reinstall VS2022 and go to the VS Installer and click "repair".

If it still does not work, well... reopen this issue... I guess...
