### ISSUE TITLE
Can't run or load projects

### ISSUE THREAD

**Issue by psych0fred** [stride3d/stride#1612]
**Release Type**: Official Release/GitHub (please choose appropriate option)
![image](https://user-images.githubusercontent.com/43375830/219489091-257e7665-8d92-4a98-84d3-0050abd5d849.png)

**Version**: Version number and/or git branch

**Platform(s)**: Does the problem occur on Windows, Android...?
Windows

**Describe the bug**
When trying to load the C# beginner tutorial it fails with the error in the image. Interface offers no way of changing the SDK/.net version to prevent this problem.

**To Reproduce**
1. Install and run stride.
2. Load C# Beginner tutorial
3. get error

**Expected behavior**
Expect tutorial to load without error

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)
![image](https://user-images.githubusercontent.com/43375830/219489409-f064ac7c-3683-43db-8e99-52a57210c8bf.png)

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)

**Additional context**
VS 2022 is installed with default settings and the stride extension also installed itself.

**Comment by Doprez** [comment]
you may need to manually download the dotnet 6 sdk from microsofts website. Unfortuantely the stride installer does not do this.

**Comment by psych0fred** [comment]
Updated the SDK and now I get this:
![image](https://user-images.githubusercontent.com/43375830/225187999-dd9a5603-19d7-4594-851d-07f8fe1bba96.png)

**Comment by Doprez** [comment]
Oh yes its bug that should be fixed in the master branch but hasnt been puched to the release yet.

See my comment on this other post.
https://github.com/stride3d/stride/issues/1617

All you should need to do is open the project directly in VS 2022 or VS Code and switch the 2 parameters in the specified classes.

**Comment by Aerotactics** [comment]
> All you should need to do is open the project directly in VS 2022 or VS Code and switch the 2 parameters in the specified classes.

Most new users are not going to do this. They'll run it once, see that it doesn't build, then uninstall and try another engine. This should be a top priority.

**Comment by Eideren** [comment]
This issue occurs when you do have an SDK installed, but an incompatible one. If you don't have any the launcher will present a window telling the user to download the right SDK.
I'm currently investigating this to make sure we account for this particular case.

**Comment by Eideren** [comment]
The message has been improved while we have #1883 for the requirements
