### ISSUE TITLE
Could not find a compatible version of MSBuild

### ISSUE THREAD

**Issue by HappyGromper** [stride3d/stride#1615]
Release Type: Official Release
Stride Version: 4.1.0.1805
Platform(s): Windows 11

To Reproduce

- Fresh machine install.
- Installed and used successfully for work VS2022
- .NET desktop development
- Universal Windows Platform development
- ASP.NET and web development
- Azure development
- .NET Core cross-platform development
- Installed Stride
- Launched Stride Launcher
- Installed the Visual Studios 2022 extension from the button
- Pressed the Install and launch button

Describe the bug
I tried to run stride and got the error:
![image](https://user-images.githubusercontent.com/22717512/220467989-94ae27b7-d81e-4373-aaf7-8031e2009e43.png)

however I've had my installation of VS2022 for a while installed with msbuild already installed:
![image](https://user-images.githubusercontent.com/22717512/220468121-d081f798-90e0-4963-9576-140a1249db95.png)

I've already uninstalled and reinstalled VS2022 and stride. I found some similar copies of the same issue from 2019 and when I attempted to do what those said like [#420](https://github.com/stride3d/stride/issues/420) but to no avail.

Expected behavior
Launching of stride

Additional context
Both stride and VS2022 are in the same drive

**Comment by trna12** [comment]
Make sure that you have .NET 6 SDK installed. I just had the same issue because VS2022 installs only .NET 7 SDK. 

The reason why it reports that it can't find msbuild is this https://github.com/microsoft/MSBuildLocator/issues/195

**Comment by HappyGromper** [comment]
Update:
Installed Stride 4.0 and it installed 5.0 core again. As I already has it installed but it wanted me to install it again but this allowed me to run stride 4.1 but it won't let me create a project as I get this error: 

[C:\Program Files\dotnet\sdk\5.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(141,5)]: Error: The current .NET SDK does not support targeting .NET Core 6.0.  Either target .NET Core 5.0 or lower, or use a version of the .NET SDK that supports .NET Core 6.0.

**Comment by HappyGromper** [comment]
> Make sure that you have .NET 6 SDK installed. I just had the same issue because VS2022 installs only .NET 7 SDK.
> 
> The reason why it reports that it can't find msbuild is this [microsoft/MSBuildLocator#195](https://github.com/microsoft/MSBuildLocator/issues/195)

I have versions 3-7 installed for work, but I'll try the build locator to see what happens.

**Comment by trna12** [comment]
it could be helpful if you would try to run `dotnet --list-sdks ` if it can really see .net 6 sdk.

**Comment by HappyGromper** [comment]
![image](https://user-images.githubusercontent.com/22717512/220472130-535353c8-3472-4055-96aa-9c110f18069e.png)

all but 3.0

**Comment by HappyGromper** [comment]
It fixed itself? I'm able to make projects and build and run them in 4.1...
