### ISSUE TITLE
Does  Stride run on Oculus Quest and PicoVR ?

### ISSUE THREAD

**Issue by vpenades** [stride3d/stride#1620]
# Question and/or Comment

I've read that Stride does support OculusVR, but one can understand it just means Oculus on Desktop. It doesn't say anything about Oculus Quest / Meta Quest and other stand alone headsets.

So, does Stride support MetaQuest and other stand alone headsets?

**Comment by nukadelic** [comment]
+1

**Comment by tebjan** [comment]
They are basically Android devices. So yes, check the build for the Android thread in the discussions, that should work. But I do not know if extra "Oculus" work needs to be done.

**Comment by vpenades** [comment]
> They are basically Android devices. So yes, check the build for the Android thread in the discussions, that should work. But I do not know if extra "Oculus" work needs to be done.

Quest headsets require rendering to be handled by OpenXR API, which is what handled de eye rendering abstraction. If stride supports OpenXR on android it will probably work

**Comment by nukadelic** [comment]
Have anyone got it working ? I am not familiar with the engine at all , but knowing its platform target build capabilities would help me out many people to decided if its worth publishing with it or not.

**Comment by MetaHertzLabs** [comment]
@nukadelic @vpenades we’re working on it, if we can get it working this seems to be the most capable engine for XR so far in terms of other features. It has OpenXR support with DirectX11 but the code for Vulkan was deleted however we can see the old code. Right now we’re trying to get it running on Android and then hopefully with this Vulkan code added back it’ll work. Help us in the Discord channel and go to #xr . Thanks!

**Comment by Eideren** [comment]
If you have any further questions, feel free to open one in the discussions tab instead or in #1848 for XR
