### ISSUE TITLE
Having a later version of dotnet installed alongside the supported one makes the android build fail

### ISSUE THREAD

**Issue by gabrielesilinic** [stride3d/stride#1627]
**Release Type**: Official Release

**Version**: 4.1.0.1805

**Platform(s)**: Windows (editor)

**Describe the bug**
Due to this issue that comes with interacting with the dotnet cli the android SDK just does not get build despite i did my best to make sure it was installed on the right sdk as well, with this bug projects that wish to run on android fail to build, by introducing into your template builder the possibility to run with the argument --sdk-version 6.xx.xx... (possibly autodetected) you could probably solve the issue

**To Reproduce**
1. install the .net 7 sdk
2. install the dotnet 6 sdk (dotnet 7 should be the "dominant/main" version used by dotnet cli, if it's not fiddle around with the settings)
3. open the launcher
4. install stride if not present
5. try to create "Sample Game: Space Escape" and check the android platform
6. initial project creation/build fails

**Expected behavior**
it should build/create the project properly

**Log and callstacks**
Microsoft.NET.Sdk.ImportWorkloads.targets(38,5)]: Error: To build this project, the following workloads must be installed: android To install these workloads, run the following command: dotnet workload restore

(spoiler, dotnet workload restore even when in the project's directory did not work, it did not show me the 3D view, i probably broke the project)

(this is the relevant part, now i solved the issue and i really don't like going out of my way to break the thing again, it's frustrating)

**Additional context**
how i solved it (it shoudn't be this way though)
1. i uninstalled the dotnet 7.0 component from visual studio
2. i installed the .net 6, enabled both from visual studio as runtime and downloaded the sdk from here https://dotnet.microsoft.com/en-us/download/visual-studio-sdks
3. installed the android workload again, just in case
4. created a new project and selected android

note: it may be dotnet cli fault as well, despite i did my best to make sure dotnet cli installed the android workload on both dotnet 7 and dotnet 6 it may be that it's either not supported meaning the --sdk-version option did not do what i expected it to do (switch dotnet version i mean to give commands to)

**Comment by diybl** [comment]
same error

**Comment by Starkium** [comment]
after reading the above this also looks like what I'm dealing with.
