### ISSUE TITLE
Drag & Drop to the Resource folder (with prompt)

### ISSUE THREAD

**Issue by Obsdark** [stride3d/stride#1633]
**Is your feature request related to a problem? Please describe.**
Is an improvement to the usability of the system, you can say it helps to improve velocity of development and fix issues with migrations and order.

**Describe the solution you'd like**
When you drag & drop or in some other manner add a file (i.e. png, 3dmodel, some audio file, etc) to the project through the editor, make the editor show a prompt than suggest to copy such file to the Resource folder of the project, this folder came with the project in VS and his purpose is to use to save this kind of things.

If accepted, the file is copied to the Resource folder of the project and the copy inside the folder is referenced by the asset, instead of simply reference the file on his original position. The prompt could also have a checkbox so to "remind my desition", both this values (the fact than make the copy to the Resource folder first and the checkbox value) are both values in the config file.

**Additional context**
This will help to improve the work of teams making the project more concise and self-contained, which in time improve the chance of share it between different parts of the team, this offer some improvement in quality of life than, although being a minor addition, would result on an improved experience for the application users besides fixing problems related to asset order with an elegant solution than allow for an optional, but visible prevention of problems caused by disorder of the assets.

**Comment by Eideren** [comment]
Right now on the master branch the editor shows a message box to the user when the asset is outside of the resource folder, here are the lines related to this check:
https://github.com/stride3d/stride/blob/3eac07770518617c8c047821f32428aa863f8c8b/sources/editor/Stride.Core.Assets.Editor/ViewModel/AssetCollectionViewModel.cs#L544-L565
We could ask the user whether they want to move the source file instead, and move the file accordingly.
If anyone wants to tackle this, feel free to do so :)

**Comment by SeleDreams** [comment]
> Right now on the master branch the editor shows a message box to the user when the asset is outside of the resource folder, here are the lines related to this check:
> 
> https://github.com/stride3d/stride/blob/3eac07770518617c8c047821f32428aa863f8c8b/sources/editor/Stride.Core.Assets.Editor/ViewModel/AssetCollectionViewModel.cs#L544-L565
> 
> We could ask the user whether they want to move the source file instead, and move the file accordingly.
> If anyone wants to tackle this, feel free to do so :)


I am personally thinking of implementing an option to automatically copy it in a way where if the user places the file in assets/audio, then the resource would be placed in resources/audio.
however i got told the user should be able to choose where in resources the file gets placed, in such a case the prompt should ask whether we want the default behaviour or if we want to manually choose where to place the resources.
I still feel like having to go through the prompts all the time would be a pain though so i guess there should be an editor setting to toggle them off by selecting the default behaviour

**Comment by tebjan** [comment]
It is not the developers' role to determine how the user organizes their files in their project. Every team has their own conventions. 

A suggestion would be to include a third option called "Copy to Resources" that triggers a folder selection dialog. By default, it would start at the root of the resources folder.
