### ISSUE TITLE
Property Grid Not Being Shown in Editor 

### ISSUE THREAD

**Issue by RamiMorrar** [stride3d/stride#1636]
**Version**: 4.1

**Platform(s)**: Windows
**Describe the bug**
Property Grid is not being show in the Editor. Even with View > Property Grid on, it still won't show up. REALLY high priority. Can't add scripts entities and the like. 
**To Reproduce**
1. Tried ticking and closing the property grid checkbox on an off. Failed.
2. Tried restarting Stride to see if problem went away. Failed
3. Tried Reinstalling Stride to see if problem cleared. Failed
4. Closed any and all other view boxes. Ticked Property Box Only. Still failed. 

**Screenshots**

<img width="960" alt="image" src="https://user-images.githubusercontent.com/54463476/226794448-4ed0b8d2-99b6-400d-a710-f47f9a50c47f.png">

**Comment by Doprez** [comment]
Could it have to do with the float option in the property grid? I tried messing around to break it myself and the closest I got was to select float and it was hiding on a seperate monitor which made it seem like it dissappeared.
![image](https://user-images.githubusercontent.com/73259914/226806098-c2fb014b-626d-4ab1-afe6-40d5ea0b77c9.png)
this image is after I found it.

**Comment by RamiMorrar** [comment]
> Could it have to do with the float option in the property grid? I tried messing around to break it myself and the closest I got was to select float and it was hiding on a seperate monitor which made it seem like it dissappeared. ![image](https://user-images.githubusercontent.com/73259914/226806098-c2fb014b-626d-4ab1-afe6-40d5ea0b77c9.png) this image is after I found it.

I believe I have fixed the issue. And no, that did not happen to me. 

Resetting the Editor Layout Has Helped in Resolving the Issue. Should this come up,  I think this is probably the best quick fix you can do if something like this happens again. 


<img width="744" alt="image" src="https://user-images.githubusercontent.com/54463476/227018761-0eabe899-8945-4cee-bca3-8a429ea23411.png">
