### ISSUE TITLE
Stride.Core.Assets.CompilerApp.targets(132, 5): [MSB3073] 

### ISSUE THREAD

**Issue by diybl** [stride3d/stride#1645]
Stride.Core.Assets.CompilerApp.targets(132, 5): [MSB3073] 命令“"C:\Users\jack\.nuget\packages\stride.core.assets.compilerapp\4.1.0.1457-beta\buildTransitive\..\lib\net5.0-windows7.0\Stride.Core.Assets.CompilerApp.exe"  --disable-auto-compile --project-configuration "Debug" --platform=Windows --project-configuration=Debug --compile-property:StrideGraphicsApi=Direct3D11 

windows 10 build error

**Comment by Doprez** [comment]
"net5.0-windows7.0"
Did you install the dotnet 6 sdk from microsofts webiste?

**Comment by diybl** [comment]
> "net5.0-windows7.0" Did you install the dotnet 6 sdk from microsofts webiste?

now i install dotnet6 it works
