### ISSUE TITLE
Error: To build this project, the following workloads must be installed: android

### ISSUE THREAD

**Issue by diybl** [stride3d/stride#1646]
**Release Type**: Release

**Version**: 4.1.0.1822

**Platform(s)**: windows10

[C:\Program Files\dotnet\sdk\6.0.407\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5)]: Error: To build this project, the following workloads must be installed: android

i run the command :
dotnet workload install android --sdk-version 6.0.407

but the error also show..

my pc has installed both .net 7.0 and .net6.0

**Comment by diybl** [comment]
same error with https://github.com/stride3d/stride/issues/1627
How to solve it? ? Cross-platform is still very important

**Comment by Doprez** [comment]
In the linked issue they provided a work around. 
were you able to remove dotnet 7 or dotnet 5? 
if you did can you try using the console commands below and show the results.

1. dotnet --list-sdks
2. dotnet workload list

I know some people have been working with mobile in the Discord if you want to try and ask there as well.

**Comment by Doprez** [comment]
Another thing that might work if you are willing to build stride yourself there is a branch that uses dotnet 7. This may solve the issue if you dont mind running Stride trhough visual studio 2022.
https://github.com/stride3d/stride/pull/1593

**Comment by diybl** [comment]
> 

are there any plan the stride3d official upgrade stride to .net7

**Comment by Doprez** [comment]
no, In the PR they discussed if they wanted .net 7 and it was decided to only stick with the LTS versions of .net. The next .net SDK update will be when .net 8 is officially released.

**Comment by Doprez** [comment]
> > Another thing that might work if you are willing to build stride yourself there is a branch that uses dotnet 7. This may solve the issue if you dont mind running Stride trhough visual studio 2022. #1593
> 
> i have complie .net7 version
> but when i create new project whith android or iso
> it show the error:
> 
> Error: Package Stride.Engine 4.1.0.1 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Stride.Engine 4.1.0.1 supports: net7.0 (.NETCoreApp,Version=v7.0)

Make sure you run dotnet clean on both stride and your project it may leave some dotnet 6 references behind if it was built before with dotnet 6.

**Comment by diybl** [comment]
> > > Another thing that might work if you are willing to build stride yourself there is a branch that uses dotnet 7. This may solve the issue if you dont mind running Stride trhough visual studio 2022. #1593
> > 
> > 
> > i have complie .net7 version
> > but when i create new project whith android or iso
> > it show the error:
> > Error: Package Stride.Engine 4.1.0.1 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Stride.Engine 4.1.0.1 supports: net7.0 (.NETCoreApp,Version=v7.0)
> 
> Make sure you run dotnet clean on both stride and your project it may leave some dotnet 6 references behind if it was built before with dotnet 6.

I cleaned the build and nuget package, but it still shows that error. .

**Comment by diybl** [comment]
i modify the strideconfig.cs

 // Android
            var androidPlatform = new SolutionPlatform()
            {
                Name = PlatformType.Android.ToString(),
                Type = PlatformType.Android,
                TargetFramework = "net7.0-android",
                IsAvailable = IsVSComponentAvailableAnyVersion(XamarinAndroidComponents)
            };

the error is solved.
