### ISSUE TITLE
Can not create "C# Beginner" project.

### ISSUE THREAD

**Issue by SoNewBee** [stride3d/stride#1650]
Just like the title.
Here is infomation fron "Creating session":
Verbose: Process dependencies for CSharpBeginner3.Game...
Info: Upgrading project [CSharpBeginner3.Game] to use [Stride.Engine] from version [4.1.0.1-beta] to [4.1.0.1822] will be required
Verbose: Restore NuGet packages for CSharpBeginner3.Game...
Verbose: Loading Assets from Package [Stride.Engine.sdpkg]
Verbose: Loading Assets from Package [Stride.Graphics.sdpkg]
Verbose: Loading Assets from Package [Stride.Particles.sdpkg]
Verbose: Loading Assets from Package [Stride.Rendering.sdpkg]
Verbose: Loading Assets from Package [Stride.Video.sdpkg]
[D:\SEP\CSharpBeginner3\CSharpBeginner3.Game\Code\InstantiatingPrefabsDemo.cs(27,48)]: Error: parameter 1: Cannot convert from "Stride.Core.Mathematics.Vector3" to "string"
[D:\SEP\CSharpBeginner3\CSharpBeginner3.Game\Code\InstantiatingPrefabsDemo.cs(27,71)]: Error: paremeter 2: Cannot convert from "string" to "Stride.Core.Mathematics.Vector3"
[D:\SEP\CSharpBeginner3\CSharpBeginner3.Game\Code\LoadingContentDemo.cs(71,41)]: Error: parameter 1: Cannot convert from "Stride.Core.Mathematics.Vector3" to "string"
[D:\SEP\CSharpBeginner3\CSharpBeginner3.Game\Code\LoadingContentDemo.cs(71,57)]: Error: parameter 2:  Cannot convert from "string" to "Stride.Core.Mathematics.Vector3"
Error: Unable to build assembly reference [D:\SEP\CSharpBeginner3\CSharpBeginner3.Game\bin\Debug\net6.0\CSharpBeginner3.Game.dll]
Verbose: Loading Assets from Package [CSharpBeginner3.Game.sdpkg]
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.PropertiesDemo'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.GettingTheEntityDemo'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.DeltaTimeDemo'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.TransformPositionDemo'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.InstantiatingPrefabsDemo'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.MouseInputDemo'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.KeyboardInputDemo'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.RemoveEntitiesDemo'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.CloneEntityDemo'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.VirtualButtonsDemo'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.GettingAComponentDemo'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.AmmoComponent'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.LerpDemo'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.AddingAComponentDemo'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.ChildEntitiesDemo'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.LoadingContentDemo'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'CSharpBeginner3.Code.TutorialUI'; replacing it with an object implementing IUnloadable (...)
Verbose: Compiling game assemblies...
Verbose: Game assemblies compiled...
Verbose: Generating CSharpBeginner3.Windows...
Verbose: Process dependencies for CSharpBeginner3.Windows...
Verbose: Restore NuGet packages for CSharpBeginner3.Windows...
Verbose: Loading Assets from Package [Stride.SpriteStudio.Offline.sdpkg]
Verbose: Loading Assets from Package [CSharpBeginner3.Windows.sdpkg]

Any help please?

**Comment by Doprez** [comment]
[D:\SEP\CSharpBeginner3\CSharpBeginner3.Game\Code\InstantiatingPrefabsDemo.cs(27,48)]: Error: parameter 1: Cannot convert from "Stride.Core.Mathematics.Vector3" to "string"
[D:\SEP\CSharpBeginner3\CSharpBeginner3.Game\Code\InstantiatingPrefabsDemo.cs(27,71)]: Error: paremeter 2: Cannot convert from "string" to "Stride.Core.Mathematics.Vector3"
[D:\SEP\CSharpBeginner3\CSharpBeginner3.Game\Code\LoadingContentDemo.cs(71,41)]: Error: parameter 1: Cannot convert from "Stride.Core.Mathematics.Vector3" to "string"
[D:\SEP\CSharpBeginner3\CSharpBeginner3.Game\Code\LoadingContentDemo.cs(71,57)]: Error: parameter 2: Cannot convert from "string" to "Stride.Core.Mathematics.Vector3"

The project should have still be created what you have to do is change the construtor parameters as discussed in these 2 discussions:
https://github.com/stride3d/stride/issues/1617#issuecomment-1444563945
https://github.com/stride3d/stride/issues/1612

**Comment by SoNewBee** [comment]
> [D:\SEP\CSharpBeginner3\CSharpBeginner3.Game\Code\InstantiatingPrefabsDemo.cs(27,48)]: Error: parameter 1: Cannot convert from "Stride.Core.Mathematics.Vector3" to "string" [D:\SEP\CSharpBeginner3\CSharpBeginner3.Game\Code\InstantiatingPrefabsDemo.cs(27,71)]: Error: paremeter 2: Cannot convert from "string" to "Stride.Core.Mathematics.Vector3" [D:\SEP\CSharpBeginner3\CSharpBeginner3.Game\Code\LoadingContentDemo.cs(71,41)]: Error: parameter 1: Cannot convert from "Stride.Core.Mathematics.Vector3" to "string" [D:\SEP\CSharpBeginner3\CSharpBeginner3.Game\Code\LoadingContentDemo.cs(71,57)]: Error: parameter 2: Cannot convert from "string" to "Stride.Core.Mathematics.Vector3"
> 
> The project should have still be created what you have to do is change the construtor parameters as discussed in these 2 discussions: [#1617 (comment)](https://github.com/stride3d/stride/issues/1617#issuecomment-1444563945) #1612

That is a quite quickly reply.Thanks.
I successfully run the project by the proposal in your answer.
But...I am using version 4.1.0.1822,there need to do some fixing.

The answer in #1617 :
>LoadingContentDemo.cs line 71:
`from`
var entity = new Entity("My new entity with a model component", randomPosition);
to
var entity = new Entity(randomPosition, "My new entity with a model component");

In fact, we should modify LoadingContentDemo.cs line 71:
from
var entity = new Entity("My new entity with a model component", randomPosition);
to
var entity = new Entity(randomPosition, "My new entity with a model component");`

**Comment by Doprez** [comment]
You are correct and it is fixed in the master branch of Stride. I think a version bump on the sample projects is needed for it to go through.
