### ISSUE TITLE
Focus on this Element Box is empty in the Editor, while being the Focus

### ISSUE THREAD

**Issue by IXLLEGACYIXL** [stride3d/stride#1661]
**Release Type**: Official Release/GitHub (please choose appropriate option)
4.1.0
**Version**: Version number and/or git branch
4.1.0.1838
**Platform(s)**: Does the problem occur on Windows, Android...?
In the Editor
**Describe the bug**
Press on a element in the Scene.
Hover over the magnyfing glass.
The Text for "Focus on this Entity" is not shown, even though the functionality is there.

**To Reproduce**
1. Create a Scene
2. select an element
3. hover over the glass

**Expected behavior**
That the Box is not empty and shows the text like it does on other elements
like in the picture

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)
![grafik](https://github.com/stride3d/stride/assets/107197024/47b19178-8f17-4e74-8265-c93c7be60a23)
![grafik](https://github.com/stride3d/stride/assets/107197024/6dc06897-a75e-49e8-ac46-6a6a009ffdf6)

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)

**Additional context**

**Comment by IXLLEGACYIXL** [comment]
same bug on the lock

**Comment by Doprez** [comment]
Just as added info this is a bug with the light theme. I do not get this error when using Expression dark or Dark Steel.

![image](https://github.com/stride3d/stride/assets/73259914/cc7534d7-3b13-45b5-bc5a-7e1ff75bec59)

**Comment by IXLLEGACYIXL** [comment]
indeed i can confirm, on dark steel the box is filled

**Comment by IXLLEGACYIXL** [comment]
fixed with svnmlr theme update
