### ISSUE TITLE
fbx import

### ISSUE THREAD

**Issue by anan1213095357** [stride3d/stride#1667]
**Release Type**: github

**Version**: 4.1

**Platform(s)**: windows

**Describe the bug**
Warning: Multiple FBX animation stacks detected in 'C:/Users/anan/Music/ask.fbx', exporting only the first one to '
Info: Computing hashes of 1 source files...
Verbose: Computed hash of C:/Users/anan/Music/ask.fbx for asset model/New folder/ask. 0 files remaining...

**Comment by NicusorN5** [comment]
This is a known issue. The FBX importer doesn't support multiple animations. 

If you are exporting from blender use https://github.com/JackPilley/BlenderToStrideAnimationSeparator .

**Comment by anan1213095357** [comment]
> 

Well, thank you

**Comment by Eideren** [comment]
Duplicate of #328 as Nicusor said
