### ISSUE TITLE
Move VisualStudio related projects to another solution file

### ISSUE THREAD

**Issue by Jklawreszuk** [stride3d/stride#1671]
**First problem**

As many may be noticed, current build system is based on **.NET Framework**.
As a developer I want to build Stride engine using built-in NET5+ msbuild equivalent. Take a look an example :
```cmd 
dotnet msbuild /t:Build Stride.sln
```
Very simple.

However, this will fail because of following error:
```
error MSB4801: task factory "CodeTaskFactory" is not supported on the .NET Core version of MSBuild - Stride.VisualStudio.Package.csproj
```
And the line causing an error:
```xml
<Import Project="$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" .../>
```
The most obvious option would be to migrate the entire VisualStudio plug-in project to NET Core, but I don't really believe it would be that easy, and I also don't believe we have enough contributors to take care of it.
I would like to mention that I am not 100% sure if only VisualStudio plugin causes an errors, but It would be nice to separate this from NET Core projs.

**Second problem**

What if a developer wants to build the whole engine, but doesn't want to use VisualStudio or just doesn't want to install any plug-in?
I think this should be **optional**, but it's not, because when you execute `dotnet msbuild /t:Stride.sln`, the Stride.sln file contains VisualStudio projects. 
Moreover, because of this, any non-Windows developer can't build either, making the whole process dependent on Windows. 

**Todo (potential solution)**

- [x] - Make Stride Stride.VisualStudio.sln file
- [x] - Figure out if the change affects the engine

**Comment by manio143** [comment]
I believe that wouldn't be enough to drop the dependency on Visual Studio MSBuild - the C++ projects (not sure if just C++/CLI or also win-x64 native) need to be built from VS Build Tools environment.
But it's definitely a good goal to have at making Stride build system modernized.
