### ISSUE TITLE
Path for VS2022 in Readme is wrong

### ISSUE THREAD

**Issue by IXLLEGACYIXL** [stride3d/stride#1674]
**Describe the bug**
VS is not a 32 bit application anymore, its 64 bit so it gets installed in the Program Files directory
In addition to that the Community folder is missing in the path
**To Reproduce**
`ls "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin"`
it will not work as it doesnt exist

**Expected behavior**
`ls "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\"`
this path exists

**Comment by dontpanic92** [comment]
In Readme the Path is for 'Visual Studio Build Tools' instead of Visual Studio. The latest version of Visual Studio Build Tools 2022 is still installed in `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools`:

![image](https://github.com/stride3d/stride/assets/1056013/e8a27bbc-be3d-4da5-b0d9-3e6f95c4db94)

**Comment by IXLLEGACYIXL** [comment]
![grafik](https://github.com/stride3d/stride/assets/107197024/01881c6b-563b-4c37-a62d-088b3b3109d0)

i dont have that, for me its in `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\`
and im on 17.6.4

did you upgrade from 2019 to 2022? or something like that

**Comment by dontpanic92** [comment]
No.. Visual Studio Build Tools and Visual Studio are 2 separate products - Visual Studio Build Tools only contains the toolchains such as Compilers, MSBuild, SDKs, etc. that enables developers to build solutions without the necessity of installing a full-featured IDE. It can be downloaded [here](https://aka.ms/vs/17/release/vs_BuildTools.exe).

I think in README there are 2 approaches mentioned - the first one is using Visual Studio 2022, while the second one is using Visual Studio Build Tools 2022. The path provided in README is for the second approach
