### ISSUE TITLE
Build failure on master branch for multiple graphic APIs/platforms

### ISSUE THREAD

**Issue by dontpanic92** [stride3d/stride#1706]
**Release Type**: Official Release/GitHub (please choose appropriate option)
GitHub

**Version**: Version number and/or git branch
master

**Platform(s)**: Does the problem occur on Windows, Android...?
Windows/Android/Linux/iOS

**Describe the bug**
Build Failure

**To Reproduce**
1. build projects for Vulkan/Direct3D12/OpenGL for Windows
2. Build fails

**Expected behavior**
Build succeeds

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)

**Additional context**

For the failures on Windows, it seems that the reason is some obslete code was removed but the corresponding references were not updated.

**Comment by dontpanic92** [comment]
For the failures on Windows, I can try to take them if nobody is working on it

**Comment by Jklawreszuk** [comment]
I think this was fixed by #1697 🤔

**Comment by dontpanic92** [comment]
Yes that's right, closing
