### ISSUE TITLE
Better documentation within tutorials.

### ISSUE THREAD

**Issue by Doprez** [stride3d/stride#1751]
**Is your feature request related to a problem? Please describe.**
This is an issue with the current docs in the Stride tutorial projects. When a user opens the tutorial project within Stride they may have no clue about the existing videos that go along with it.

**Describe the solution you'd like**
I will create a PR to modify the projects. We should have a simple readme in the project, we should also add a popup on the demo start to open and notify the user that there is support in the videos as well as a discord reference.

This is a simple request that I will work on but I wanted to document it here for visibility.

**Comment by VaclavElias** [comment]
The video links could be added to the code comment as well, so one can see them right away. Aggor would do that if we would have gave him feedback when he was doing that :)

**Comment by Doprez** [comment]
I shall add this as well!
