### ISSUE TITLE
Wrong IDE opens when pressing "open in IDE"

### ISSUE THREAD

**Issue by Doprez** [stride3d/stride#1752]
**Release Type**: Official Release 

**Version**: 4.1.0.1838

**Platform(s)**: Windows

**Describe the bug**
Currently no matter the text editor in the project settings a different IDE is opened when pressing "open in IDE" in Stride.
![image](https://github.com/stride3d/stride/assets/73259914/3b11e07f-10f2-4bc8-9a1f-1b3836b72bc2)

**To Reproduce**
1. configure the project settings to open VS code
2. press open in IDE

**Expected behavior**
It should open the configured IDE.

**Comment by Jklawreszuk** [comment]
Sorry @Doprez but you missunderstood a feature. This allows you to open text with editor of your choice. For example you provide path to your vscodium ("C:\Program Files\VSCodium\bin\codium" in my case) and when you right click on file, there is an option "open with text editor" it works :). What it not implemented is picking IDE of your choice. Currently Opening with IDE is hardcoded to all versions of visual studio so you cant open with Rider or VS code for example

**Comment by Doprez** [comment]
Gotcha, So the configurable IDE's are stuck with VS2022?

**Comment by Doprez** [comment]
Perfect, this makes more sense I will close this as completed but maybe open a new one for a refactor that is less important.
Thank you very much for explaining.

**Comment by Eideren** [comment]
> What it not implemented is picking IDE of your choice. Currently Opening with IDE is hardcoded to all versions of visual studio so you cant open with Rider or VS code for example

@Jklawreszuk Maybe you're aware, but just in case ... 
![image](https://github.com/stride3d/stride/assets/5742236/6529e63f-d2f8-4d31-b25f-310f222a6107)
This option will open the IDE you associated to your project files in windows, so Rider and VS Code if you set them up

**Comment by Doprez** [comment]
This is important to know! thank you again.

**Comment by Jklawreszuk** [comment]
@Eideren Oh, you're right I forgot that option exists, thanks 😀. But, still, it's not intuitive at all and for vs code it opens sln only not entire content like vs/rider does
