### ISSUE TITLE
DX11: Trying to use an external shared texture with NT Handle but no Keyed mutex throws an exception

### ISSUE THREAD

**Issue by arturoc** [stride3d/stride#1758]
**Release Type**: Github 

**Version**: master / 636342b207786f5236c1e54db59fdaf3b2e60972

**Platform(s)**:  Windows DX11

**Describe the bug**
When trying to use an external texture shared with an NT handle but no keyed mutex an exception is thrown cause the code only accepts textures that have both shared NT handle and keyed mutex.

**To Reproduce**
1. Create a texture using an NT shared handle but no keyed mutex
2. Try to use it from stride using `SharpDXInterop.CreateTextureFromNative`

**Expected behavior**
The shared texture should be created without problem.

**Log and callstacks**
The application throws an exception at the end of `InitializeFromImpl` in `Texture.Direct3D.cs` while checking the `textureDescription.Options` as the combination is considered valid and the switch case ends up in the default branch throwing an exception: https://github.com/stride3d/stride/blob/636342b207786f5236c1e54db59fdaf3b2e60972/sources/engine/Stride.Graphics/Direct3D/Texture.Direct3D.cs#L178-L198

**Comment by tebjan** [comment]
Closed by #1759
