### ISSUE TITLE
Is there any change that new stride base on .net8, and editor imitate Unity3d？

### ISSUE THREAD

**Issue by FlameskyDexive** [stride3d/stride#1763]
# Question and/or Comment
Unity3d's new polisy is disgusted, but many unity developer need a similar game engine, and if stride can make a change and plan to do this, it's so cool.

**Comment by IXLLEGACYIXL** [comment]
https://github.com/stride3d/stride/pull/1616
This PR is for Upgrading stride to .NET 8 but as long as .NET 8 is in preview it won't be merged.

Stride doesn't "imitate" or "clone" unity
The rework of the Editor is planned to go to Avalonia, many discussions are around here about that topic

**Comment by tebjan** [comment]
Closing this, as it is just a question that should go into the Discussions section.
