### ISSUE TITLE
Unable to import .obj model

### ISSUE THREAD

**Issue by creeperlv** [stride3d/stride#1765]
**Release Type**: Official Release

**Version**: 4.1.0.1897

**Platform(s)**: Windows 11 x86_64

**Describe the bug**
Cannot import .obj 3d model

**To Reproduce**
1. Download this file https://github.com/creeperlv/Site-13-V2/blob/main/Site-13-V2/Assets/SCPAssets/Models/Constructions/Site-13/Zone0/Hallways/Hallway-00.obj

2. Use `Add asset`

3. Select `3D Model`

4. Select downloaded file.

5. Import the model.

6. Get the error.

**Expected behavior**

The model should be imported

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)
![Stride-Model-Import-Failure](https://github.com/stride3d/stride/assets/7870727/e4c1f628-0309-4a7e-b835-af4ee0ad779f)

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)
[Stride-Model-Import-Failure.txt](https://github.com/stride3d/stride/files/12639706/Stride-Model-Import-Failure.txt)

**Additional context**

**Comment by Doprez** [comment]
![image](https://github.com/stride3d/stride/assets/73259914/8c36093e-173f-4da1-bea4-7bdb0a5b42ef)
Can you try installing version 4.1.1822 and see if this issue persists?

**Comment by Doprez** [comment]
I am currently using Stride 4.1.0.1822 and can confirm this works there I think the issue lies with the new Silk ASSIMP importer.

**Comment by creeperlv** [comment]
> I am currently using Stride 4.1.0.1822 and can confirm this works there I think the issue lies with the new Silk ASSIMP importer.

I think so. I currently have 1838 installed and can confirm that the model works fine with 1838.
![Srtide-Model-Import-Success-On-1838](https://github.com/stride3d/stride/assets/7870727/fef9b127-e067-4110-a99b-a690fa20ce63)

**Comment by creeperlv** [comment]
> ![image](https://user-images.githubusercontent.com/73259914/268424545-8c36093e-173f-4da1-bea4-7bdb0a5b42ef.png) Can you try installing version 4.1.1822 and see if this issue persists?

Can confirm the model I use have no issue importing in 4.1.0.1822

**Comment by NicusorN5** [comment]
I also confirm the model loading works fine in the latest Stride version.

**Comment by Doprez** [comment]
seems to be fixed in 4.1.0.1898 now.
