### ISSUE TITLE
Flawed implementation of the gamepad/gamecontroller API

### ISSUE THREAD

**Issue by SeleDreams** [stride3d/stride#1775]
**Release Type**: Official Release
**Version**: 4.1.0.1898
**Platform(s)**: Windows

**Describe the bug**
I don't know if it would be considered a bug, as much as I would consider it a design flaw from the gamepad API.
Right now, the gamepad API seems to arbitrarily split some types of gamepads as GameControllers and some others as GamePads.
To begin with this feels flawed for developers because the two of those are functionally *identical*
both rely on getting their A button, their bumper buttons etc, so both should fit in a single class. But also, because of it, the same code can break depending on the controller due to whether or not the engine considers it a GamePad or GameController

like on an xbox one and series x controller, this code will work and break as intended when the A button is pressed
```
 if (Input.HasGameController)
 {
     IGameControllerDevice gamecontroller = Input.GameControllers[0];
     Debug.Assert(gamecontroller != null);
     Debug.Assert(!gamecontroller.IsButtonDown((int)GameControllerButton.ControllerButtonA));
 }
```

However this code won't even though it is functionally *the exact same thing*
```
if (Input.HasGamePad)
{
    IGamePadDevice gamepad = Input.GamePads[0];
    Debug.Assert(gamepad != null);
    Debug.Assert(!gamepad.IsButtonDown(GamePadButton.A));
}
```

Another flaw it creates is when we use the VirtualButton feature in order to abstract button presses as actions. The VirtualButton API only allows to specify gamepad input, so if we setup VirtualButtonBindings, the engine only will allow gamepad buttons and not game controller buttons, because it's obvious the engine was normally designed for all controllers to be recognised as gamepads.
because of it, Xbox One controllers and Xbox Series X controller just cannot even be used by the virtual button system because of this arbitrary separation of gamepads and game controllers.

**To Reproduce**
1. Setup a VirtualButtonConfigSet
2. Add gamepad bindings
3. These bindings won't work on xbox series x and xbox one controllers

**Expected behavior**
While I could say specifically for VirtualButtons to add GameController buttons, I think the issue is at a deeper level on the design itself of the current gamepad/gamecontroller API which seems flawed

**Comment by Eideren** [comment]
So, the issue is that some devices we expect to be registered as `Gamepads` are registered as `GameControllers` instead.
I don't have those two pads, so I can't really debug this, though it shouldn't be that hard.

> To begin with this feels flawed for developers because the two of those are functionally identical

Well, no, they have wildly different feature sets, gamepads are registered as xinput devices, gamecontrollers are registered as dinput devices.
There's a lot of resources regarding the difference in feature set, but as an example, xinput support vibrations, while dinput does not have a standardized amount of buttons and axis.

I don't have anything against building an abstraction layer that covers both apis, but we have to keep those two interfaces as well to provide users with those additional features if they end up needing them.

**Comment by SeleDreams** [comment]
Wouldn't it be easier to simply expose both in a single class with flags
like "supportsVibration" etc

**Comment by Eideren** [comment]
Sure, that would be part of how we build the abstraction layer

**Comment by SeleDreams** [comment]
I feel like instead of gamepad and gamecontroller it should be a unified
Gamepad class and the backends would be directly called DirectInputGamepad
and XinputGamepad (both relying on a common interface I guess
