### ISSUE TITLE
Please migrate to new C# ecosystem and switch to vscode

### ISSUE THREAD

**Issue by Thaina** [stride3d/stride#1776]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**

I have 2 requests that related to each other
1 - Please use vscode as main editor of the project. Both this codebase itself. And default code editor of the engine
2 - Please upgrade this codebase and project create from the engine to use C# in compatible with `C# dev kit`. Which I think it just the modern project structure of C#

As unity current circumstance all of us would already be awared of. I am trying to transition myself to stride, in the spirit that stride are more align with C# ecosystem than godot, completely made whole engine in C#. And the environment seem to focused more on 3D project

However, one crucial element is visual studio IDE is heavy and proprietary product. Unlike vscode which is very light and opensourced,  easier extensible and could be tightly integrate with game engine. Not to mention it completely free and cross platform, very popular also very well maintained

So I try to compile this codebase in vscode, which are very frustrating that it not support C# dev kit and so there are many point I have stumble upon, even though I have some success

Additionally I would like to suggest that the code editor in stride should be fully replaced with vscode. Double click the code file should just open vscode project folder

- What are the usecases?
It should be obvious that using stride are completely made with C#, so stride should always follow C# ecosystem closely
vscode is very handy to be used especially for coding

- What kind of options/settings are expected/wanted?
- Is the feature affecting behaviour in the editor? 
  - if so: how should this look in the editor?

IDE should be selectable. VSCode should be default option for new project. But Visual Studio might be default for existing project

- what kind of documentation is needed or needs to be updated?
How to migrate to vscode and document about how to switch (and extend support) to other IDE

**Comment by Eideren** [comment]
> Please use vscode as main editor of the project. Both this codebase itself. And default code editor of the engine

This is very subjective, I don't think it makes sense to have ***any*** IDE as the ***solely*** supported one for any dotnet project. 
As to supporting vscode for building the editor, right now we have a couple of dependencies on MSBuild itself, not Visual Studio per se - the community is slowly getting rid of them, but in the mean time you can compile from the command line, you have to have the requirements installed of course. Have a look at [the readme](https://github.com/stride3d/stride#build-stride-without-visual-studio)

The game solution can be compiled from vscode though, just open your solution and start debugging.
As for opening vscode from the editor, make sure you set vscode as the default ide for c# solutions in windows, and in Stride, set the default IDE to system default and it should open vscode when you press on the IDE button.

**Comment by Thaina** [comment]
@Eideren I think we all install Visual Studio Installer and had it install many things to work with since unity. But the need to opening the project in Visual Studio itself or else the intellisense and project discovery and compilation, nuget restoration, and etc are not working is a roadblock issue for me to start contributing to the project 

> in Stride, set the default IDE to system

I wish this option should have vscode and support vscode style project launching. Such as open the project folder instead of the file, also specified both filename and line:column for pinpointing error or specific member of C#

**Comment by IXLLEGACYIXL** [comment]
> I wish this option should have vscode and support vscode style project launching. Such as open the project folder instead of the file, also specified both filename and line:column for pinpointing error or specific member of C#

Visual Studio has a Project extension so you can open sln files like in VS whihc also includes the sln structure to be resolved

**Comment by Thaina** [comment]
> > I wish this option should have vscode and support vscode style project launching. Such as open the project folder instead of the file, also specified both filename and line:column for pinpointing error or specific member of C#
> 
> Visual Studio has a Project extension so you can open sln files like in VS whihc also includes the sln structure to be resolved

The point is, is it work like that if I just double click on any script file in engine windows?

When their are error reported in stride, if I double click on it, will it open vscode with that behaviour?

**Comment by IXLLEGACYIXL** [comment]
double clicking on files and opening the IDE is bugged currently and only works with VS

**Comment by Thaina** [comment]
That's the point I have suggest on this issue, please make it work with VSCode

**Comment by Doprez** [comment]
Just adding for documentation.

The issue with double clicking currently is that it uses Strides built in IDE and not the default IDE in the settings.

as for adding VS Code there was [this PR](https://github.com/stride3d/stride/pull/818) for Rider support but it did not get finished sadly. If anyone wants to pick up the suggestion from Thaina this may be a good starting point for at least the buton below to open a project in Code.
![image](https://github.com/stride3d/stride/assets/73259914/bdefd995-23d9-4c80-abaf-0cd0fac09385)

**Comment by errorstrike** [comment]
I am hobbyist in gamedev, but I am agree about VScode. Microsoft Visual studio is free only for individual developers and little organazaitions. But for the rising of popularity of Stride, it's needed to be not depended of paid IDE. Rider is better, but not everyone can buy it. VScode is most popular free IDE. The feature of Stride that Stride is free, so IDE should be free without limitations. Godot and Bevy use VScode. I think, developers love it. But I like achitecture and disign of Stride, so, I have plan to try Stride in any way and, may be buy, Rider. However, JetBrains stoped selling in Russia and Belarus, so developer could buy Rider only via mediators (unofficial undeground resellers).

**Comment by Kryptos-FR** [comment]
@errorstrike you can already use VS Code. Just open the folder where the project is located.

**Comment by Eideren** [comment]
Closing this one off as too scattershot, we already have an issue open about adopting the recommended c# style. VSCode can already open and build games, while we have another existing issue to ensure building the engine works across dotnet IDEs.
Feel free to open an issue to add an `Open in VSCode` button in the dropdown though.
