### ISSUE TITLE
Sprite Fonts Sample is Broken

### ISSUE THREAD

**Issue by OnyeNacho** [stride3d/stride#1796]
**Release Type**: Official Release

**Version**: 4.1

**Platform(s)**: Windows

**Describe the bug**
The Sprite Fonts sample project has failed during compilation process.

**To Reproduce**
1. Start Stride.
2. Select "Sample: sprite fonts"
3. Wait for the engine to try and create a session.

**Expected behavior**
The session should be successful and launch the editor with the project so I can try it.

**Screenshots**
![Error](https://github.com/stride3d/stride/assets/2350777/07ec752f-f52b-43b5-b9ed-3570d965f6f1)

**Log and callstacks**
[Log.txt](https://github.com/stride3d/stride/files/12659445/Log.txt)

**Comment by Doprez** [comment]
Creating a PR now, sadly since some assets dont get imported due to the failure the code fix does not solve this immediately.

**Comment by Doprez** [comment]
May need more time than I thought. Some assets dont seem to exist at all in this package.

**Comment by Doprez** [comment]
https://github.com/stride3d/stride/pull/1798 should be fixed soon.

**Comment by OnyeNacho** [comment]
Thank you.
