### ISSUE TITLE
Font Crash

### ISSUE THREAD

**Issue by ly3027929699** [stride3d/stride#1806]
**Release Type**: GitHub

**Version**: master

**Platform(s)**: Windows 10

**Describe the bug**

**To Reproduce**
1. seleted Assets/SpriteFont
2. modify the FontSource to System Font

**Expected behavior**
A crash happened.

**Screenshots**
![image](https://github.com/stride3d/stride/assets/42492716/4e617ee9-e928-48da-8d55-2dc660733206)

**Log and callstacks**

**Additional context**
The Button's TextBlock  shrunked;
my repo:https://github.com/ly3027929699/TestStride

**Comment by ly3027929699** [comment]
This problem occurred last night and was not solved until I switched to the release version. I recompiled it today and still have the problem. it's all right with the release version.

**Comment by NicusorN5** [comment]
I think this was fixed by PR #1999 , but I might try to reproduce this on the latest release too just to be sure.

**Comment by Eideren** [comment]
Could not repro on latest, likely fixed by #1999 as @NicusorN5 pointed out
