### ISSUE TITLE
[Xaml] Invalid resource type: expected type is 'DataTemplate', actual type is 'DataTypeTemplateSelector'.

### ISSUE THREAD

**Issue by cNoNim** [stride3d/stride#1818]
**Release Type**: GitHub

**Version**: master

https://github.com/stride3d/stride/blob/c6fd21b1bc974fd3fed0f6089df31bb356b3e574/sources/editor/Stride.Core.Assets.Editor/Components/TemplateDescriptions/Views/TemplateBrowserUserControl.xaml#L60C95-L60C95

Guess type should be changed to DataTypeTemplateSelector in

https://github.com/stride3d/stride/blob/c6fd21b1bc974fd3fed0f6089df31bb356b3e574/sources/editor/Stride.Core.Assets.Editor/Components/TemplateDescriptions/Views/ObjectBrowserUserControl.xaml.cs#L56

**Comment by Eideren** [comment]
Fixed through #1822
