### ISSUE TITLE
[Xaml] Unable to resolve symbol 'compilerApp'

### ISSUE THREAD

**Issue by cNoNim** [stride3d/stride#1819]
**Release Type**: GitHub

**Version**: master

https://github.com/stride3d/stride/blob/c6fd21b1bc974fd3fed0f6089df31bb356b3e574/sources/editor/Stride.Core.Assets.Editor/Themes/generic.xaml#L80

https://github.com/stride3d/stride/blob/c6fd21b1bc974fd3fed0f6089df31bb356b3e574/sources/editor/Stride.Core.Assets.Editor/Themes/generic.xaml#L92

compilerApp -> diagnostics

**Comment by Eideren** [comment]
Fixed through #1822
