### ISSUE TITLE
[Xaml] Unable to resolve symbol 'ValueConverters'

### ISSUE THREAD

**Issue by cNoNim** [stride3d/stride#1820]
**Release Type**: GitHub

**Version**: master

https://github.com/stride3d/stride/blob/c6fd21b1bc974fd3fed0f6089df31bb356b3e574/sources/presentation/Stride.Core.Presentation.Graph/Themes/generic.xaml#L8

Assembly should be specified or namespace should be removed as not used.

**Comment by Eideren** [comment]
Fixed through #1822
