### ISSUE TITLE
Create a project for Linux support

### ISSUE THREAD

**Issue by Te3Que** [stride3d/stride#1824]
**Is your feature request related to a problem? Please describe.**
Have a project on the development for Linux support.
This can aid devs to easier contribute towards the end goal.

**Describe the solution you'd like**
A project so the more understanding devs can open issues that might be busy work for them, 
but could be a great issue for the less  understanding devs.

**Describe alternatives you've considered**
Ask on Discord for an exact file to work on?

Here are some questions that can aid in the description of the feature request:
- What are the usecases?
To aid new devs and enable them to make it easier contribute on the projects

**Comment by JeromyWalsh** [comment]
This item issue is resolved by https://github.com/stride3d/stride/issues/1922.
