### ISSUE TITLE
(Probably)Theme Update has leftover Test Elements

### ISSUE THREAD

**Issue by IXLLEGACYIXL** [stride3d/stride#1867]
**Release Type**: Official Release/GitHub (please choose appropriate option)

Current Github version

**Version**: Version number and/or git branch

**Platform(s)**: Does the problem occur on Windows, Android...?

**Describe the bug**
![grafik](https://github.com/stride3d/stride/assets/107197024/57a8e3d8-bb6b-4d31-8b82-b1b045fbb313)

These tests shouldnt be there

**To Reproduce**
1. open the settings of latest engine

**Expected behavior**
that its not there, probably came with the new theme edits

**Comment by manio143** [comment]
I think this was always there when compiling in Debug configuration. But sure, can probably be removed.

**Comment by IXLLEGACYIXL** [comment]
then leave it as is
