### ISSUE TITLE
Stride Game Studio Crashes when "unselecting" a normal map texture.

### ISSUE THREAD

**Issue by Salmakis** [stride3d/stride#1877]
**Release Type**: Official Release/GitHub (please choose appropriate option)
official relase from launcher

**Version**
4.1.0.1989

**Platform**
Windows

**Describe the bug**
When i add a Normal Map texture via Stride Game Studio into the assets, that works.
But when i then click that normal map, and then select anything else, Stride Game Studio Crashes.

**To Reproduce**
1. Add a normal map texture asset
2. click the normal map textur in the asset view
3. click something else in the asset view

**Comment by MeharDT** [comment]
I'm having trouble replicating this issue.

Does it happen with all of your normal maps or only a specific one? Can you also reproduce this issue in a empty new project?

**Comment by Salmakis** [comment]
Hi, thanks for investigating.

i just retried it with a new empty project:
![grafik](https://github.com/stride3d/stride/assets/12813949/edad9cd9-396c-4fa6-b4a8-1e0ad6438bc5)

i Tried it with a subfolder containing the normal map, also with direct in the asset root.

This is the file that i used as normal map:
![tilesNormal](https://github.com/stride3d/stride/assets/12813949/94860f9d-4280-4453-a9d6-ba017bfb8570)

its a 32bit png 512x512

**Comment by MeharDT** [comment]
Thanks for including the files, unfortunately I'm still not able to replicate a crash after including the texture in my project -> selecting the normal map in Asset View -> Selecting a different texture in Asset View.

Can you upload your empty project? If you can also copy the exception from Crash Reporter that could provide some clues as well.

**Comment by Salmakis** [comment]
im currently on another machine, where i installed the latest 4.1.0.1948 at least on this scenario i cant reproduce the issue by myself. i will try  it with the 4.1.0.1948 on my other machine but this will be in a few days.
then ofc i can post the log, i also send it via via this dialog in 4.1.0.1989 and 4.1.0.1939, i dont know if this is recieved somewhere.

**Comment by acastrodev** [comment]
Thank you, @Salmakis, I also attempted to replicate the issue using version 4.1.0.1948 and the provided file but could not reproduce it.

**Comment by Salmakis** [comment]
since i was not able to reproduce for a while it now in 4.1.0.1948 i close the issue.
