### ISSUE TITLE
OpenXR Broken

### ISSUE THREAD

**Issue by MaximilianEmel** [stride3d/stride#1909]
**Release Type**: Latest 4.1 Release & Master

**Version**: 4.1.0.1948 & b4442c12b20d9659d421d3d9ce7fead4728a66db

**Platform(s)**: Windows 10 w/ SteamVR

**Describe the bug**
OpenXR doesn't init at all, either in the Studio, or the Built Game.

**To Reproduce**
Use OpenXR as the VR API.

**Expected behavior**
The game to run as normal, as it would with for example, the OpenVR API.

**Log and callstacks**
[error.txt](https://github.com/stride3d/stride/files/12840735/error.txt)

**Comment by Eideren** [comment]
It's not broken anymore but it's not yet done, see #957
