### ISSUE TITLE
Errors : try to open Sample "Game Menu UI"

### ISSUE THREAD

**Issue by neoxeo** [stride3d/stride#1938]
**Release Type**: Official Release/GitHub (please choose appropriate option)
Official

**Version**: Version number and/or git branch
4.1.0.1948

**Describe the bug**
When I open first sample UI I have error messages

**To Reproduce**
1. Launch Game Studio
2. Select Sample "Game Menu UI"
3. Select Windows

**Expected behavior**
Error messages and solution does not open

**Screenshots**
![image](https://github.com/stride3d/stride/assets/5283778/b67b3e78-dc37-4796-9d5b-f321d2d37b96)

**Log and callstacks**
_Verbose: Process dependencies for GameMenu.Game...
Info: Upgrading project [GameMenu.Game] to use [Stride.Core] from version [4.1.0.1-beta] to [4.1.0.1948] will be required
Verbose: Restore NuGet packages for GameMenu.Game...
Verbose: Loading Assets from Package [Stride.Engine.sdpkg]
Verbose: Loading Assets from Package [Stride.Graphics.sdpkg]
Verbose: Loading Assets from Package [Stride.Particles.sdpkg]
Verbose: Loading Assets from Package [Stride.Rendering.sdpkg]
[D:\Stride3D\MyProjects\GameMenu\GameMenu.Game\UISceneBase.cs(23,37)]: Error: 'IServiceRegistry' ne contient pas de définition pour 'GetServiceAs' et aucune méthode d'extension accessible 'GetServiceAs' acceptant un premier argument de type 'IServiceRegistry' n'a été trouvée (une directive using ou une référence d'assembly est-elle manquante ?)
Error: Unable to build assembly reference [D:\Stride3D\MyProjects\GameMenu\GameMenu.Game\bin\Debug\net6.0\GameMenu.Game.dll]
Verbose: Loading Assets from Package [GameMenu.Game.sdpkg]
Warning: Could not deserialize object of type 'GameMenu.MainScript'; replacing it with an object implementing IUnloadable
YamlException: Unable to resolve tag [!GameMenu.MainScript,GameMenu.Game] to type from tag resolution or registered assemblies ((Lin: 21, Col: 54, Chr: 854) -> (Lin: 22, Col: 24, Chr: 914))
   at Stride.Core.Yaml.Serialization.Serializers.TagTypeSerializer.ReadYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\TagTypeSerializer.cs:line 131
   at Stride.Core.Yaml.ErrorRecoverySerializer.ReadYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ErrorRecoverySerializer.cs:line 21

Warning: Could not deserialize object of type 'GameMenu.SplashScript'; replacing it with an object implementing IUnloadable
YamlException: Unable to resolve tag [!GameMenu.SplashScript,GameMenu.Game] to type from tag resolution or registered assemblies ((Lin: 27, Col: 54, Chr: 1261) -> (Lin: 28, Col: 24, Chr: 1323))
   at Stride.Core.Yaml.Serialization.Serializers.TagTypeSerializer.ReadYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\TagTypeSerializer.cs:line 131
   at Stride.Core.Yaml.ErrorRecoverySerializer.ReadYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ErrorRecoverySerializer.cs:line 21

Verbose: Compiling game assemblies...
Verbose: Game assemblies compiled...
Verbose: Generating GameMenu.Windows...
Verbose: Process dependencies for GameMenu.Windows...
Verbose: Restore NuGet packages for GameMenu.Windows...
Verbose: Loading Assets from Package [Stride.SpriteStudio.Offline.sdpkg]
Verbose: Loading Assets from Package [Stride.Video.sdpkg]
Verbose: Loading Assets from Package [GameMenu.Windows.sdpkg]

**Additional context**

**Comment by Eideren** [comment]
Will be fixed through #1943
