### ISSUE TITLE
Managed Debugging Assistant Exception 'DisconnectedContext' or 'ContextSwitchDeadlock'.

### ISSUE THREAD

**Issue by PeaceSells50** [stride3d/stride#194]
**Release Type**: GitHub

**Version**: Compiled Locally. Xenko Version 3.0.0.5

**Platform(s)**: Windows 10

**Describe the bug**

**To Reproduce**

F5 Executing from Visual Studio 2017. X64. Compiled Xenko project.

Startup: Xenko.GameStudio

Alternates between two different exceptions.

I am not sure if this is relevant, but I am seeing this before the exceptions.

Just My Code Warning
You are debugging a release build of Xenko.Core.Design.dll. Using Just My Code with Release builds using compiler optimizations results in a degraded debugging experience(e.g. breakpoints will not be hit)

1. Mix Platform Configuration. Managed Debugging Assistant 'DisconnectedContext' : 'Transition into COM context 0x1bee85d8 for this RuntimeCallableWrapper failed with the following error: Exception from HRESULT: 0xE0434352. This is typically because the COM context 0x1bee85d8 where this RuntimeCallableWrapper was created has been disconnected or it is busy doing something else. Releasing the interfaces from the current COM context (COM context 0x1bee8700). This may cause corruption or data loss. To avoid this problem, please ensure that all COM contexts/apartments/threads stay alive and are available for context transition, until the application is completely done with the RuntimeCallableWrappers that represents COM components that live inside them.'

Exception Settings
Break when this exception type is thrown

2. Mix Platform Configuration. Managed Debugging Assistant 'ContextSwitchDeadlock' : 'The CLR has been unable to transition from COM context 0x52aa8fa0 to COM context 0x52aa8e78 for 60 seconds. The thread that owns the destination context/apartment is most likely either doing a non pumping wait or processing a very long running operation without pumping Windows messages. This situation generally has a negative performance impact and may even lead to the application becoming non responsive or memory usage accumulating continually over time. To avoid this problem, all single threaded apartment (STA) threads should use pumping wait primitives (such as CoWaitForMultipleHandles) and routinely pump messages during long running operations.'

Exception Settings

Break when this exception type is thrown

**Expected behavior**

No exception.

**Log and callstacks**

No call stack.

**Comment by Eideren** [comment]
Never seen this one before, we'll need more info to debug or reproduce it properly and given that on top of that no one else reported the same issue I'll close this one off. Feel free to create a new one if you do get this error again but please provide callstacks, hardware info and more.
