### ISSUE TITLE
[Website] answers.xenko.com license expired

### ISSUE THREAD

**Issue by justStand** [stride3d/stride#200]
Not sure where to post something like this.

http://answers.xenko.com/

**Comment by xen2** [comment]
Since AnswerHub is quite expensive, the plan was to move to something else.
I will redirect this page to something more meaningful in the meantime, sorry I didn't get around doing this sooner.

**Comment by Eideren** [comment]
The forum, discord and github issues now cover what answers provided, closing this one off.
