### ISSUE TITLE
[Crash] [Editor] AccessViolationException after duplicating a TextBlock

### ISSUE THREAD

**Issue by adrsch** [stride3d/stride#2004]
**Release Type**: GitHub

**Version**: The build is about 3 weeks old as of posting

**Platform(s)**: Edtior

**Describe the bug**
Serious bug, could cause loss of work.

**To Reproduce**
NOTE: I haven't tried to repro this yet, I'm not sure what the rate is... I was just lucky to have a debugger attached when this happened. But I had seen random crashing in the UI Editor - not sure how much is related to this.

1. I was in the UI Editor. The structure of the document is a grid with a TextBlock as a direct child. The font on the TextBlock is set to a runtime rasterized font which is a system font (Terminus TTF for Windows, you can download it, it's foss). Size 12, both in the font import settings and the TextBlock. 
2. The text wasn't displaying in the editor. I was trying to debug that, this bug just happened... I will maybe be able to write up that as another issue if I can figure out more on it.
4. I used the ctrl+D shortcut to duplicate the text block, and immediately the debugger hit this exception on the first character of the string.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)

**Log and callstacks**
[MiniStride.GameStudio.dmp](https://github.com/stride3d/stride/files/13198710/MiniStride.GameStudio.dmp)
![Screenshot 2023-10-29 101118](https://github.com/stride3d/stride/assets/35346279/681d4ea7-7cf9-49ab-bc9f-8cabdc4087a0)
![Screenshot 2023-10-29 101309](https://github.com/stride3d/stride/assets/35346279/3dab192d-25ed-4d0b-8cfe-8d4e54130ff4)

**Additional context**
![Screenshot 2023-10-29 101047](https://github.com/stride3d/stride/assets/35346279/355ee115-b9b9-4a7a-a2ab-be9822878d75)
![Screenshot 2023-10-29 101056](https://github.com/stride3d/stride/assets/35346279/8d655b7d-0487-4778-bd8b-c6d4b2a46bae)

**Comment by IXLLEGACYIXL** [comment]
https://github.com/stride3d/stride/issues/1750

currently fonts are borked up, idk if anyone found a solution yet

**Comment by adrsch** [comment]
> #1750
> 
> currently fonts are borked up, idk if anyone found a solution yet

I see, I see, that explains why I have a thousand seemingly unrelated issues whenever I'm using them.

Except one spot where I got them nicely on a ScrollingText. Painful! They're working great and I just want to use them for the whole project...

**Comment by manio143** [comment]
I've merged a fix from Basewq for the issue mentioned above. Should we close this one now?

**Comment by NicusorN5** [comment]
I will check #1692

**Comment by adrsch** [comment]
I will test the fix with it soon, sorry, work got real busy this week. But I will definitely do it myself! Don't want to make anyone else spend their time on it.

**Comment by adrsch** [comment]
Okay, it is confirmed fixed
