### ISSUE TITLE
2D collision issue - clipping through

### ISSUE THREAD

**Issue by WithBlueHorns** [stride3d/stride#2019]
**Release Type**: Official Release

**Version**: 4.1.0.1948

**Platform(s)**: Windows (the only tested)

**Describe the bug**
Sometimes rigid body will go through a collider, both having a box collider in a relative size to the objects.

**To Reproduce**
1. Download repro
https://drive.google.com/file/d/1k92RpKr9ftKCL7G1sSw82pNTvKcPs5rc/view?usp=sharing
2. Run
3. Wait 3 seconds, then rigidbody will have force applied to itself

**Expected behavior**
Rigid body should hit and stop/bounce off the collider, not clip through it

**Screenshots**

https://github.com/stride3d/stride/assets/95977080/e7cc9c0f-0cf2-4a2a-b14b-4144eb01f974

https://github.com/stride3d/stride/assets/95977080/38959d91-6278-429a-a2fe-22b8776202f5

**Log and callstacks**
No relevant logs

**Additional context**
Encountered the issue when tried a pong game, but encountered this.

**Comment by Eideren** [comment]
Wrapping up the box2dcollider in a convex2dcollider like it was before #1708 fixes this issue, can you weigh in on this @Jklawreszuk ?
I just quickly tested this constructor:
```cs
public BoxColliderShape(bool is2D, Vector3 size)
{
    Type = ColliderShapeTypes.Box;
    Is2D = is2D;
    size.Z = 0.04f;
    BoxSize = size;

    //Box is not working properly when in a convex2dshape, Z cannot be 0

    cachedScaling = Vector3.One;

    //if (is2D) size.Z = 0.001f;

    // Note: Creating Convex 2D Shape from (3D) BoxShape, causes weird behaviour,
    // better to instantiate Box2DShape directly (see issue #1707)
    if (Is2D)
    {
        InternalShape = new BulletSharp.Convex2DShape(new BulletSharp.Box2DShape(size / 2)) { LocalScaling = cachedScaling };
    }
    else
    {
        InternalShape = new BulletSharp.BoxShape(size / 2) { LocalScaling = cachedScaling };
    }

    DebugPrimitiveMatrix = Matrix.Scaling(size * DebugScaling);
}
```

**Comment by Jklawreszuk** [comment]
It looks like the collision problems lie deeper than I tought 😔 @Eideren, You can assign me to this issue, I'll take a look into

**Comment by Eideren** [comment]
Might be a good idea to look at bullet examples for 2d to see if there's anything weird they end up setting up on their end. For the changes I made above I quickly scanned through this one https://github.com/bulletphysics/bullet3/blob/master/examples/Planar2D/Planar2D.cpp

**Comment by VaclavElias** [comment]
Regarding 'InternalShape' and 'Is2D' I meant, can we make them `public`?

**Comment by Eideren** [comment]
Opened #2092 to fix this issue, do note that you also need to add continuous collision detection 
![image](https://github.com/stride3d/stride/assets/5742236/9ebbf5f6-7002-405d-80a7-9db8170e787d)
![image](https://github.com/stride3d/stride/assets/5742236/9b263ce8-7f9d-4c72-b0e1-6d6db0681d4b)
and set up your rigidbody properly:
![image](https://github.com/stride3d/stride/assets/5742236/427e4f50-89f0-40e3-89e4-9e0717ab6576)
