### ISSUE TITLE
undocking and redocking scene view breaks rendered scene

### ISSUE THREAD

**Issue by Doprez** [stride3d/stride#2031]
**Release Type**: GitHub

**Version**: master and 4.2.0.2043

**Platform(s)**: Windows

**Describe the bug**
Currently in Master when you undock and the redock the scene view it causes the scene render to go blank. You have to reload the scene to get the view back to normal.

**To Reproduce**
1. drag the scene tab into its own window.
2. place the scene back into the dock

**Expected behavior**
Sceneview should not be blank after redocking to GameStudio.

**Screenshots**
![image](https://github.com/stride3d/stride/assets/73259914/fcb5080d-6b7a-45b5-a40b-aef4941e832f)

**Additional context**
This works fine in the release 4.1.0.1948

**Comment by Eideren** [comment]
Closing this one in favor of #2161
