### ISSUE TITLE
[GameStudio] Code editor doesn't find auto completion info

### ISSUE THREAD

**Issue by tebjan** [stride3d/stride#2043]
**Release Type**:

Release 4.2 preview packages

**Describe the bug**
The code editor doesn't find the references to get code completion working.

**To Reproduce**
1. Open a C# code file in Game Studio

**Expected behavior**
Code gets parsed, errors reported and completions should work.

**Screenshots**
![image](https://github.com/stride3d/stride/assets/1094716/400d2b72-4460-4e3f-b89d-13780ad78c88)

**Additional context**
New 4.2 release todos.

**Comment by Kryptos-FR** [comment]
I tried updating the version of RoslynPad that we use but it crashes for various reason (the last one being it can't find the DiagnosticService).

**Comment by Eideren** [comment]
This is the exception in question:
```
System.Composition.Hosting.CompositionFailedException: 'No export was found for the contract 'IDiagnosticService'.'
    [External Code]
    Stride.Assets.Presentation.AssetEditors.ScriptEditor.RoslynHost.GetService<TService>() in RoslynHost.cs
    Stride.Assets.Presentation.AssetEditors.ScriptEditor.RoslynWorkspace.RoslynWorkspace(Stride.Assets.Presentation.AssetEditors.ScriptEditor.RoslynHost) in RoslynWorkspace.cs
    Stride.Assets.Presentation.AssetEditors.ScriptEditor.RoslynHost.RoslynHost() in RoslynHost.cs
    Stride.Assets.Presentation.AssetEditors.ProjectWatcher..ctor.AnonymousMethod__13_2() in ProjectWatcher.cs
    [External Code]
    Stride.Assets.Presentation.AssetEditors.ProjectWatcher.OpenProject(Stride.Core.IO.UFile) in ProjectWatcher.cs
    Stride.Assets.Presentation.AssetEditors.ProjectWatcher.UpdateProject(Stride.Assets.Presentation.AssetEditors.ProjectWatcher.TrackedAssembly) in ProjectWatcher.cs
    Stride.Assets.Presentation.AssetEditors.ProjectWatcher.TrackPackage(Stride.Core.Assets.Editor.ViewModel.PackageViewModel) in ProjectWatcher.cs
    Stride.Assets.Presentation.AssetEditors.ProjectWatcher.Initialize() in ProjectWatcher.cs
```
I don't really know what those exports are referring to, although RoslynPad's repo does have similar classes with export attributes declared:
```cs
namespace RoslynPad.Roslyn.Diagnostics;

[Export(typeof(IDiagnosticService)), Shared]
internal sealed class DiagnosticsService : IDiagnosticService
{
    [ImportingConstructor]
    public DiagnosticsService(Microsoft.CodeAnalysis.Diagnostics.IDiagnosticService inner)
```
here https://github.com/roslynpad/roslynpad/blob/6de624c47749016beded6f95f1b8794f007ce730/src/RoslynPad.Roslyn/Diagnostics/DiagnosticsService.cs#L4-L10

This is the commit that introduced this file in RoslynPad: https://github.com/roslynpad/roslynpad/commit/f4b0b3adf51fd6a70ecba304a84da39816dc1ed2

Creating the same class on our side doesn't fix the issue, I'm not familiar with any of that so hopefully someone else can take over.

**Comment by Eideren** [comment]
Nope, still the same issue.

**Comment by Eideren** [comment]
Could someone test the PR referenced above ^ ?
Thanks

**Comment by Kryptos-FR** [comment]
I tested it on top of #2046 and it does seem to work.
