### ISSUE TITLE
UI library margins reset to zero

### ISSUE THREAD

**Issue by YerkoAndrei** [stride3d/stride#2048]
**Release Type**: Official Release

**Version**: 4.2.2043

**Platform(s)**: Windows

**Describe the bug**
UI library margins reset when using in another UI library or a UI page

**To Reproduce**
1. Create a UI library with zero Margin
2. Use that UI library on a UI page or another UI library
3. In the UI page, change the margins on the child UI library
4. Reload proyect
5. Child UI library should reset to all zero, but still highlight the Margin property as it have a change

**Expected behavior**
The parent UI library or UI page, should save the changes on the child UI library

**Screenshots**
Only property affected on a .sduipage and .sduilib
![problema ilib en uipage](https://github.com/stride3d/stride/assets/19843418/337df5de-9e3c-4181-9e04-86af4b309091)

**Additional context**
Its not necessary to relaod the project, sometime it break when reloading a UI page tab.

**Comment by dawnmichal** [comment]
I just want to confirm that I also encountered this error.
