### ISSUE TITLE
Stride.CommunityToolkit Updates when it shouldn't

### ISSUE THREAD

**Issue by Doprez** [stride3d/stride#2053]
**Release Type**: Official Release and GitHub

**Version**: 4.2.0.2043

**Platform(s)**: Windows

**Describe the bug**
When opening Stride Stride.CommunityToolkit gets updated to the latest version, in this case 4.2.0.2043. 

**To Reproduce**
1. add the Stride.CommunityToolkit  nuget
2. open Strides editor

**Expected behavior**
since Stride.CommunityToolkit  does not follow the same release schedule it should be ignored from this upgrade step.

**Screenshots**
![image](https://github.com/stride3d/stride/assets/73259914/2a03e124-62b3-46e8-bff4-33e8fe19dd24)

**Log and callstacks**
```
[C:\dev\stride-dev\DotRecast-Stride\DotRecast.Stride\DotRecast.Stride\DotRecast.Stride.csproj(0,0)]: Error: Unable to find package Stride.CommunityToolkit with version (>= 4.2.0.2043)
  - Found 10 version(s) in nuget.org [ Nearest version: 1.0.0-preview.14 ]
  - Found 0 version(s) in Local nugets
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in C:\Program Files\dotnet\library-packs
  - Found 0 version(s) in Stride Dev
  - Found 0 version(s) in vvvv
[C:\dev\stride-dev\DotRecast-Stride\DotRecast.Stride\DotRecast.Stride.Windows\DotRecast.Stride.Windows.csproj(0,0)]: Error: Unable to build assembly reference [C:\dev\stride-dev\DotRecast-Stride\DotRecast.Stride\DotRecast.Stride\bin\Debug\net8.0\DotRecast.Stride.dll]
```

**Comment by VaclavElias** [comment]
I don't know anymore where we were discussing it but xen2 was suggesting, that only Stride NuGet packages should be updated, not the non Stride NuGet packages. So the toolkit, shouldn't be upgraded obviously, as anyone can name the NuGet package `Stride.Something.` and the engine shouldn't just upgrade it.

The question was how to get list of all NuGet packages, without listing them manually in the code, so when a new package is added, so we don't have to manually upload also the list..

**Comment by VaclavElias** [comment]
Discussed here actually https://github.com/stride3d/stride/pull/1881

**Comment by Doprez** [comment]
Yeah I made the isue before looking at the PRs lol, my mistake. I was wondering if we could make a call to the nuget API to see if the version exists but I wasnt sure if that was too expensive of a task or what the pitfalls may be.
