### ISSUE TITLE
Order of Projects in Editor changes the deciding of the main project to launch

### ISSUE THREAD

**Issue by IXLLEGACYIXL** [stride3d/stride#2054]
**Release Type**: Official Release/GitHub (please choose appropriate option)
any
**Version**: Version number and/or git branch
4.2
**Platform(s)**: Does the problem occur on Windows, Android...?

**Describe the bug**
The order of the Projects decides which Project is used by the game studio to use as launch project.
If the order in the Editor has a Testproject first in the order it launches that instead of the game.
**To Reproduce**
1. Make a test project which is in the order at spot 1
2. Launch game
3. it launches the test project

**Expected behavior**
Idk where C# gets the info for the project to launch, but that should be taken instead of the order of the projects in the editor.

**Comment by Kryptos-FR** [comment]
There has to be a *current* project  so it takes the first as default, since there aren't other way to guess. You can set the current project by right-clicking on it in the explorer.

The same can happen when you target multiple platforms.

In my opinion this is not a bug.
