### ISSUE TITLE
Add Component (Script) silently fails when Script constructor throws exception

### ISSUE THREAD

**Issue by jonstelly** [stride3d/stride#209]
**Release Type**: Official Release/GitHub (please choose appropriate option)
GitHub

**Version**: Version number and/or git branch
main

**Platform(s)**: Does the problem occur on Windows, Android...?
Game Studio

**Describe the bug**
Adding a Script Component to an Entity, where the Script constructor fails, Game Studio fails to add the Script to the entity but gives no feedback why.

**To Reproduce**
1. Create a script like:
```
public class SomeScript : SyncScript
{
    public SomeScript()
    {
        throw new InvalidOperationException("I meant to do this");
    }

    public override void Update()
    {
        throw new NotImplementedException();
    }
}
```

2. Attempt to add this script as a component to an entity
3. Nothing happens, no error, no indication of what failed

**Expected behavior**
Some sort of indication that adding the component failed

**Additional context**
I've got a proposed fix for this but would like some feedback.  Making the change below shows a MessageBox with the exception details and it also seems that this would cover more cases than just adding a component (should handle all commands derived from SyncNodePresenterCommandBase)

For some questions:
1) Does MessageBox make sense here or would it be better to write this sort of thing to some sort of log, like the Build log maybe, but an Editor log or something similar?
2) I notice that the MessageBox shows up twice for me... I haven't tracked down exactly why yet.
3) Other thoughts?

![image](https://user-images.githubusercontent.com/967068/45784000-05b37f80-bc2d-11e8-9813-8831df69ab27.png)

Example for my case:

![image](https://user-images.githubusercontent.com/967068/45784131-4f03cf00-bc2d-11e8-999d-9e785b0c9264.png)

**Comment by Eideren** [comment]
PR #256 shares some information and files required to fix this issue, as such reading through and looking at the files changed there is a good starting point if someone wants to take care of this issue.
See also #220 .
