### ISSUE TITLE
Cherrypick stride.core.assets.(https://github.com/stride3d/stride/commit/3490d527f3ca8135eaf8f544560b2105abd21e80) I messed up a bit.

### ISSUE THREAD

**Issue by meriaizen86** [stride3d/stride#2114]
Cherrypick stride.core.assets.(https://github.com/stride3d/stride/commit/3490d527f3ca8135eaf8f544560b2105abd21e80) I messed up a bit.

_Publicado originalmente por @meriaizen86 en https://github.com/stride3d/stride/pull/2103#pullrequestreview-1834705530_

**Comment by Eideren** [comment]
?
