### ISSUE TITLE
solution item is disappeared when save in Stride Editor

### ISSUE THREAD

**Issue by itn3000** [stride3d/stride#2123]
**Release Type**: Official Release

**Version**: 4.2.0.2067

**Platform(s)**: Windows

**Describe the bug**
When Saving project by Stride editor, solution items which is added with Visual Studio is disappeared from solution file.

**To Reproduce**
1. create new project
2. open project with Visual Studio
3. add solution item with Visual Studio(e.g. README.md)
4. edit project with Stride Editor(e.g. add entity, edit settings)
5. save project with Stride Editor

**Expected behavior**
sln file contents is preserved when Saving project with Stride Editor, 

**Log and callstacks**
sln before saving Stride Editor is here.
[before-save.txt](https://github.com/stride3d/stride/files/14048194/before-save.txt)
and sln after saving Stride Editor is here
[after-save.txt](https://github.com/stride3d/stride/files/14048207/after-save.txt)

**Comment by Kryptos-FR** [comment]
Did you save the solution in VS (using Save All)? VS is known for not saving the solution every time there is a change. So you have to make sure about that.

To me the issue is with VS, I have the same problem when using other external tools. Nothing we can do on our end I'm afraid as we can't read VS memory only what's on the disk.

**Comment by IXLLEGACYIXL** [comment]
https://github.com/stride3d/stride/pull/2106
i cant reproduce it with this pr

ive done:
1. add solution item
2. wrote hi into the md, save  with ctrl s
3. added sprite component to my camera
4. ctrl s in the editor
and ive done
1. add solution item
2. wrote hihi into the md, NOT save  with ctrl s
3. added sprite component to my camera
4. ctrl s in the editor
both items are still there and didnt get removed from the solution after these

**Comment by itn3000** [comment]
sorry, I tried re-investigating, solution item was preserved when did following steps
1. create new project
2. open project with Visual Studio
3. add solution item with Visual Studio(e.g. README.md)
4. *reload project(from "File" menu) with stride editor*
5. edit project with Stride Editor(e.g. add entity, edit settings)
6. save project with Stride Editor

by the way, I found unexpected newline was inserted at head of sln file always when saving with stride editor.

**Comment by IXLLEGACYIXL** [comment]
can you try that with my PR ?

**Comment by itn3000** [comment]
I have not tried yet, I will test with this PR. Thank you.

**Comment by IXLLEGACYIXL** [comment]
> sorry, I tried re-investigating, solution item was preserved when did following steps
> 
>     1. create new project
> 
>     2. open project with Visual Studio
> 
>     3. add solution item with Visual Studio(e.g. README.md)
> 
>     4. _reload project(from "File" menu) with stride editor_
> 
>     5. edit project with Stride Editor(e.g. add entity, edit settings)
> 
>     6. save project with Stride Editor
> 
> 
> by the way, I found unexpected newline was inserted at head of sln file always when saving with stride editor.

i cant reproduce that either with my PR 
please try it so i can linkt the PR with this issue to mark it as solved

no idea about that one new line ...its just there.. menacingly
