### ISSUE TITLE
BoundingCircle?

### ISSUE THREAD

**Issue by tonisimakov99** [stride3d/stride#2159]
This will speed things up a bit in 2D collision checking scenarios

**Comment by NicusorN5** [comment]
If you strictly need 2D circle circle collisions, they're absolutely trivial to implement manually. Otherwise use rigidbodies with this configuration 
![image](https://github.com/stride3d/stride/assets/20599225/daba948f-e03f-48fc-b531-8006ecce00a1)

**Comment by tonisimakov99** [comment]
> If you strictly need 2D circle circle collisions, they're absolutely trivial to implement manually. Otherwise use rigidbodies with this configuration ![image](https://private-user-images.githubusercontent.com/20599225/305675184-daba948f-e03f-48fc-b531-8006ecce00a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjIzMDIsIm5iZiI6MTcwODIyMjAwMiwicGF0aCI6Ii8yMDU5OTIyNS8zMDU2NzUxODQtZGFiYTk0OGYtZTAzZi00OGZjLWI1MzEtODAwNmVjY2UwMGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDAyMDY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMTMzNzE1NDEyNWI1ZDNkYjViNTQyMDNhMTIwYjFiYWMzYWRmMjhhMDg3ZWRlNjFmOWRmMTIxNjZkMzg0N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.owQmi3HMbUiLYi3Mld28HeY_9zCRcXmBO5nOyKy7QX0)

In general, I just want to use the capabilities of the engine in the server part of the game, and I need to get information about collisions in the system. Without rendering.
