### ISSUE TITLE
[EXEC(0,0)]: Error: [AssetCompiler] Unhandled exception. Exception: InvalidOperationException: 

### ISSUE THREAD

**Issue by Generalec** [stride3d/stride#2164]
# Question and/or Comment
Hello,

I imported model with name consisted with space. ThereforeI got error related to this invalid naming.

`[EXEC(0,0)]: Error: [AssetCompiler] Unhandled exception. Exception: InvalidOperationException: Assets names cannot have empty spaces before or after the name. Please rename [Models/Line/Line/2/line3_ ] and compile again.`

But after I remated model without space and also deleted model. I still got this error message.

I tried to find file where is asset path stored but no success.

I restarted Stride several times and reloaded assemblies also ...

Where I can delete it manualy, please?

**Comment by Doprez** [comment]
if you go to your `project/Assets` folder you said there was nothing there? 

Unfortuantely I cant seem to recreate this error, but if you open the project folder in VSCode and then do a search all for `line3_` does anything come up?

**Comment by Generalec** [comment]
> if you go to your project/Assets folder you said there was nothing there?

Correct. There is no particular file.

I tried to Find in Files option - line3_ and I could not find anything

Well I stared to using my backup project so I don't have problem to continue but it's strange.

**Comment by Generalec** [comment]
Well I stared to using my backup project so I don't have problem to continue.
