### ISSUE TITLE
Null reference exception when opening GameStudio settings

### ISSUE THREAD

**Issue by johang88** [stride3d/stride#2182]
**Release Type**: Github

**Version**: master

**Platform(s)**: Windows

**Describe the bug**
GameStudio crashes with a null exception when clicking Edit -> Settings.

**To Reproduce**
1. Open a project in game studio
2. Click Edit
3. Click Settings

**Expected behavior**
Not to crash ...

**Log and callstacks**
[gamestudio crash log.txt](https://github.com/stride3d/stride/files/14551475/gamestudio.crash.log.txt)

**Comment by johang88** [comment]
3/4 values are null

![image](https://github.com/stride3d/stride/assets/204513/79abe014-2cb4-4c46-9921-8e3f8e97c054)

**Comment by Doprez** [comment]
https://github.com/stride3d/stride/pull/2195

hopefully this should fix this issue.

**Comment by Eideren** [comment]
Should be fixed, update to 4.2.0.2122 through the launcher

**Comment by johang88** [comment]
Can confirm that it's fixed 👍
