### ISSUE TITLE
Opening Settings causes Game Studio to crash

### ISSUE THREAD

**Issue by AbsoluteWisp** [stride3d/stride#2194]
**Release Type**: **Official Release**/~~GitHub~~ (please choose appropriate option)

**Version**: Stride 4.2.0.2121 + .NET 8.0.3 + VS 17.9.4 (2022) + Windows 11 10.0.23606.1000 (Insider build, Dev branch) 

**Platform(s)**: Windows, in Game Studio

**Describe the bug**
When using the basic "New game" template (the one with ground and a sphere where you can fly and look around), two issues can be observed:
- The built-in code editor highlights errors at all namespace `using` declarations (both those under `Stride.somethingsomething` and those that are parts of .NET, like `System`). VS 2022 (w/ extension) shows no such errors on the exact same solution, and the project builds properly.
- Opening settings (Edit > Settings) shows an empty settings window and crashes the editor app.

**To Reproduce**
1. Create a new project with the "New game" template.
2. Try to open settings.

**Expected behavior**
Settings window is opened and usable.

**Screenshots**
![stridecrash](https://github.com/stride3d/stride/assets/86200600/00a11ed1-eb32-4c85-a12b-2bfd968aa149)

**Log and callstacks**
Stride-generated crash report: [crashreport.txt](https://github.com/stride3d/stride/files/14692000/crashreport.txt)

**Additional context**
Probably related to #2192 but opened new issue to add more context.

**Comment by Doprez** [comment]
if you go to `C:\Users\User\AppData\Roaming\Stride` is there a `GameStudioInternal.conf` file? 

I cant seem to recreate this issue, I wonder if its because I used Stride before the most recent release.

**Comment by AbsoluteWisp** [comment]
![image](https://github.com/stride3d/stride/assets/86200600/00de1371-41cf-48e0-a323-022689b044b0)
I have the file under my regular user. I also did a sanity check on a brand-new user (ran stride once, then looked), and it's also there.

**Comment by AbsoluteWisp** [comment]
In that case, would there be a workaround possible by copying a known-good `conf` file into there? Might be noteworthy while a proper fix is being implemented by those smarter than me.

**Comment by Doprez** [comment]
you can try copy pasting my settings into your file.
```
!SettingsFile
Settings:
    Interface/AskBeforeReloadingAssemblies: false
    Interface/AutoReloadAssemblies: true
    Themes/ThemeName: DarkSteel
```

but if the file is already there I dont know if that will work properly. Ill have to debug the Stride source when Im off work on the machine that has the issue.

If you have the time you can try using Stride 4.1 with .NET 6 to see if the same issue occurs. If so then it may be a windows 11 issue as well.

**Comment by AbsoluteWisp** [comment]
Tried your config just to be sure, predictably still crashing. Trying 4.1.0.1948 now

**Comment by Doprez** [comment]
awesome, if you reopen 4.2 does it work now?

**Comment by AbsoluteWisp** [comment]
Nope. 4.2 still crashes

**Comment by Doprez** [comment]
Interesting, Im not sure what is making it work on my desktop but not my laptop then. Eitherway Ill try to take a look after work, hopefully its an easy fix lol.

**Comment by AbsoluteWisp** [comment]
Maybe something Win11-related that ALSO only affects 4.2?
Which seems wildly improbable but who knows at this point. If there are any other engine versions that you'd like me to try, just let me know, I have a lot of free time today and tomorrow (Friday). I can also try stuff on a stable Win11 install, but I have nothing on hand right now that's still running on 10.

**Comment by Doprez** [comment]
AHA even better news, it seems like it was just the most recent minor version release that broke the settings window. 

Stride 4.2.0.2067 works fine on both my machines. so you can use the newer version at least.

**Comment by AbsoluteWisp** [comment]
That seems to be doing the trick!
