### ISSUE TITLE
[Community Toolkit] iOS Bug: "System.DllNotFoundException, Message=freetype" - What does this mean? Any fix?

### ISSUE THREAD

**Issue by jonmdev** [stride3d/stride#2197]
## Version

**Release**:  Stride Community Toolkit NuGet 1.0.0-preview.20
**Platform(s)**: iOS

## Context

I am attempting to create an integration pathway with Maui to allow crossplatform gaming for iOS/Android/Windows with Microsoft Maui as discussed [here](https://github.com/stride3d/stride/discussions/2196).

I think this would be a massive benefit for Stride, cross platform gaming, and Maui apps where simple lightweight 3D elements are needed (eg. 3D product visualization or secondary game play functions).

The Community Toolkit is a fantastic candidate for this as it can be added to an existing .NET 8 project with a simple NuGet. A code only approach should allow easy integration.

## Bug
However, unfortunately, if I create a default Maui project in Visual Studio 2022 and add the Stride Community Toolkit NuGet, even with no other steps taken (not even using Stride, just add package), I can no longer build the project to iOS.

Attempts to build to iOS (USB attached iPhone, set to Debug mode on top bar and target iPhone) provides the following error:

```
System.DllNotFoundException
  Message=freetype
```

I am not sure what this represents. Any thoughts/suggestions/fixes?

## Screenshot
**Screenshots**
<img width="500" alt="ios freetype" src="https://github.com/stride3d/stride/assets/43948450/c9fefe29-f7dd-44c0-9bf5-04c102c48adb">

## Repro Code

**Repro Project**
https://github.com/jonmdev/MauiStride

**To Reproduce**
1. In Visual Studio 2022 go File > New > .NET8 MAUI project
2. Add Stride Community Toolkit NuGet
3. Select "Debug" and USB attached iPhone and click "Debug"

## Goal
**Expected behavior**
Need to be able to build to iOS with Community Toolkit installed without error in order to continue integration attempts.

Stride seems like a fantastic project! I already adore the code only approach and simplicity of the Community Toolkit! Thanks for any ideas or suggestions.

**Comment by YanYas** [comment]
There was something mentioned about it in the Stride/Linux discord chat. [Here](https://discord.com/channels/500285081265635328/999260755654365184/1218282731926978570). See the message above it for context.
It also links to [here](https://doc.stride3d.net/latest/en/manual/platforms/linux/setup-and-requirements.html?tabs=freetype-ubuntu%2Copenal-ubuntu%2Csdl2-ubuntu). I have no idea what effect this has with Mac/IOS.
