### ISSUE TITLE
[Editor] ScriptComponent drag and drop on Entities fails

### ISSUE THREAD

**Issue by Eideren** [stride3d/stride#221]
**Release Type**: GitHub

**Version**: 3.0.0.6 commit [ac4e7e0](https://github.com/xenko3d/xenko/commit/ac4e7e03b8e2e0e68005589bd52f7f2a2aba7b1a)

**Platform(s)**: Windows Editor

**Describe the bug**
Dragging a ScriptComponent over an entity shows "No scripts inheriting from {nameof(ScriptComponent)} found in asset {asset.Url}"

**To Reproduce**
See description.

**Expected behavior**

**Screenshots**

**Log and callstacks**

**Additional context**
[typesForPath](https://github.com/xenko3d/xenko/blob/57087ee16451064d737bb15362a14029a5092211/sources/editor/Xenko.Assets.Presentation/AssetEditors/ScriptSourceCodeResolver.cs#L49) is used to check if a file implements `ScriptComponent` but is never populated.
A part of a method seems to be used to populate it but it just [access it instead](https://github.com/xenko3d/xenko/blob/57087ee16451064d737bb15362a14029a5092211/sources/editor/Xenko.Assets.Presentation/AssetEditors/ScriptSourceCodeResolver.cs#L138) which should throw but doesn't because the program never reaches that point: [GetCompilationAsync](https://github.com/xenko3d/xenko/blob/57087ee16451064d737bb15362a14029a5092211/sources/editor/Xenko.Assets.Presentation/AssetEditors/ScriptSourceCodeResolver.cs#L72) fails to compile properly. `GetDiagnostics` on the `gameProjectCompilation` doesn't contain anything, so does `GetSymbolsWithName`, the function exits out [here](https://github.com/xenko3d/xenko/blob/57087ee16451064d737bb15362a14029a5092211/sources/editor/Xenko.Assets.Presentation/AssetEditors/ScriptSourceCodeResolver.cs#L85).

**Comment by justStand** [comment]
Was there ever a fix or at least a workaround?

**Comment by justStand** [comment]
it seemed to stem from an issue with broken configuration files. https://github.com/xenko3d/xenko/issues/312
