### ISSUE TITLE
How to get latest version?

### ISSUE THREAD

**Issue by m1911star** [stride3d/stride#2249]
![image](https://github.com/stride3d/stride/assets/4948120/70f11afb-9b0a-4c92-a7fe-8473432883e4)

**Comment by m1911star** [comment]
I download the latest launcher, but only version 3.x is valid

**Comment by IXLLEGACYIXL** [comment]
open visual studio and go to nuget configuration adn add the blue higlhlighted soruce
![grafik](https://github.com/stride3d/stride/assets/107197024/c14c5f77-2483-49a1-8a9e-c80cae46f9e3)

**Comment by m1911star** [comment]
solved, thanks!

**Comment by IXLLEGACYIXL** [comment]
non VS solution `dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org`
found on https://github.com/NuGet/Home/issues/10804
