### ISSUE TITLE
Duplication of Entity with List<T> variable (where T is something referenceable in a scene like Entities or Components) crashes editor

### ISSUE THREAD

**Issue by YerkoAndrei** [stride3d/stride#2255]
**Release Type**: Official Release

**Version**: 4.2.0.2122

**Platform(s)**: Windows (Editor)

**Describe the bug**
When duplicate (ctrl + d / ctrl+c + ctrl+v) an entity with a script with a not null List<T> variable, the editor crashes.
This happens when the List Type is something in the scene like Entities or Components, for example: `List<Entity>` or `List<TransformComponent>` crashes, but `List<Prefab>` or `List<Sound>` doesn't.

**To Reproduce**
1. Create script with a List<T> variable (Type must be something referenceable in a scene)
2. Add script to any Entity
3. Select the Entity
4. Duplicate with ctrl + d

**Expected behavior**
Entity should duplicate with references

**Log and callstacks**
In this Crash i use a script in the Entity "Botón (Amarillo)"
[Crash.txt](https://github.com/stride3d/stride/files/15371453/Crash.txt)

**Additional context**
Example class:
```
using System.Collections.Generic;
using Stride.Engine;

namespace Example;

public class CrashExample : StartupScript
{
    public List<Entity> entities = new List<Entity> { };

    public override void Start()
    {

    }
}
```

**Comment by Kryptos-FR** [comment]
It's not a random List<T> though, it is explicitly a list of entities. If it doesn't happen with other types, please update the title and description.

**Comment by YerkoAndrei** [comment]
updated
