### ISSUE TITLE
Add ExpDecay function for framerate independent damping

### ISSUE THREAD

**Issue by tebjan** [stride3d/stride#2301]
**Is your feature request related to a problem? Please describe.**
See, Lerp smoothing is broken, click the video below:
[![Enhanced Exponential Decay Function Explanation](https://img.youtube.com/vi/LSNQuFEDOyQ/0.jpg)](https://youtu.be/LSNQuFEDOyQ)

**Describe the solution you'd like**
![image](https://github.com/stride3d/stride/assets/1094716/ee26645b-dc0f-4738-a1e7-c8abab97bd5f)

instead of:
`a = lerp(a, b, damping * dt)`

Implementations for both, C# and SDSL.

Here are some questions that can aid in the description of the feature request:

- What are the use cases?
Daping between two values over time for smooth motion

**Comment by Kryptos-FR** [comment]
The only issue is that `exp()` is more expensive computationally.

**Comment by tebjan** [comment]
The more important issue ist that Lerp smoothing doesn't work correctly. Watch the first half of the video. Especially if you want to deliver a consistent user experience on all machines. It might affect SFX too badly, but if gameplay relies on it, no option has better performance.
