### ISSUE TITLE
FBX Bone Start is root for bone links

### ISSUE THREAD

**Issue by IXLLEGACYIXL** [stride3d/stride#2313]
**Release Type**: Official Release/GitHub (please choose appropriate option)

4.2

**Describe the bug**

Standard ( blender atleast ) of armatures is that the peak is the end and gets rotated and such 
Assume we have one bone hand,
rotating the hand results in blender animation that the peak is moved, in stride the bone link will link to the fat end but the weapon attached to that bone link is in an offset to that bone
![grafik](https://github.com/stride3d/stride/assets/107197024/78fd77d9-44c3-487e-9059-a143138d2dae)

**To Reproduce**
1.  make a blender bone attached to a cube and move the tip in an animation
2. attach in stride a bone link
3. bone link is moving in an offset of the animation

**Expected behavior**

The bone link should either attach to the peak, or give an option to attach either to the peak or the fat end of the bone

**Comment by IXLLEGACYIXL** [comment]
the work around seems to be to add an extra bone and targeting that one

**Comment by ArieLeo** [comment]
i'm curious, is this kind of setup worked in previous version? because afaik the concept of Bone Head=Root and Bone Tail=Tip from blender are doesn't exist in game engine. Blender just built different

**Comment by IXLLEGACYIXL** [comment]
adding extra bones to the nodes you want to reach with the bone link bypasses the problem so i guess its fine
