### ISSUE TITLE
Launcher unable to connect to xenko server

### ISSUE THREAD

**Issue by SeleDreams** [stride3d/stride#232]
**Release Type**: Official Release

**Version**: 2.0.0 (of the launcher)

**Platform(s)**: Windows

**Describe the bug**
When launching the Xenko launcher in order to download a build of xenko, the launcher gets the error "Unable to connect to Xenko server. Switching to offline mode"
**To Reproduce**
1. Download the launcher from the xenko website.
2. Install it.
3. Launch it.

**Expected behavior**
The launcher should display the available xenko build from the server to install it.

**Screenshots**
![image](https://user-images.githubusercontent.com/16335601/46812469-14e1a500-cd75-11e8-8cc0-02e6cf532955.png)

**Additional context**
My internet connexion is perfectly working, I'm writing this bug report directly from this exact same PC, I didn't receive any warning from the firewall either.

**Comment by Kryptos-FR** [comment]
So what should the issue resolution be? It happens that network have some down time. Wait for a while and try again.

**Comment by Kryptos-FR** [comment]
Sorry that was a bit harsh. Do you still have an issue? If so feel free to reopen it.
Apologies.

**Comment by pikachuk** [comment]
The issue is still happening for me, yes

**Comment by Kryptos-FR** [comment]
Reopened. I should stay off GitHub when I am in a bad mood.

**Comment by pikachuk** [comment]
Since I still can't connect after multiple attempts even after reinstalling etc, is there a way to download the prebuilt editor ? I tried to build the editor from source but I get a lot of issues, for instance clang is said as unsupported by my pc, then when I replace the clang executable, i get errors when it builds irony and xenko.execserver etc etc

**Comment by Kryptos-FR** [comment]
At that point, I think that there is a lot of issues on your machine. I don't see any issue with Xenko packages. And following the instructions (and installing all the prerequisites as stated on the README) compiling works fine.

Consider cleaning and or reinstalling your operating system; and keep default configurations for where softwares are installed and for the system paths.

**Comment by pikachuk** [comment]
I guess I'll wait for my new pc since I'll get a new pc soon
I can't keep default config on my current pc because the C drive only has 80gb but on my next pc it will have an ssd of 240gb as the C drive so it will be better

**Comment by pikachuk** [comment]
The cause of the issue has been found https://github.com/xenko3d/xenko/issues/287
