### ISSUE TITLE
Navigation mesh always recalculating

### ISSUE THREAD

**Issue by GideonUng** [stride3d/stride#233]
**The navigation mesh seems to always update when entities are moved in a scene even if the entities arent relevant to the navigation mesh**

**To Reproduce**
1. Setup navigation for a scene (navigationmesh, navigation bounding box)
2. Move an entity that has no influence on navigation (different collision layer, entity without collision at all)
3. Watch the navigationmesh reclaculate and update

**Expected behavior**
Navigation should only be updated if navigation related objects update in the scene.
If objects that are not relevant to the navigation mesh update their values the navigation mesh should not be updated.

**Additional context**
It seems that any value changes trigger a recalculate. even if e.g. a property of some component is changed the nav mesh is recalculated

**Comment by devjarmo** [comment]
How were you checking to see if this was recalculating? I have a dynamic mesh and delegate to NavigationMeshUpdated and I’m not seeing this behavior but I am experiencing some performance hits so I’m curious if it is this issue.

**Comment by GideonUng** [comment]
This was related to editor behavior. Im pretty sure i had a look at the source code of this problem too and i think i talked to Xen2 on the discord about this briefly. but its all to long ago for me to remember and i have no idea what the current state of this is.

**Comment by devjarmo** [comment]
Ok thanks. I ran some profiling and watched the performance of my box and found my issue to be unrelated. In don’t believe I’m seeing this occurring, I will be adding some rigid body Colliders to the scene today and will continue to monitor.

**Comment by Eideren** [comment]
@GideonUng is this fixed ?

**Comment by GideonUng** [comment]
@Eideren dunno. its a 5 year old issue. i havent used stride in just as long. just deleted all old issues i had open anywhere.
let someone who uses stride open an issue if it still exists.

**Comment by GideonUng** [comment]
no one has looked at this in 5 years. why is it being reopened

**Comment by Eideren** [comment]
As long as no one validated whether the issue still exist, which it most likely does given how little that area changed over the years, there is no reason to close it. Why are you being this contentious about such a trivial subject ? It is still useful for us, just leave it open, it's not like anyone would bother you given how little traction it is getting.
