### ISSUE TITLE
can't find MSBuild

### ISSUE THREAD

**Issue by Sunflair0** [stride3d/stride#2336]
I have downloaded MSBuild from Visual Studio. I asked ChatGPT to help me, and it suggested: 

Select Workloads:

In the installer, select the workloads you need. For MSBuild, you can choose:
.NET desktop development
ASP.NET and web development
Desktop development with C++

In following the path that MSBuild should be on. I see I have Program Files and Program Files (x86) and Program Files and Program Files. Which path is where the build should be?

**Platform(s)**: Does the problem occur on Windows, Android...?
Windows

**Describe the bug**
Pushing the start 4.2.0.2149 button makes this message come up. Cannot advance past it.

Error message:
Stride Game Studio 4.2.0.2149 (.NET 8.0.6)

Could not find a compatible version of MSBuild.
Check that you have a valid installation with the required workloads, or go to www.visualstudio.com/downloads to install a new one. Also make sure you have the latest .NET 6 SDK 
System.InvalidOperationException: Failed to find all versions of .NET Core MSBuild. Call to hostfxrresolvesdk2. There may be more details in stderr. at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetSdkFromGlobalSettings(String workingDirectory) at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext() at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext() at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext() at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable1 source, Func2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable1 source, Func`2 predicate) at Stride.Core.Assets.PackageSessionPublicHelper.FindAndSetMSBuildVersion() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\PackageSessionPublicHelper.cs:line 40 at Stride.GameStudio.Program.Startup(UFile initialSessionPath) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.GameStudio\Program.cs:line 221

**Comment by Sunflair0** [comment]
or both?

**Comment by MeharDT** [comment]
The "ASP.NET and web development" workload is not needed for Stride and MSBuild isn't either for Stride 4.1+.

Have you downloaded the latest .NET 8.0 SDK?

https://dotnet.microsoft.com/en-us/download/dotnet/8.0

**Comment by VaclavElias** [comment]
Not sure if this helps. ..

I have MSBuild in this location. It wasn't added to PATH be default. I usually refer just the whole path..

![image](https://github.com/stride3d/stride/assets/4528464/6f5caa97-f72d-4805-9a23-e15cc6ca2e0c)

**Comment by Sunflair0** [comment]
You caught me in the middle of ripping out MSBuild and reinstalling it. I will download 8 again. The 64 version. I think earlier I may have done the 84, but not sure. 
To answer, yes, I have done it, but now I am 'repairing' the download.

**Comment by Sunflair0** [comment]
The reason I am re-doing the MSBuild is because I don't see the .exe file in my list. Just about everything else is.

**Comment by Sunflair0** [comment]
If I don't need MSBuild for 4.2, then why the error message?

I finished .net 8.0 and it gives me the same error.

**Comment by MeharDT** [comment]
> If I don't need MSBuild for 4.2, then why the error message?
> 
> I finished .net 8.0 and it gives me the same error.

Can you restart your PC after the installation and try opening Stride again?

The error message is out of date and will likely be changed in a future update to reflect the new requirements.

**Comment by Sunflair0** [comment]
no change. I did a restart, and still the same.
What else could it mean? I have been at this for weeks and about to give up.

**Comment by IXLLEGACYIXL** [comment]
what happens when you run in powershell `dotnet --list-sdks`

**Comment by VaclavElias** [comment]
I was just about to ask the same if we could have an output of that :)

**Comment by Sunflair0** [comment]
![stride6 18 24](https://github.com/stride3d/stride/assets/62845098/3f92edaf-e51c-4a03-82b2-ba68d64f9628)

**Comment by Sunflair0** [comment]
Must I run this after I change my directory? To what should I change it?

**Comment by IXLLEGACYIXL** [comment]
it runs dotnet command and lists all installed sdks

you dont have an installed sdk

you probably installed the runtime 
https://dotnet.microsoft.com/en-us/download
![grafik](https://github.com/stride3d/stride/assets/107197024/c0624c44-007d-4f1f-ae46-40cfe4e7b44c)
thats what you want, the link previously sent gives all options which are available and you probably just clicked on runtime and not the sdk for windows

**Comment by IXLLEGACYIXL** [comment]
after you installed that, restart your pc

**Comment by Sunflair0** [comment]
![stride6a 18 24](https://github.com/stride3d/stride/assets/62845098/96d2f145-9378-402f-9621-d7b389e2a0a1)

I have not done it again, but I will try it if you think something will be different. (green is what I just downloaded, but not installed and restarted computer again)

**Comment by IXLLEGACYIXL** [comment]
does the command now list it?
![grafik](https://github.com/stride3d/stride/assets/107197024/46d55e88-15fd-4b85-ac0d-c5eed6231407)
should output something like this

**Comment by Sunflair0** [comment]
nada.
I even changed the directory to match yours (\users)

**Comment by IXLLEGACYIXL** [comment]
does this path contain the sdk , run that `ls 'C:\Program Files\dotnet\sdk'`

**Comment by IXLLEGACYIXL** [comment]
can you check this too https://github.com/dotnet/sdk/issues/22508#issuecomment-963494604

**Comment by Sunflair0** [comment]
![stride6b 18 24](https://github.com/stride3d/stride/assets/62845098/3cd9b538-cf7a-4cdd-aecb-9056688719fe)

Is this what you are asking?

**Comment by IXLLEGACYIXL** [comment]
yes what is in that folder? does it contain the net8 sdk?

**Comment by Sunflair0** [comment]
![stride6c 18 24](https://github.com/stride3d/stride/assets/62845098/419b8066-9eb7-4ea8-b690-2facfb445a01)

**Comment by Sunflair0** [comment]
yes, the link you shared, I have both files.

**Comment by IXLLEGACYIXL** [comment]
you mean environment variables?
can you share your path environment variables

**Comment by Sunflair0** [comment]
as soon as you tell me what that is, I will

**Comment by IXLLEGACYIXL** [comment]
windows button => type environment => should give you program for setting environment variables and a window like that 
![grafik](https://github.com/stride3d/stride/assets/107197024/c1422848-dc97-4c0f-af2b-2a29f441fe60)

at bottom is a blue button for environment variables
![grafik](https://github.com/stride3d/stride/assets/107197024/553aba53-be93-47e4-9a10-4541395cdc17)

it should be like that if you double click on path at the systemvariables tab and it should have only one dotnet path and not a x86 one

**Comment by Sunflair0** [comment]
ok, I will do that.
Ich mag Deutsch :)

**Comment by IXLLEGACYIXL** [comment]
![grafik](https://github.com/stride3d/stride/assets/107197024/33258683-475b-43bc-a9fe-34f50aaad525)

**Comment by IXLLEGACYIXL** [comment]
screenshot would be best as always

**Comment by Sunflair0** [comment]
It's giving me a stupid BING search for it.  

I will figure it out...

**Comment by IXLLEGACYIXL** [comment]
![grafik](https://github.com/stride3d/stride/assets/107197024/d2d1f621-6888-475c-bb00-30c15e3eb999)
systemsteuerung => top right umgebung => umgebungsvariablen bearbeiten => opens a similiar window for whatever reason

**Comment by Sunflair0** [comment]
![stride6d 18 24](https://github.com/stride3d/stride/assets/62845098/d798a097-61b8-46e9-ba93-3583b184f198)

That was fun.

**Comment by Sunflair0** [comment]
![stride6e 18 24](https://github.com/stride3d/stride/assets/62845098/495235c9-5069-481b-94ee-dd86542e8ef1)

Is this more of what you want?

**Comment by IXLLEGACYIXL** [comment]
> ![stride6e 18 24](https://private-user-images.githubusercontent.com/62845098/340792636-495235c9-5069-481b-94ee-dd86542e8ef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzYxMTYsIm5iZiI6MTcxODczNTgxNiwicGF0aCI6Ii82Mjg0NTA5OC8zNDA3OTI2MzYtNDk1MjM1YzktNTA2OS00ODFiLTk0ZWUtZGQ4NjU0MmU4ZWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE4MzY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZmViNDgwNGMxNmQ2NWE0NTE2YTQ2NTg2NzhhNDIzOTYwNTM1ODMwYTM0N2I1M2E4ZTM4NTE0N2NjY2IxM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.28ui1j1Dz81LE7Ym16tHIoTjlSPeaqs3jNB1Xwc921k)
> 
> Is this more of what you want?

you double clicked on the top path, you need to double click on path in the bottom panel

**Comment by Sunflair0** [comment]
The one that starts out with Python?

**Comment by IXLLEGACYIXL** [comment]
yes, system variables, not user variables

**Comment by Sunflair0** [comment]
Not sure why it starts out with Python. It was a class I took for 2 weeks and the teacher quit so never finished. I don't code in Python. I have PyCharm on my computer.

**Comment by IXLLEGACYIXL** [comment]
![grafik](https://github.com/stride3d/stride/assets/107197024/01b8cd54-44e0-4bae-907d-ad3a15cb5ad3)
here double click on Value of path

**Comment by Sunflair0** [comment]
![stride6g 18 24](https://github.com/stride3d/stride/assets/62845098/699c096d-221e-471b-b5ce-9eabbe42d672)

I promise you all other windows are closed. I have closed the window several times on accident, and this visual is the first of me opening the window again.

**Comment by IXLLEGACYIXL** [comment]
uhhhhhhhhhhhhhh thats new 🤣 
that is maybe also the reason why the install doesnt work... 

do you have stride still open or VS ? something that may lock that thing?

maybe make a restart and go straight to that? there seems something horrible wrong there

**Comment by Sunflair0** [comment]
I will restart and go straight to the window.
Wish me more than luck

**Comment by Sunflair0** [comment]
Same.

Is there a way to browse to it or something other than this window?

**Comment by Sunflair0** [comment]
no, it's mine. I abuse it daily.

**Comment by IXLLEGACYIXL** [comment]
run in powershell `$env:PATH -split ';'`

( its very weird that you cant edit the system variables as admin )

**Comment by Sunflair0** [comment]
I agree. Is there some way I can verify I am in admin mode? I don't think that is the default.

![powershellA](https://github.com/stride3d/stride/assets/62845098/d7ad487f-c95e-41b0-9c09-027eee4aab68)
![powershellB](https://github.com/stride3d/stride/assets/62845098/13e616ca-21b7-49a8-93d6-f15f80545345)

**Comment by MeharDT** [comment]
> ![stride6g 18 24](https://private-user-images.githubusercontent.com/62845098/340796176-699c096d-221e-471b-b5ce-9eabbe42d672.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzY5ODAsIm5iZiI6MTcxODczNjY4MCwicGF0aCI6Ii82Mjg0NTA5OC8zNDA3OTYxNzYtNjk5YzA5NmQtMjIxZS00NzFiLWI1Y2UtOWVhYmJlNDJkNjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE4NTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMzJmY2Q1NDdmZGNjNWI0ZTQ0ZTg2NjlkZjQwODg2OTA2MDM5N2IzMTk3MTRhOGJiNzIyYTU4ZmU1YzQ0ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MmO8H3TC2pBsnUfDu7LVuS0qpOhvoHJyJvEjIwJar6A)
> 
> I promise you all other windows are closed. I have closed the window several times on accident, and this visual is the first of me opening the window again.

Can you try the steps here and see if it gives you Edit access?

https://superuser.com/a/1467834

**Comment by IXLLEGACYIXL** [comment]
y0,ou have exactly t0ha issue https://github.com/dotnet/sdk/issues/22508#issuecomment-963494604
 the x86 dotnet comes first and AFTER that normal dotnet comes => x32 dotnet gets called and for that you have 0 sdks
 
 you have for x64 which is in C:\Program Files\dotnet\ but its below x86 path
 
 now the mystery why you cant edit the environment variables...

**Comment by Sunflair0** [comment]
Ok, so I did the SYSTEM variable thing, and I have access now.

**Comment by Sunflair0** [comment]
How do I change it! 

I keep dreaming of the games I need to program, and I don't think I can stop the dreams until I program it.

Help free me :)

**Comment by MeharDT** [comment]
Awesome! What you'll need to do now is select

`C:\Program Files\dotnet\`

In the list, and then click "Move Up" in the right hand side until it's above

`C:\Program Files (x86)\dotnet\`

From there press Ok on the open windows and try launching Stride again.

**Comment by IXLLEGACYIXL** [comment]
and try `dotnet --list-sdks` again, mybe restart required again dont know..

**Comment by Sunflair0** [comment]
I got all excited and couldn't think and tried moving the file in the screenshot.
I am a doof.

So, no change, which means a restart and then I will do powershell again.

**Comment by IXLLEGACYIXL** [comment]
can you reopen the window and show how its currently?

**Comment by IXLLEGACYIXL** [comment]
also why is there a x86 path in there at all

**Comment by Sunflair0** [comment]
Ok, so I restarted, powershell said nothing there. So, I went back and looked at SysEnv and it was back on the bottom!!!

I changed it again, and same thing. So, I put it all the way at the top and now powershell shows stuff.

Gonna try Stride again.

**Comment by Sunflair0** [comment]
EVERY 🥇  SINGLE 🥇ONE 🥇 OF 🥇 YOU 🥇 ARE 🥇 GENIUSES.

Thank you.

**Comment by Sunflair0** [comment]
Ok, so I am gonna name something in my game after every one of you. It may be 10 years from now when you see it, but remember this moment!

I gonna go cry with happiness now.
