### ISSUE TITLE
Effect Compiler/User Settings missing in Project property grid in the editor

### ISSUE THREAD

**Issue by Basewq** [stride3d/stride#2347]
**Release Type**: Official Release

**Version**: 4.2.0.2122

**Platform(s)**: Windows & Android

**Describe the bug**
Project's 'User Settings' not appearing in the Property grid, which contained the Effect Compiler setting.

In Stride 4.1.01948:
![image](https://github.com/stride3d/stride/assets/1356956/e031b328-2a2a-457b-8ba2-7a84a21817aa)

In Stride 4.2.0.2122:
![image](https://github.com/stride3d/stride/assets/1356956/4f74df80-9aa6-4aba-b254-432719c62f60)

**To Reproduce**
1. Create 'My game' project in 4.1.01948 & 4.2.0.2122
2. Select the MyGame.Windows project in the editor
3. Look at the Property grid window

**Expected behavior**
See the User Settings.

**Additional context**
Settings are stored in the `MyGame.Windows.sdpkg.user` file.
When settings changed, file will change, eg.
```
!SettingsFile
Settings:
    Package/Game/Effect/EffectCompilation: LocalOrRemote
```
Find out why it's not appearing.

**Comment by tebjan** [comment]
Happened to me again, seems to be an issue still.

**Comment by tebjan** [comment]
Nevermind, it works. The platform-specific project, e.g. MyGame.Windows needs to be selected.
