### ISSUE TITLE
Will using C# attributes to optimize code submissions be accepted?

### ISSUE THREAD

**Issue by Arc-huangjingtong** [stride3d/stride#2365]
# Question and/or Comment

Will using C# attributes to optimize code submissions be accepted?

like
```
  if (fun == null)
  {
      fun.Invoke();
  }
```
be
```
fun?.Invoke();
```

**Comment by Eideren** [comment]
Not exactly sure I understand the question.

I'm guessing you meant;
```cs
if (fun != null)
{
    fun.Invoke();
}
```
For the first snippet.

If this question is about whether we would accept PRs which only contain code style changes, like you've shown above, not really ... we would rather your PR introduce at least a new feature, improve performance or fix a bug, if that's the case you may introduce change in style if they don't go against the style of the rest of the code base.

Reviewing style changes is very time consuming and if the PR doesn't do anything besides that it's often not worth the effort.

Let me know if I misinterpreted the question !

**Comment by Arc-huangjingtong** [comment]
Sorry，my english is not good ，but the word ‘like’ is ‘as sth be sth’ ， In short，I understand your mean。
if i use Span<T> replace old code to reduce GC,Is that okay? or use other High level C# Feature to improve Performance or ReFactory Code to reduce code line num?Is that okay?

**Comment by Eideren** [comment]
> if i use Span replace old code to reduce GC,Is that okay? or use other High level C# Feature to improve Performance
Yep, very much welcome
> ReFactory Code to reduce code line num?Is that okay?
Just reducing the amount of lines, not really, but if you reduce the amount of lines while fixing a bug or while improving performance, yes.

**Comment by Arc-huangjingtong** [comment]
Thank You!

**Comment by NicusorN5** [comment]
Condider closing this thread @Arc-huangjingtong ?

**Comment by Ethereal77** [comment]
I didn't notice this was an issue. Why are there issues labeled as `question` if we have the Discussions tab in GitHub?

**Comment by Arc-huangjingtong** [comment]
![image](https://github.com/stride3d/stride/assets/87562566/7776b806-ea2c-48d0-913b-e8ee469bcc77)

**Comment by Ethereal77** [comment]
Well, then we should remove that and point users towards Discussions for questions and comments.

**Comment by VaclavElias** [comment]
Probably it was there historically. We can easily convert any issue to a discussion. Also, I can change that button to behave like the below, just links, so it could be just a link to Discussion.

![image](https://github.com/stride3d/stride/assets/4528464/c15b69d9-dce6-4a23-877d-358ec7d99ab6)

![image](https://github.com/stride3d/stride/assets/4528464/63c697a9-803e-414c-8483-13e5d3a36c17)
