### ISSUE TITLE
When importing models with multiple materials, only the first is included

### ISSUE THREAD

**Issue by MechWarrior99** [stride3d/stride#2433]
**Release Type**: Official Release

**Version**: 4.2.0.2188

**Platform(s)**: Game Studio

**Describe the bug**
When importing a FBX or GLTF model with multiple materials. Only one material slot is imported.

**To Reproduce**
1. Get or create a model in the FBX format (or GLTF?) with 2 or more materials in it. 
2. Drag and drop the asset from the file explorer in to the Asset View window in Stide Game Studio
3. Select "3D model" in the popup.
4. Agree to copy source file.
5. In the import dialog window, check all options.
6. See only a single material.

**Expected behavior**
All materials and material slots from the imported model would be included.

**Screenshots**
![image](https://github.com/user-attachments/assets/95c745a2-e463-471b-9f62-0f7424c34dc8)
![image](https://github.com/user-attachments/assets/64e5a0aa-824d-4d2b-b7c2-390c7d3690f4)

**Log and callstacks**

**Additional context**
This was working in a earlier 4.2 version, though I am not sure which one specifically at this point.

**Comment by MechWarrior99** [comment]
So I looked in to this issue a bit, it seems like it is an issue with the new assimp library itself or the way it is utalized possibly, because the `MNumMaterials` property on the imported Assimp `Scene` is `1`. Even when the actual file has multiple materials.
Also, I check versions and it is working in 4.2.0.1, but not working in 4.2.0.2188. So somewhere in there it broke.

**Comment by MechWarrior99** [comment]
So after more testing I realized that the assets I tested with, while they did have different materials, none of their settings had been changed, so they were identical. So the deduplicate setting is in fact working. The critira it uses for determining what materials to remove is just different now (probably more accurate I would say).

**Comment by VaclavElias** [comment]
It would be nice to have some Blender guide in our manual, wouldn't be?

**Comment by Doprez** [comment]
> It would be nice to have some Blender guide in our manual, wouldn't be?

Agreed, I tagged this issue in the other blender discussion https://github.com/stride3d/stride/discussions/2414
