### ISSUE TITLE
Update Stride Doesn't Run [Docs] 

### ISSUE THREAD

**Issue by Gurrman375** [stride3d/stride#2471]
**Describe the update or improvement you would like to see**
An update to issues with this article [Stride Doesn't Run](https://doc.stride3d.net/latest/en/manual/troubleshooting/stride-doesnt-run.html)

**Is this related to a specific part of the documentation?**
This is related to the section **.NET SDK 8.0**.

**Why is this update needed?**
I had issues installing Stride3d for a few hours because it was unclear .Net SDK was installed. I spent a while looking for a solution and found the image below. If this is updated, it can help developers troubleshoot the issue further.

**Additional context**
![image](https://github.com/user-attachments/assets/06f1d845-b276-455c-8bf1-bd1438c0c80c)

**Proposed changes**
Either add the above image or add in to download the binary if the SDK files are not found.

**Comment by Kryptos-FR** [comment]
Installing the SDK manually is a bad idea and we shouldn't recommend it. If using the .MSI installers doesn't work, then something big is broken on the user machine and it is beyond our scope to diagnose it.

I would certainly not link to a SO article while there is already comprehensive documentation on how to install the SDK. https://learn.microsoft.com/en-us/dotnet/core/install/windows

**Comment by Gurrman375** [comment]
Was unaware that that was a problem. I'll close this then.
