### ISSUE TITLE
[Shaders] ByteAddressBuffer not parsed correctly

### ISSUE THREAD

**Issue by tebjan** [stride3d/stride#248]
**Release Type**: Official Release/GitHub (please choose appropriate option)
official

**Version**: Version number and/or git branch
3.0.0.6

**Platform(s)**: 
windows d3d11

**Describe the bug**
the generated c# shader keys are wrong 

**To Reproduce**
add a ByteAddressBuffer shader variable in xksl

**Expected behavior**
no error in visual studio and a c# shader object key of type buffer

**Screenshots**
![image](https://user-images.githubusercontent.com/1094716/47670596-dee25480-dbad-11e8-96a4-924f525d8321.png)
![image](https://user-images.githubusercontent.com/1094716/47670507-a5a9e480-dbad-11e8-9ae6-bac33482c34b.png)

**Log and callstacks**
Error	CS0246	The type or namespace name 'ByteAddressBuffer' could not be found (are you missing a using directive or an assembly reference?)	CoNature.Game	C:\vvvv\PROJECTS\2018\11_MLF_CoN\CoNature\CoNature\CoNature.Game\Shaders\Utils_CalcDispatchArgs.cs	23	N/A

**Comment by xen2** [comment]
The code to fix is likely located in `ShaderKeyGeneratorBase.cs`
