### ISSUE TITLE
[Direct3D] GraphicsOutput.CurrentDisplayMode from GraphicsOutput.Direct3D.cs contains wrong information about current resolution and/or refresh rate

### ISSUE THREAD

**Issue by Feralnex** [stride3d/stride#2492]
**Release Type**: Official Release

**Version**: v4.2.0.2232

**Platform(s)**: Windows

**Describe the bug**
If You have scaling applied on Windows in display settings then when referencing e.g. GraphicsDevice.Adapter.Outputs[0].CurrentDisplayMode (any first monitor/display connected to the PC) You might get resolution of the display (output) after scale was applied. If You turn off/on monitor or force saving mode and wake it then You might get proper resolution in CurrentDisplayMode, but it's possible to do that "workaround" on my machine, it might not work for the others.

The refresh rate is even funnier, we just get first RefreshRate from SupportedDisplayModes which matches current output resolution (which can be a scaled resolution on Windows). The source code from the repo:

```cs
/// <summary>
/// Tries to find a display mode that has the same size as the current <see cref="OutputDescription"/> associated with this instance
/// of the specified format.
/// </summary>
/// <param name="format">The format to match with.</param>
/// <returns>A matched <see cref="DisplayMode"/> or null if nothing is found.</returns>
private DisplayMode TryFindMatchingDisplayMode(Format format)
{
    var desktopBounds = outputDescription.DesktopBounds;

    foreach (var supportedDisplayMode in SupportedDisplayModes)
    {
        var width = desktopBounds.Right - desktopBounds.Left;
        var height = desktopBounds.Bottom - desktopBounds.Top;

        if (supportedDisplayMode.Width == width
            && supportedDisplayMode.Height == height
            && (Format)supportedDisplayMode.Format == format)
        {
            // Stupid DXGI, there is no way to get the DXGI.Format, nor the refresh rate.
            return new DisplayMode((PixelFormat)format, width, height, supportedDisplayMode.RefreshRate);
        }
    }

    return null;
}
```

**To Reproduce**
1. Create project on Windows platform
2. Access GraphicsDevice.Adapter.Outputs[0].CurrentDisplayMode (any first monitor connected to the PC)
3. If You have scaling for that display applied You might get wrong resolution information and/or refresh rate (refresh rate is hit or miss - depends if the first SupportedDisplayMode with matching resolution will have the same RefreshRate as Your monitor currently uses)

**Expected behavior**
GraphicsOutput.CurrentDisplayMode should have actual Resolution (Width/Height) and RefreshRate taken from the Output (monitor/display).

**Screenshots**
Sorry about Windows settings in Polish instead of English, but it shouldn't be a problem to notice resolution and refresh rate:

![Image](https://github.com/user-attachments/assets/d9c6c755-8d2f-4d86-a457-9dc5e6d8a9c3)
![Image](https://github.com/user-attachments/assets/ad35f188-ae9c-409c-b573-f0dbe39550c7)

**Additional context**
Fix is on the way, I've created this issue for further reference.

**Comment by Doprez** [comment]
It may be useful to note if you test separate rendering backends, the `Outputs` property was broken. This may be useful to note when the PR gets reviewed or tested.

https://github.com/stride3d/stride/issues/2411

**Comment by Feralnex** [comment]
> It may be useful to note if you test separate rendering backends, the `Outputs` property was broken.
> 
> [#2411](https://github.com/stride3d/stride/issues/2411)

Unfortunately GraphicsOutput.OpenGL implementation is severely missing:

```cs
#if STRIDE_GRAPHICS_API_OPENGL

using System;

namespace Stride.Graphics
{
    public partial class GraphicsOutput
    {
        public DisplayMode FindClosestMatchingDisplayMode(GraphicsProfile[] targetProfiles, DisplayMode mode)
        {
            return mode;
        }

        public IntPtr MonitorHandle
        {
            get { return IntPtr.Zero; }
        }

        private void InitializeSupportedDisplayModes()
        {
        }

        private void InitializeCurrentDisplayMode()
        {
            currentDisplayMode = null;
        }
    }
}
#endif
```

No wonder You've got empty Output handle...

**Comment by Doprez** [comment]
lol well at least thats easily explained. Definitely not the only thing that needs some love in OpenGL but that may give me a very easy starting point to look at in the future so thank you!
