### ISSUE TITLE
EffectCompile Error: XenkoForwardShadingEffect.ShadowMapCaster and XenkoForwardShadingEffect.ShadowMapCaster are both writing bytecode at the same time

### ISSUE THREAD

**Issue by ghost** [stride3d/stride#25]
I don't think this is a new issue with v3 as I had a problem in v2 that could only be solved with the same solution. I am just getting much more information in v3 to report.

I am moving over a flowing water demo to v3 that I was going to share with the forums but I get the attached [asset shader errors.txt](https://github.com/xenko3d/xenko/files/2258033/asset.shader.errors.txt) when the build is run. The only way to get past it is to kill the process Xenko.Core.Assets.CompilerApp_ExecServer.exe.

In v2 I had an error with no other details, but killing the old equivalent SiliconStudie-named exe was the solution. It does not always happen, but once it does, it will happen every time and even re-starting my PC does not seem to fix it. Then randomly it will stop for a while. Almost seems like it's running two compilers once I do something it does not like>?

The shader being compiled is [ScriptedWaterShader.txt](https://github.com/xenko3d/xenko/files/2258042/ScriptedWaterShader.txt) (with extension changes to .txt for GitHub, it's .xksl in my project).

**Comment by TomGroner** [comment]
When running the compile, I can see the compiler exe start, go away, re-start and stay. The one that stays is the one that I have to kill. After it's killed, I will see it start, go away, and stay away. Then the following run it will repeat.

**Comment by TomGroner** [comment]
This is actually occurring every time from within Xenko Studio. When running from Visual Studio, I get the back and forth effect.

**Comment by Refsa** [comment]
Xenko.EffectCompilerServer

**Comment by TomGroner** [comment]
The full project that I am experiencing this issue with can be found here: https://github.com/TomGroner/XenkoFlowingWater

**Comment by TomGroner** [comment]
@xen2 A bit more info. I started working on a new project and the shader compiler was working just fine. However as soon as I had my shader inherit from PositionVertexTransform I began getting this issue in the second project. When I stopped inheriting from PositionVertexTransform, the problem went away.

**Comment by TomGroner** [comment]
One last thing and I might try to investigate this and fix myself, but it might be over my head: Only when you both inherit from PositionVertexTransform in a shader, and then the shader is applied to a material with a MaterialTransparencyBlendFeature, does this seem to happen.

**Comment by Eideren** [comment]
Looks like this is #937 , I'll close this one instead to avoid pinging the 6 participants in the other one.
