### ISSUE TITLE
Click around in Top-Down RPG. Console window comes up with [RouterClient]: Error: Could not connect to connection router using mode Connect. 

### ISSUE THREAD

**Issue by PeaceSells50** [stride3d/stride#254]
3.0.0.7-dev, master branch, compiled from GitHub source

Windows 10

Console window comes up and 
[RouterClient]: Error: Could not connect to connection router using mode Connect. Xenko.Engine.Network.SimpleSocketException: Connection router did not connect back to our listen socket
   at Xenko.Engine.Network.RouterClient.<InitiateConnectionToRouter>d__5.MoveNext()
Xenko.Engine.Network.SimpleSocketException: Connection router did not connect back to our listen socket
   at Xenko.Engine.Network.RouterClient.<InitiateConnectionToRouter>d__5.MoveNext()

1. Create project from template Top-Down RPG.

2. Click around. After around a minute or 2 the console window comes up with error in it.

**Comment by xen2** [comment]
This happen because by default the game is in "dev build" and tries to connect back to game studio to send some info about shader usage.
This can be ignored, and this feature completely disabled for release game (in package properties).

**Comment by Eideren** [comment]
This issue won't show up by default now, see #639 .
