### ISSUE TITLE
[Editor] Asset grid view has old color scheme

### ISSUE THREAD

**Issue by tebjan** [stride3d/stride#263]
**Release Type**: 
official

**Version**: Version number and/or git branch
3.0.0.6

**Describe the bug**
when switching to grid view in asset view the colors are not correct

**Expected behavior**
same color scheme as rest of the editor

**Screenshots**
![image](https://user-images.githubusercontent.com/1094716/48367192-3acdd280-e6b0-11e8-8990-79af9660dd08.png)

ping @0xaryan, do you have any idea? is this an easy fix?

**Comment by xwellingtonx** [comment]
@tebjan It is just to change the style of XAML elements with new dark theme implemented with Xenko 3.x.

**Comment by 0xaryan** [comment]
> ping @0xaryan, do you have any idea? is this an easy fix?

Sorry that I forgot to change the resource for the Grid View colors in the details mode.
Yup I think that's quite easy to do as I remember. I would do that myself If I wasn't busy. I've already changed the color resource for the default view. You can find the other one's color resouces in the grid view's template and change it to the default one.

**Comment by tebjan** [comment]
sounds easy, but how do i do that? is there a global color theme that i can apply?

**Comment by Eideren** [comment]
Closing this as the asset grid view was removed through #601
