### ISSUE TITLE
drive path errors and model materials

### ISSUE THREAD

**Issue by nullwanton** [stride3d/stride#269]
**Release Type**: Official Release/GitHub Official Release

**Version**: 3.0.0.6

**Platform(s)**: Windows

**Describe the bug**
No materials are found when importing an asset, nor can you save a project, there are errors in all file paths not containing a drive letter or .\

**To Reproduce**
1. create a new project
2. import a .obj model,

**Expected behavior**
1. use the save toolbar button or file menu and the project won't save, and give path errors, the ony way the project will save, is to use the build and run toolbar button
2. no materials will be found, the image path will start with map\, after manually selecting the image file the material will be shown on the model in the preview window and the image path will start with a drive letter and will be using the full path, if the model has been exported using daz3d

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)

**Additional context**

**Comment by Eideren** [comment]
Importing .obj works fine. We'll need more information to figure out what's wrong, like the path your project and xenko/stride resides at. This is probably just one of the issues we had when transitioning to nuget so I'll just close this one off
