### ISSUE TITLE
doc page : use a script needs updating

### ISSUE THREAD

**Issue by nullwanton** [stride3d/stride#271]
Release Type: Official Release

Version: 3.0.0.6

https://doc.xenko.com/latest/en/manual/scripts/use-a-script.html

there is'nt a charectorscript or script in the entity property grid +add componment droplist, which then stops siomeone adding custom animations to custom models, as there is'nt a controller, unless everything todo with adding scripts to control animations is all out of date

so you import a model from a .fbx, and then import the animation separately, through assets, then create an animation script, and that as far as you can get

**Comment by Kryptos-FR** [comment]
The image with in the documentation is an illustration of what users might find in the drop down to add a component.
There is actually a `CharacterScript` that can be added as an asset in the asset view.

Only the scripts that are added to the solution are shown in the drop down list.

@xen2 could you move that issue to the xenko3d/xenko-docs repository.

**Comment by nullwanton** [comment]
there is'nt a CharacterScript under asset view +Add asset/script

**Comment by Eideren** [comment]
Closing this as nonsensical and off topic.
