### ISSUE TITLE
When I want to download this game engine for windows.

### ISSUE THREAD

**Issue by HCricle** [stride3d/stride#279]
In windows 10,i can not to download this game engine.It show service can not to connect.

**Comment by tebjan** [comment]
did you allow the launcher to connect to the internet on first start? any firewall active?

**Comment by bluesaka111** [comment]
In my case there no connection request that pop up. And when I search in incoming bound rules (Firewall advanced settings) there no setup rule to tell Firewall to allow Xenko incoming data at all.

**Comment by bluesaka111** [comment]
I guess the launcher lack permissions to download packages. Maybe I will test out on virtual machine to see how it turn out.

**Comment by Eideren** [comment]
Works fine on a VM. Closing this one off as it probably was linked to the many other issues we had with nugget. Feel free to open a new issue if you still have the same one though.
