### ISSUE TITLE
[Asset] Handle assets containing multiple animations per file

### ISSUE THREAD

**Issue by herocrab** [stride3d/stride#328]
**Release Type**: Official Release

**Version**: 3.0

**Platform(s)**: Windows (In Game Studio)

**Describe the bug**
Xenko Game Studio does not currently allow importing multiple animations for .blender and .fbx files. They have to be imported one by one. Game Studio could be modified to ask the user which animation to import or recursively import them all separately.

**Workaround**
To highlight the workaround: You can still get around this by exporting animations one by one and importing into Xenko, they will use the same model and skeleton and you can crossfade/blend to them with no issue.

**To Reproduce**
1. Try to import the attached model/animations. Only the first/default animation is imported.

**Expected behavior**
Either:
1) All animations would be imported separately.
2) Xenko would ask which animation would be imported through a drop down box.

**Additional context**
This is labor intensive for adding many character animations.

**Attached files**
[BaseMesh_Anim.fbx.zip](https://github.com/xenko3d/xenko/files/2774983/BaseMesh_Anim.fbx.zip)

Eideren: conciseness, removed template text

**Comment by tebjan** [comment]
For now you can use this script to save all animations into separate files: https://github.com/GutterLab/BlenderToXenkoAnimationSeparator

**Comment by VaclavElias** [comment]
Just adding a bounty link https://opencollective.com/stride3d/projects/multiple-animations-per-model

**Comment by Eideren** [comment]
This has been fixed through #2163
