### ISSUE TITLE
Geometry Instancing

### ISSUE THREAD

**Issue by GutterLab** [stride3d/stride#340]
**Is your feature request related to a problem? Please describe.**
Being able to draw a lot of the same thing while staying performant.

**Describe the solution you'd like**
Support for geometry instancing.

**Additional context**
https://en.wikipedia.org/wiki/Geometry_instancing

**Comment by xen2** [comment]
@tebjan Fine with doing that at first.
I think the main other concern was how to gather instances (should we find duplicate draw call automatically or have an explicit way to describe those?)

**Comment by yangguosdxl** [comment]
Maybe automatically gather instances not very emergency。this can do by game logic. Generally, may be we just want a method to commit geometry instancing :-)

**Comment by Eideren** [comment]
Should we close this issue ? @tebjan
