### ISSUE TITLE
Input.LockMousePosition exits window if mouse moved too quickly

### ISSUE THREAD

**Issue by CPogolski** [stride3d/stride#345]
**Release Type**: Official Release

**Version**: 3.1.0.1-beta01-0406

**Platform(s)**: Windows 10 Pro Build 17134

**Describe the bug**
When `Input.LockMousePosition` is used to lock the mouse cursor to the window, it exits the window despite its setting if the mouse is moved too quickly. This occurs on `forceCenter=true` and `forceCenter=false`.

**To Reproduce**
1. Use Third-Person Sample
2. Launch Game
3. Move mouse quick enough (Using a 6000 DPI Mouse, but not on Max. settings, so it should occur on slower ones, too.)

**Expected behavior**
Mouse-Cursor should never leave the window.

**Additional Information**
- Using a Tripple 2160p Monitor Setup
- Game launched via Xenko Editor AND Visual Studio 2017 Enterprise
- Tested in Window and Fullscreen

**Comment by SleepyMode** [comment]
Input.LockMousePosition appears to work differently with multiple implementations.

- https://github.com/xenko3d/xenko/blob/951335d9d421889a7459130f3e68436c62d8a02c/sources/engine/Xenko.Input/Simulated/MouseSimulated.cs#L76
- https://github.com/xenko3d/xenko/blob/b40e7ad0800ec658f6107bc92071d20cb6e8e800/sources/engine/Xenko.Input/Windows/MouseWinforms.cs#L77
- https://github.com/xenko3d/xenko/blob/28245aff55cea3ceacaef2ea3902657cd06f81b6/sources/engine/Xenko.Input/SDL/MouseSDL.cs#L53
- https://github.com/xenko3d/xenko/blob/951335d9d421889a7459130f3e68436c62d8a02c/sources/engine/Xenko.Input/UWP/MouseUWP.cs#L94



I wonder if the issue occurs with all of the implementations.

**Comment by Zeroto** [comment]
Some relevant research:
https://docs.microsoft.com/en-us/windows/win32/dxtecharts/taking-advantage-of-high-dpi-mouse-movement
https://wiki.libsdl.org/SDL_SetRelativeMouseMode
https://docs.microsoft.com/en-us/windows/uwp/gaming/relative-mouse-movement

How often do people want to lock the mouse and have it visible? The solutions in the SDL and UWP links will hide the cursor automatically(and I don't think that could be disabled).

For winforms it would require using raw input. But this also has the benefit of working with high dpi mice. With the current implementation the minimum delta is 1 pixel I believe. When using raw input this would allow for more precise movements.

I do think that we should still use the normal absolute input when the cursor is not locked. That way the cursor operates the same as it would in the operating system.

**Comment by Zeroto** [comment]
I'm currently fixing/adding support for this and already have it working for SDL and UWP: https://github.com/Zeroto/stride/tree/345-MouseLock

However, when looking at implementing it for winforms I have a question. It looks like it already has support for raw input using sharpdx, but only when using the .net framework and not when targeting .net core. Is there a specific reason why this is the case? I see it was added in the following commit( https://github.com/stride3d/stride/commit/341d6b0cde01a765237dbf720e690643211c0e81 ) but that commit doesn't explain why this was done.

**Comment by Eideren** [comment]
Nice, thanks a bunch !
There might be netfw-specific logic in there, not sure, you could try to remove that and see how the engine fares while @xen2 gets back to you.
