### ISSUE TITLE
Xenko.SpriteStudio.Runtime missing

### ISSUE THREAD

**Issue by gattila** [stride3d/stride#366]
Release Type: Official beta

Version: 3.1

Platform: Windows 10

Bug:
When I tired to execute the SpriteStudio demo, it failed with runtime exception:
An unhandled exception of type 'Xenko.Core.Serialization.Contents.ContentManagerException' occurred in Xenko.Games.dll
Unexpected exception while loading asset [SpriteEntityScene]. Reason: Could not load file or assembly 'Xenko.SpriteStudio.Runtime, Version=3.1.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.. Check inner-exception for details.

I tired to add a similar nuget package from VS, but I didn't found.

**Comment by Kryptos-FR** [comment]
You mean that package?
https://www.nuget.org/packages/Xenko.SpriteStudio.Runtime/3.1.0.1-beta01-0430

**Comment by gattila** [comment]
Yes, thank you I forgot to check the "Include Prelease" checkbox in the nuget package. But IMHO in can be useful if anybody add this package to the project templatge.

**Comment by Eideren** [comment]
This has been fixed through one of the many nuget changes.
