### ISSUE TITLE
Creating any ColliderShape before a PhysicsComponent has been created results in an exception

### ISSUE THREAD

**Issue by profan** [stride3d/stride#368]
**Release Type**: Official Release

**Version**: 3.1.01-beta01-0430

**Platform(s)**: Windows

**Describe the bug**
Creating any kind of ColliderShape, like a ConeColliderShape will currently result in an exception related to libbulletc not being loaded (if done before a PhysicsComponent has been created).

**To Reproduce**
1.  In any project before a **PhysicsComponent** has been created, create a shape like so: 
```cs
var newShape = new ConeColliderShape(32, 32, ShapeOrientation.UpX);
```

**Screenshots**
![image](https://user-images.githubusercontent.com/2816340/52323102-067e5f80-29dc-11e9-8f93-3a176c1e5cf8.png)

**Additional context**
Currently, you can work around the problem by making sure some kind of PhysicsComponent is created before any ColliderShape, because of this:

> https://github.com/xenko3d/xenko/blob/5f596657e006bfea9ebbf0f04302df5e3f3aed85/sources/engine/Xenko.Physics/Engine/PhysicsComponent.cs#L27-L31

**Comment by profan** [comment]
@xen2 I just had a go at trying to reproduce this and came up with nothing btw.. Which is strange, did something change about this since last?

**Comment by Eideren** [comment]
Was able to reproduce it by forcing the repro line to execute before running the game. If you want to tackle this issue see xen2's comment above https://github.com/stride3d/stride/issues/368#issuecomment-460913875
