### ISSUE TITLE
Instalation Problems

### ISSUE THREAD

**Issue by meine31** [stride3d/stride#380]
# Question and/or Comment

An error occurred while installing version 3.0.0.8.
Failed to download package 'Xenko.3.0.0.8' from 'https://packages.xenko.com/api/v2/package/xenko/3.0.0.8'.
Unable to read data from the transport connection: Une connexion existante a dû être fermée par l’hôte distant.
 Une connexion existante a dû être fermée par l’hôte distant
Unable to find package 'Xenko.3.0.0.8'. at NuGet.Protocol.FindPackagesByIdNupkgDownloader.<GetNuspecReaderFromNupkgAsync>d6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.RemoteV2FindPackageByIdResource.<GetDependencyInfoAsync>d18.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesCoreAsync>d22.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<>cDisplayClass21_0.<<GetDependenciesAsync>b0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesAsync>d21.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.DependencyResolver.ResolverUtility.<CreateGraphItemAsync>d2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.DependencyResolver.ResolverUtility.<FindLibraryEntryAsync>d1.MoveNext()

**Comment by phr00t** [comment]
Can you try using my different Xenko distribution method?

https://github.com/phr00t/xenko/releases/tag/3.1b-R1

Please mention me with results if you try it!

**Comment by Kryptos-FR** [comment]
Xenko packages are published on nuget now. That old address is not valid anymore, as far as I know. @xen2  do you confirm?

**Comment by Eideren** [comment]
The given address works as expected but that version is out of date anyway, I'll close this off.
