### ISSUE TITLE
FileNotFoundException() Error in OpenStreamForRead in ObjectDatabase.cs when loading project created from TopDownRPG template.

### ISSUE THREAD

**Issue by antonyjones67** [stride3d/stride#384]
**Release Type**: Official Release/GitHub (please choose appropriate option)
Debug - Hash f56d4f836098f0c9fd5a39eeebffa2d7ed59a179

**Version**: Version number and/or git branch
Master Branch

**Platform(s)**: Does the problem occur on Windows, Android...?
Windows

**Describe the bug**
FileNotFoundException() Error in OpenStreamForRead in ObjectDatabase.cs when loading project created from TopDownRPG template.

**To Reproduce**
1. Create a project from TopDownRPG template
2. Load in Editor
3. Close.
4. Open project created from TopDownRPG template in Editor

**Expected behavior**

**Screenshots**
![crash](https://user-images.githubusercontent.com/3905646/52920981-96bb7f00-32cf-11e9-971c-fd0d1359ffb5.png)

**Log and callstacks**
[callstack.txt](https://github.com/xenko3d/xenko/files/2873524/callstack.txt)

**Additional context**

**Comment by antonyjones67** [comment]
This is really strange. It has something to do with NavMesh. Going back to 5470299 does not help. I am currently unable to launch the Xenko editor. :(

**Comment by xen2** [comment]
It looks like the exception should be caught:
https://github.com/xenko3d/xenko/blob/releases/3.0.0.6/sources/engine/Xenko.Assets/Navigation/NavigationMeshAssetCompiler.cs#L205

You can probably continue and there might be another exception/issue later?

**Comment by antonyjones67** [comment]
Yes. I push through but when I click on the dialog above. There seems to be a focus issue and the dialog and editor start to flicker incredibly. And I cannot close the dialog.

**Comment by xen2** [comment]
Maybe it's stuck in some kind of loop somewhere?
If you pause process in debugger when it is in this flicker/hanging state, can you check in the Debugging Threads windows? (available in `Debug menu >Windows > Threads`
![image](https://user-images.githubusercontent.com/527565/52986719-e28b3700-343b-11e9-97d4-6ad1562aba6c.png)
Then you can copy paste its content here, like this in my example case:
```
Not Flagged	>	25776	1	Worker Thread	Main thread	WindowsBase.dll!MS.Win32.UnsafeNativeMethods.GetMessageW
Not Flagged		26340	3	Worker Thread	MetricThreadSender	System.dll!System.Collections.Concurrent.BlockingCollection<System.Action>.TryTakeWithNoTimeValidation
Not Flagged		26608	0	Worker Thread	<No Name>	
Not Flagged		26732	35	Worker Thread	ProtocolHandler.SendThread	Microsoft.VisualStudio.DesignTools.WpfTap.dll!Microsoft.VisualStudio.DesignTools.WpfTap.Networking.ProtocolHandler.SendThread
Not Flagged		25668	36	Worker Thread	ProtocolHandler.ReadThread	Microsoft.VisualStudio.DesignTools.WpfTap.dll!Microsoft.VisualStudio.DesignTools.WpfTap.Networking.AnonymousPipe.WaitForCondition
Not Flagged		25368	42	Worker Thread	<No Name>	System.dll!System.Net.TimerThread.ThreadProc
Not Flagged		24164	43	Worker Thread	<No Name>	
Not Flagged		24652	0	Worker Thread	<No Name>	
```

**Comment by antonyjones67** [comment]
Here is the thread window.

![image](https://user-images.githubusercontent.com/3905646/52991418-dfeff980-33c9-11e9-93ac-a302648e4dea.png)

Here is the callstack.

[callstack.txt](https://github.com/xenko3d/xenko/files/2878368/callstack.txt)

**Comment by xen2** [comment]
Is it already stuck at this point?
It looks like it is still building shaders/assets.
Could it be just that the main window is hidden on another screen or something like that?

**Comment by Kryptos-FR** [comment]
Looks like (from the stacktrace) that it is run from Visual Studio with the XAML debugging enabled. XAML debugging slows down a lot the execution of Wpf application so I would recommend to disable it.

That's something we should add in our documentation for developers/contributors.

**Comment by xen2** [comment]
It could even be that XAML live UI debugging is the responsible for this window blinking behavior (I had sometimes weird stuff happening when using it)

**Comment by antonyjones67** [comment]
Oh my goodness, the live debugging was the problem. Lol. I didn't see that coming. This is kind of a bummer because the Xaml Live Tools were kind of useful. Thank you guys! :)

**Comment by xen2** [comment]
Issue can be closed then?

**Comment by antonyjones67** [comment]
I think after understanding all the factors involved. This was actually 3 different problems. The one that was most important to me is a problem with XAML Live Tools . The original error, the exception, is still there, but  we can push through it. Definitely not a high priority. The third thing could be the warnings in the Open Session dialog above. I am happy with just being able to run again. Thank you.

**Comment by Kryptos-FR** [comment]
@xen2 let's add that somewhere in the doc about building/debugging from the sources.

**Comment by Eideren** [comment]
Could not repro the main issue on latest, most likely fixed by now. Closing this one off but feel free to open a new one with more info if you still have it.
