### ISSUE TITLE
Physics debug model is located at incorrect position when RootScene's Offset is not 0

### ISSUE THREAD

**Issue by EternalTamago** [stride3d/stride#394]
**Release Type**: Official Release

**Version**: 3.0.0.8 / 3.1.0.1-beta01-0441

**Platform(s)**: Windows

**Describe the bug**

**To Reproduce**
1. Create new game project.
2. Add a StaticColliderComponent to the Sphere entity and add a sphere collider to it.
3. Set MainScene.Offset to X=5 Y=0 Z=0.
4. Add DebugPhysicsShapes asset and add it to the Sphere entity.
5. Run the game and press Ctrl + Shift + P to enable debug rendering.

**Expected behavior**
The physics debug model is located at the same position as SphereColliderShape.

**Screenshots**
![image](https://user-images.githubusercontent.com/13661631/53298481-203ff380-3872-11e9-8a17-161a734f0a03.png)

**Log and callstacks**

**Additional context**

**Comment by wrshield** [comment]
Hello, is anyone currently working on this issue? If not, I'd like to try working on it.
Thanks

**Comment by Doprez** [comment]
No one should be looking into this currently, if you want to give it a go please do! If you have any questions feel free to hop in Discord if no one is available here I find most are active in Discord these days.

@Aggror tagging you in case there is anything to say someone is looking into this like was done for the VR task. I assume that was just due to the bounty that it had though.

**Comment by wrshield** [comment]
This one may actually be solved already, I was not able to reproduce the behavior.  I'll leave it to you all to determine.  :)

**Comment by Doprez** [comment]
sweet, Ill test it tomorrow and see if we can close it. Always nice to clean these old issues. 

If you want another issue to look into I think https://github.com/stride3d/stride/issues/2236 should be fairly simple to get started. Seems like it just initializes with a NaN value.

**Comment by wrshield** [comment]
Thanks I'll check out that one.

**Comment by Doprez** [comment]
@Eideren I think this issue can be closed. I cant seem to recreate it in the latest release.
