### ISSUE TITLE
Launcher v3.0.3 Update Error

### ISSUE THREAD

**Issue by e102em** [stride3d/stride#429]
**Release Type**: Official Release/GitHub (please choose appropriate option)

*Version: v3.0.3 

*Platform: Windows

This version will not update to the latest version. (Tried running as admin and ran with firewall setting off in case there was any connection issues).

Reproduce (Unknown)

Did try reinstalling xenko at the main website.
 [Screenshot](https://imgur.com/F9nsLKR)

**Comment by phr00t** [comment]
Can you try using my different Xenko distribution method?

https://github.com/phr00t/xenko/releases/tag/3.1b-R1

Please mention me with results if you try it!

**Comment by Eideren** [comment]
Lacks detail, issue either fixed or out of date given the changes nuget has gone through, I'll close this off.
