### ISSUE TITLE
SDL AllowUserResizing doesn't work

### ISSUE THREAD

**Issue by phr00t** [stride3d/stride#430]
**Release Type**: GitHub

**Version**: 3.1

**Platform(s)**: Windows 10 x64

**Describe the bug**
Setting Game.Window.AllowUserResizing to "true" should make the window able to be resized... but it seems to have no effect. The window appears to be locked when using SDL.

**To Reproduce**
1. Open or create any project
2. Set Game.Window.AllowUserResizing to "true"
3. Try to resize the window! You can't :-(

**Expected behavior**
Able to resize the window.

**Comment by Eideren** [comment]
https://github.com/xenko3d/xenko/blob/0029ebee92db0458b69e1d3cb3b58126aaff335a/sources/engine/Xenko.Graphics/SDL/Window.cs#L390

**Comment by phr00t** [comment]
https://wiki.libsdl.org/SDL_SetWindowResizable

**Comment by phr00t** [comment]
Fixed in my fork: https://github.com/phr00t/xenko/commit/c668b2203163122a2ed6510fb0245478a9f294a9

Working on other issues at the moment, so no pull request at the moment

**Comment by Eideren** [comment]
Fixed through #444
