### ISSUE TITLE
Links in documentation are broken due to namespace changes

### ISSUE THREAD

**Issue by tebjan** [stride3d/stride#44]
The documentation still links to the old namespaces:

![image](https://user-images.githubusercontent.com/1094716/43681557-0f8b8786-9857-11e8-8285-cb51a6619a1d.png)

**Comment by Kryptos-FR** [comment]
Good point. @xen2 will need to re-generate the doc.

As a side-note, issues related to the documentation should go to the [xenko-docs](https://github.com/xenko3d/xenko-docs) repository.
