### ISSUE TITLE
Expose display information to developers (resolution/refresh rate, etc).

### ISSUE THREAD

**Issue by profan** [stride3d/stride#441]
**The Problem**
Right now there's no way to get display information from Xenko, while this information is readily available at least in SDL2 underneath [(SDL_GetWindowDisplayIndex](https://wiki.libsdl.org/SDL_GetWindowDisplayIndex), [SDL_GetDisplayBounds](https://wiki.libsdl.org/SDL_GetDisplayBounds), etc).

This is necessary for things like placing a window in the center of the screen, generating a list of "possible resolutions" given a users display etc (you could of course just arbitrarily populate it with every possible combination and let the user pick, but given that the information is there at least on the SDL2 side and easily accessible, it seems a bit baroque).

**Describe the solution you'd like**
A way to get display information for the current display the xenko game window is on (but being able to query all displays wouldnt hurt).

**Describe alternatives you've considered**
There are ways around this but they involve various levels of hackery and are often then platform-specific, leading you to reimplement what is already there but not exposed.

**Comment by Hadoukanen** [comment]
Is was evaluating this engine as a replacement for my current one and was very pleased with it and then i ran into this. Why have not more people said anything about this since 2019 c'mon... This engine was very promising and then it falls flat on it's nose like this. Well... Guess i have to look further.

**Comment by Eideren** [comment]
Closing this off, afaict it is already implemented under `Game.GraphicsDevice.Adapter.Outputs`. See [GraphicsOutput.cs](https://github.com/stride3d/stride/blob/master/sources/engine/Stride.Graphics/GraphicsOutput.cs)
