### ISSUE TITLE
installetion problem

### ISSUE THREAD

**Issue by aroureo** [stride3d/stride#448]
[log.pdf](https://github.com/xenko3d/xenko/files/3184347/log.pdf)

**Comment by Kryptos-FR** [comment]
@aroureo Please refrain from uploading the log as a PDF.

1. There is no reason to create a PDF out of a text log.
2. There is no guarantee the file is safe of viruses.

**Comment by Eideren** [comment]
Here's a txt conversion by stripping the pdf: [log.txt](https://github.com/xenko3d/xenko/files/3185150/log.txt)
A whole bunch of time outs when fetching packages.

**Comment by aroureo** [comment]
@Kryptos-FR  im sorry I just try to install xenko many times the last 2 days and I cant do that because of this error... I try 3.1 and 3.0 version of xenko but nothing works...any solution plz?

**Comment by Eideren** [comment]
This issue is either fixed or out of date given the changes nuget has gone through, I'll close this off.
