### ISSUE TITLE
Cannot write to RWTexture in Pixel Shader

### ISSUE THREAD

**Issue by WhyPenguins** [stride3d/stride#471]
**Release Type**: Official Release

**Version**: 3.1.0.1-beta02-0615

**Platform(s)**: Windows

**Describe the bug**
An "Invalid Stage" exception is thrown when drawing with a shader that writes to an RWTexture inside the pixel stage.

**To Reproduce**
Write a shader that does the above, something like:
```
shader ...{
    RWTexture3D<float4> Tex;
    override stage void PSMain(){
        Tex[int3(0,0,0)] = float4(1.0);
    }
}
```
**Expected behavior**
Since DirectX 11 and OpenGL 4.2 this should be possible in both compute shaders and pixel/fragment shaders. Not sure how this should be handled regarding supporting multiple API versions, but there should be some way to do it I'd imagine.

**Additional context**
Does anybody know if just commenting out the exception and generalizing the NativeDeviceContext.ComputeShader stuff to allow for other stages would work? I also notice it isn't implemented yet at all in OpenGL, is that on anyone's radar?

Also this is my first GitHub issue, so hopefully this is alright haha. Thanks if you can help!

**Comment by WhyPenguins** [comment]
Just wanted to note (and this should have been obvious when I looked at the code), but this also seems to affect RWStructuredBuffers and other objects that require unordered access views.

**Comment by WhyPenguins** [comment]
Hey, sorry if this isn't the best place to ask this, but...In order to try fixing this I've first compiled Xenko, however I'm not really sure what to do now to get the launcher to recognise the local build. I can see my build in the .nuget cache as 3.1.0.1-beta02, while the launcher only shows the most recent one. Any ideas? :)

**Comment by tebjan** [comment]
@WhyPenguins you made good progress then! @xen2 is currently working on an update of the launcher to choose different beta versions. 
for now the most easy way is to open your game project in visual studio and do a search/replace for "beta02-615" with "beta02". that works well, and if you do a git commit for that change you can revert it later when you want to go back.
once the new launcher is out, this will be much more convenient.

**Comment by WhyPenguins** [comment]
@tebjan Sorry for getting back so late, thanks that did the trick :)
