### ISSUE TITLE
Include .XML documentation files in built Nuget packages for the Public API

### ISSUE THREAD

**Issue by fdrobidoux** [stride3d/stride#499]
## Preface
I've taken the liberty to transfer my concerns from https://github.com/xenko3d/xenko/issues/476 to this new issue, because it became its own thing, and was out of scope from that issue's original intentions. I apologize for the inconveniences this may cause.

## Is your feature request related to a problem? Please describe.
Within the source code in Xenko's runtime libraries (those for the users when coding their games), there is already a lot of written XML documentation available for most classes, methods and properties. However, none of it can be accessed using the IntelliSense quick-info feature of Visual Studio and other modern C# IDEs.

The reason being, Xenko nuget packages are not built with .XML documentation files.
This means that, when you're trying to learn how the Xenko API works, you have to constantly refer to the online API, because no quick-info doc gets generated. This slows down development and learning for those trying to work with the API.

A solution was attempted with commit https://github.com/xenko3d/xenko/commit/a4c7c1a748c8a576d5464559c5460b73b3f6ca87, but sadly, it does not build any .XML doc files.

After I took serious look at the .targets files, I found out said documentation is not in the .xml format : **It's in a .usrdoc format** that is used for in-editor tooltips. That's fine, but whenever we talk about XML doc, it's interpreted as an issue with the editor tooltips. It's not the same at all.

Additionally, project `Xenko.Core.Mathematics` seems to have "XML documentation file" checked in its build properties, yet the .csproj file has no reference to such thing. Comparing it with, say, `Xenko.Core.IO`, that project has "XML documentation file" unchecked, and both csproj files are not much different from eachother. I'm legit confused by this.

## Describe the solution you'd like
Have XML doc files built for every project included in `Xenko.Runtime.sln`. Also, include them in the build process for every nuget packages built, including them in libs and refs (netstandard2.0).

## Describe alternatives you've considered
This shouldn't cause any side-effects, so no alternatives necessary.

## Additional context
Just so we get on the same wave-length when I talk about quick-doc, this is what happens when I'm fetching the quick-doc on the `AngleType.Revolution` : 

![image](https://user-images.githubusercontent.com/9446588/63641755-98507000-c681-11e9-9e36-d7c03a64d36e.png)

**Comment by Aggror** [comment]
This is a must have for developers. Hope this gets fixed soon.

**Comment by xen2** [comment]
This was broken only for specific packages (the one that were tagged with `XenkoRuntimeNetStandard` true).
This is supposedly fixed with a4c7c1a748c8a57
Do you still have the issue with latest beta release?

**Comment by fdrobidoux** [comment]
Sorry, I left you hanging there.

When I tried last time, it still didn't show up quick-doc when I manually imported the `.nupkg` files from generating `Xenko.Runtime.sln` in a brand new project. 

The only way I was able to do it with my limited knowledge of dotnet project building, was by checking the parameter "Include XML documentation" in each project file through VisualStudio's interface. However, it targets a fixed path, which is based on the current build config (ex. Debug + AnyCPU, aka x86-x64) which is probably not what we want.

But hey, doing this includes the `.xml` file in the `.nupkg` on post-build. Somehow it just works.

**Comment by xen2** [comment]
Ha sorry I thought you were talking about the official release.
If you build locally and want the doc (disabled by default cause it was quite slow):
add `<XenkoPublicApi>true</XenkoPublicApi>` in `build\Xenko.PreSettings.Local.targets` if you use `Xenko.sln` (or `build\Xenko.Runtime.PreSettings.Local.targets` if you use `Xenko.Runtime.sln`)
