### ISSUE TITLE
replacing three dots with ellipsis

### ISSUE THREAD

**Issue by leela52452** [stride3d/stride#503]
i have come across about "The string uses three dots (...) instead of an ellipsis character (…)"
i did a online search & could not find a satisfactory answer.

can i pr with changes given.at https://hosted.weblate.org/projects/xenko/assetspresentation/source/review/?type=sourcechecks

**Comment by xen2** [comment]
Hello,
Sure, could you do the changes directly on weblate please?

**Comment by leela52452** [comment]
i believe you have no source strings on weblate.
please check or contact admins of weblate about how to configure source strings.

**Comment by xen2** [comment]
Sorry my bad, this is in the source files (Xaml/C# code)!
