### ISSUE TITLE
Asset Compiler doesn't seem to work well.

### ISSUE THREAD

**Issue by meriaizen86** [stride3d/stride#524]
**Application launch**
Official release, updated via launcher
*Version*
Xenko Game Studio 3.1.0.1-Beta2-0741**: Version number and/or git branch

**Setup**

- Windows 10 Pro 1903-18362.388

- Ryzen 5 2600

- Gygabyte AMD Radeon Series RX 580 GV-R850GAMING-8GD

**Describe the bug**

**To Reproduce**
1. Enable Temporal Antialiasing 
![img](https://i.imgur.com/YgAtmBe.png)

Or:
2. Enable Light Shafts
![img](https://i.imgur.com/A9frDjB.png)

**Expected behavior**
Those effects gets an error on the asset compiler.

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)

**Additional context**
![unknown](https://user-images.githubusercontent.com/26027169/66283711-d2d63b00-e8c4-11e9-96dd-4a3fe27343ff.png)

**Comment by aurodev** [comment]
Add a .txt file with the errors please, hard to scroll through an image.

Similar errors on adding TA.
3.1.0.1-beta02   from around 9.18.19
[AssetCompilerErrors.txt](https://github.com/xenko3d/xenko/files/3743735/AssetCompilerErrors.txt)

**Comment by xen2** [comment]
Can you try again after installing latest VC++ redist and let me know if that fixes the issue?
https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by aurodev** [comment]
Chasing my tail here...
TA is obviously a DX11 feature.   
**Works fine on Direct3D 11.0/OpenGLES 3.1**

**Comment by xen2** [comment]
Thanks for the update.
Maybe what should be improved is:
- make error message more meaningful.
- make error message happen earlier at design-time (in editor)

**Comment by meriaizen86** [comment]
Sorry about that, I missed the log.txt. so I can't post it, my bad.

**Comment by Eideren** [comment]
Issue resolved, moving suggestions over to #675
