### ISSUE TITLE
UI Text Element (non-Fullscreen, non-Billboard) flickering and deformation issues in a 3D scene.

### ISSUE THREAD

**Issue by ravazquez** [stride3d/stride#529]
**Release Type**: Official Release/GitHub (please choose appropriate option)
Official Release
**Version**: Version number and/or git branch
3.0.0.7
**Platform(s)**: Does the problem occur on Windows, Android...?
Windows 10 Pro
**Describe the bug**
UI Text Element (non-Fullscreen, non-Billboard) shows flickering and deformation issues when placed in a 3D scene.

**To Reproduce**
1. Open 
[UITest.zip](https://github.com/xenko3d/xenko/files/3743854/UITest.zip) and run the project
2. Pan and rotate the camera to see deformation, flickering and clipping issues

**Expected behavior**
Text and BG image should deform in the same way. Text should not flicker or clip.

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)

**Additional context**

**Comment by phr00t** [comment]
This is a duplicate. I already identified and fixed this in my fork, and even created a pull request:

https://github.com/xenko3d/xenko/issues/314

**Comment by ravazquez** [comment]
@Eideren was this resolved?

**Comment by Eideren** [comment]
I would expect it to be so considering the PR that phroot mentions has been merged.
