### ISSUE TITLE
Namespace start by number

### ISSUE THREAD

**Issue by cycpe950609** [stride3d/stride#547]
**Release Type**: Official Release

**Version**: 3.1.0.1-beta02-0752

**Platform(s)**: I only test on Windows

**Describe the bug**
When I make a new project which name is start by Number (e.g 3DGame ),Xenko will generate source code file with name of project, not namespce in 'Create a game...' Dialog

**To Reproduce**
1. In "Project selection" ,select New project -> General -> New game , name project 3DGame 
2.Click Select
3.In "Create a game...", type ThreeDGame in namespace, and click OK

**Expected behavior**
namespace in 3DGame.Windows\3DGameApp.cs should be ThreeDGame.Windows

**Additional context**
```cs
using Xenko.Engine;

namespace 3DGame.Windows//Here is ERROR
{
    class 3DGameApp//Here is ERROR
    {
        static void Main(string[] args)
        {
            using (var game = new Game())
            {
                game.Run();
            }
        }
    }
}
```

**Comment by Kryptos-FR** [comment]
I disagree that we need to do anything about it. That is a restriction of how C# works, not something we want to bother with. Just don't name your project starting with a number.

I do think there was a check at some point ot prevent creating such invalid names, that could be one area where we can do something. But transforming the name the user has typed is not a good solution and I would always be strongly against it.

**Comment by xen2** [comment]
@Kryptos-FR I think you might have misread.
Issue is about game name being used as namespace instead of namespace specified by user.
I will see if it's still worth keeping them separate and test what visual studio does for new csproj projects.

**Comment by Kryptos-FR** [comment]
@xen2 I definitely read to fast and misunderstood.

**Comment by Eideren** [comment]
This is mostly fixed, the window where you specify platforms and such when creating a project blocks user if they don't have a valid namespace but the generated *.Windows (linux, osx, etc.) and the class hosting their main still carry the project name which may or may not have an invalid name.

**Comment by herocrab** [comment]
@Eideren it looks as though this issue was resolved and the PR merged. Can this be closed?
