### ISSUE TITLE
ko.po

### ISSUE THREAD

**Issue by jhwon0812** [stride3d/stride#548]
I would like to proceed with the Korean language.
Do you mind if I proceed with the work?

**Comment by xen2** [comment]
@jhwon0812 sure, please go ahead, thanks for offering help!
Quick reminder, the way localization is done is not directly through editing file on git, but instead please do that in
https://hosted.weblate.org/projects/xenko/

More details: https://github.com/xenko3d/xenko/blob/master/docs/localization.md

**Comment by jhwon0812** [comment]
@xen2 
I've translated it into a separate file. 
To who put links to create files po ko pull request for.

Please check the full request. 
Also, if you have any problems with him, I would appreciate it if you could tell me.
