### ISSUE TITLE
Add 2D Game Template

### ISSUE THREAD

**Issue by furesoft** [stride3d/stride#566]
Add 2D Game Templates

**Comment by fdrobidoux** [comment]
Wasn't there a sample 2D game? It should be enough of a base for most projects.

**Comment by JamesOrson** [comment]
There is a 2D game example. So far it has been sufficient for me in making 2D titles and answering my questions.

**Comment by Eideren** [comment]
Requires more detail, I'll close this one off but feel free to open a new one
