### ISSUE TITLE
Simplify Xenko Packages (xkpkg): csproj references xkpkg and not the opposite.

### ISSUE THREAD

**Issue by xen2** [stride3d/stride#58]
As I was thinking about how to tackle on #12 and #13, I thought things would be much easier if we didn't have this xkpkg references + csproj `PackageReference` duality now that we moved to the new csproj system.

The idea would be to move away from `1 xkpkg = multiple csproj` and instead going to `1 xkpkg = 1 csproj` (or `1 xkpkg = 0 csproj` in case of assets-only packages), to fit better with the approach taken by the new csproj system and nuget.
Then PackageReference/ProjectReference would take over the role of dependencies.

Likely the `.xkpkg` would be side-by-side with the `.csproj` file.

Benefits:
* Solution/csproj would become entry-points, not xkpkg (or Solution which contains a xkpkg custom reference)
* Any kind of C# projects/solutions could be opened, much more freedom to compose project as the user want (fits better when user wants to use only specific part of Xenko, or develop plugins)
* Solution/project states should be more easy to maintain (right now we generate `.sln` on save from package, which prevent any project from outside the package).
* No superfluous duplication of Dependencies/PackageReference (which could be out of sync), Metadata package information, etc...
* Can rely on NuGet and MSBuild evaluation/targets rather than our own dependency resolution mechanism.
* Later it enables the way for the whole engine and user projects to become almost standard nuget packages. This should help a lot for #12 and #13.

**Comment by Kryptos-FR** [comment]
Good call. I would also see that issue being a pre-requisites before starting the work on #12 and #13. Is there a way to set precedence/dependencies easily with ZenHub?

**Comment by dfkeenan** [comment]
Are xkpkg even necessary? Could the meta data not just be props in the csproj files?

**Comment by xen2** [comment]
@Kryptos-FR I have already put this issue as part of those two epics (you can't see it?)
screenshot: 
![image](https://user-images.githubusercontent.com/527565/43700596-2e240e06-998e-11e8-965a-dbc33b87cd0b.png)

@dfkeenan yes I was considering it as well (it requires some additional work in the GameStudio so it might happen in multiple steps).

**Comment by Kryptos-FR** [comment]
@xen2 I don't see it from here (mobile phone). I suppose it only appears if the ZenHub plugin is installed.

**Comment by Eideren** [comment]
AFAICT, besides dfkeenan's suggestion, this is done so should we close this off ?

**Comment by xen2** [comment]
Yes, overall it's done (might still need some improvements but better to keep track as separate issues)
