### ISSUE TITLE
Cubemap (*.dds) Skybox appears distorted

### ISSUE THREAD

**Issue by acampbellb** [stride3d/stride#586]
After creating a cube map using Microsoft's DirectXTex library, as such:

PS C:\nexus\workspace\skybox> & .\texassemble.exe cube -y -w 256 -h 256 -o cubemap.dds left.png right.png up.png down.png back.png front.png
Microsoft (R) DirectX Texture Assembler (DirectXTex version)
Copyright (C) Microsoft Corp. All rights reserved.
*** Debug build ***

reading left.png (4096x4096 R8G8B8A8_UNORM 2D α:Opaque)
reading right.png (4096x4096 R8G8B8A8_UNORM 2D α:Opaque)
reading up.png (4096x4096 R8G8B8A8_UNORM 2D α:Opaque)
reading down.png (4096x4096 R8G8B8A8_UNORM 2D α:Opaque)
reading back.png (4096x4096 R8G8B8A8_UNORM 2D α:Opaque)
reading front.png (4096x4096 R8G8B8A8_UNORM 2D α:Opaque)
Writing cubemap.dds  (256x256,6 R8G8B8A8_UNORM Cube)

Attaching to a background entity, the skybox appears distorted (dithered). Is xenko compatible with DirectXTex produced cube maps?

![screencap](https://user-images.githubusercontent.com/24684832/73611237-ced5d380-45ad-11ea-8f57-ecc67930f8ee.png)

**Comment by Basewq** [comment]
I tested one myself with texassemble.exe. By default I get 'banding' issues, as well.
The solution I found was to select the **texture** asset that you're using for the skybox, and untick Compress.
