### ISSUE TITLE
In the Scene editor Pan movement of camera via middle mouse button seems inverted

### ISSUE THREAD

**Issue by Mzoltan32** [stride3d/stride#596]

**Comment by Kryptos-FR** [comment]
Please follow the template and provide the steps to reproduce.

Also have a look at the documentation that explains how to setup the editor controls: https://doc.xenko.com/latest/en/manual/game-studio/navigate-in-the-scene-editor.html

**Comment by Mzoltan32** [comment]
just open the editor on a fresh installation then utilize middle mouse
button if i remember correctly

and then the directions are inverted

**Comment by Basewq** [comment]
Edit -> Settings
Scene editor -> Key bindings -> Tick/untick 'Invert mouse panning axis'

Is this not good enough?

**Comment by Kryptos-FR** [comment]
@Mzoltan32  It is literally on a screenshot in the documentation page I linked.
