### ISSUE TITLE
cant find the is trigger option under property grid

### ISSUE THREAD

**Issue by Mzoltan32** [stride3d/stride#598]
**Release Type**: Official Release

**Version**: Version number 3.1

**Platform(s)**: Does the problem occur on Windows, Android...?

**Describe the bug**
cannot find various options under the property grid tab when selecting a box collider for example
i cant progress with the tutorials

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)

**Additional context**

**Comment by Kryptos-FR** [comment]
Please provide the steps to reproduce and remove any paragraph that don't add any useful information.

**Comment by Mzoltan32** [comment]
rightclick on the asset explorer

select add asset physics selected then select the created physics asset and
there is no options under property grid

**Comment by Basewq** [comment]
You are editing the wrong thing:
https://doc.xenko.com/latest/en/manual/physics/script-a-trigger.html

Select an **entity** in the scene, add Character/Rigidbody/Static collider **component** and edit that component.

**Comment by Mzoltan32** [comment]
how can i have an invisible trigger then

**Comment by Basewq** [comment]
> how can i have an invisible trigger then
If you don't need to see it, then disable or remove the Model component.
