### ISSUE TITLE
I want to compile Xenko from source code

### ISSUE THREAD

**Issue by andyzheung** [stride3d/stride#604]
I want to compile the project, because I can't install from the install exe.

So I want to compile it on my windows 10 PC:

verison:
https://github.com/xenko3d/xenko/tree/releases/3.0.0.6

I follow like this:
Building from source
Prerequisites
Git (recent version that includes LFS, or install Git LFS separately).
Visual Studio 2017 with the following workloads:
.NET desktop development
If your OS is Windows 10: add .NET Framework 4.6.2 development tools in optional components of .NET desktop development
If your OS is Windows 7: .NET 4.6.2 Developer Pack)
Desktop development with C++
.NET Core cross-platform development
Optional (to target UWP): Universal Windows Platform development
Optional (to target iOS/Android): Mobile development with .NET and Android NDK R13B+ individual component
FBX SDK 2019.0 VS2015
Build Xenko
Clone Xenko: git clone https://github.com/xenko3d/xenko.git
Set XenkoDir environment variable to point to your <XenkoDir>
Open <XenkoDir>\build\Xenko.sln with Visual Studio 2017, and build.
Open <XenkoDir>\samples\XenkoSamples.sln and play with the samples.
Optionally, open and build Xenko.Android.sln, Xenko.iOS.sln, etc...

But come to so many errors:
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MC3066	类型引用无法找到名为“TableViewScrollViewer”的公共类型。 行 26 位置 59.	Xenko.Core.Assets.Editor	D:\Project\DistRender\xenko\sources\editor\Xenko.Core.Assets.Editor\Themes\ExpressionDark\TableViewScrollViewer.generic.xaml	26	
错误	MC3066	类型引用无法找到名为“ScrollTip”的公共类型。 行 47 位置 58.	Xenko.Core.Assets.Editor	D:\Project\DistRender\xenko\sources\editor\Xenko.Core.Assets.Editor\Themes\ExpressionDark\Resources\ExpressionDark.normalcolor.Resources.xaml	47	
错误	MC3066	类型引用无法找到名为“NodeVertexControl”的公共类型。 行 25 位置 128.	Xenko.Assets.Presentation	D:\Project\DistRender\xenko\sources\editor\Xenko.Assets.Presentation\AssetEditors\VisualScriptEditor\Views\VisualScriptEditorView.xaml	25	
错误	MC3066	类型引用无法找到名为“GroupNavigationControl”的公共类型。 行 113 位置 71.	Xenko.Core.Assets.Editor	D:\Project\DistRender\xenko\sources\editor\Xenko.Core.Assets.Editor\Themes\ExpressionDark\TableflowView.ExpressionDark.normalcolor.xaml	113	
错误	MC3066	类型引用无法找到名为“EditableContentListBoxItem”的公共类型。 行 25 位置 14.	Xenko.Assets.Presentation	D:\Project\DistRender\xenko\sources\editor\Xenko.Assets.Presentation\AssetEditors\SpriteEditor\Views\SpriteEditorView.xaml	25	
错误	MC3066	类型引用无法找到名为“EditableContentListBoxItem”的公共类型。 行 21 位置 14.	Xenko.Assets.Presentation	D:\Project\DistRender\xenko\sources\editor\Xenko.Assets.Presentation\AssetEditors\GraphicsCompositorEditor\Views\GraphicsCompositorEditorView.xaml	21	
警告	MSB3245	未能解析此引用。未能找到程序集“Xenko.Metrics”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。	Xenko.GameStudio	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	2110	
警告	MSB3245	未能解析此引用。未能找到程序集“Xenko.CrashReport”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。	Xenko.GameStudio	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	2110	
警告	MSB3245	未能解析此引用。未能找到程序集“Xenko.Core.AssemblyProcessor”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。	Xenko.GameStudio	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	2110	
警告	MSB3245	未能解析此引用。未能找到程序集“Xceed.Wpf.Toolkit”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。	Xenko.Core.Assets.Editor	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	2110	
警告	MSB3245	未能解析此引用。未能找到程序集“Xceed.Wpf.DataGrid”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。	Xenko.Core.Assets.Editor	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	2110	
警告	MSB3245	未能解析此引用。未能找到程序集“Xceed.Wpf.AvalonDock”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。	Xenko.GameStudio	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	2110

**Comment by limocute** [comment]
你使用最新的代码编译过吗？我使用3.1的能编译通过，但是最新的master分支不能编译

**Comment by andyzheung** [comment]
> 你使用最新的代码编译过吗？我使用3.1的能编译通过，但是最新的master分支不能编译

![image](https://user-images.githubusercontent.com/22912347/74651088-08b5f500-51be-11ea-9820-6a95d14ebafe.png)

这个版本吗？直接下载release包？

**Comment by limocute** [comment]
按照readme说明安装git包括fls，直接克隆最新master分支，或者master-3.1分支，安装说明中的vs2019工作负载，克隆完就可以编译了，我最新的master分支编译错误是我环境有问题，现在可以了


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by andyzheung** [comment]
我又重新试了一遍，用master-3.1，还是有问题，按照这个说明做的:
![image](https://user-images.githubusercontent.com/22912347/74749194-bdc2dd00-52a4-11ea-9b23-fb445c117550.png)
还是有11个错误：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0006	未能找到元数据文件“D:\Project\xenko\sources\editor\Xenko.Assets.Presentation\bin\Debug\net472\Xenko.Assets.Presentation.dll”	Xenko.GameStudio.Tests	D:\Project\xenko\sources\editor\Xenko.GameStudio.Tests\CSC	1	活动
错误	CS0006	未能找到元数据文件“D:\Project\xenko\sources\presentation\Xenko.Core.Presentation.Graph\bin\Debug\net472\Xenko.Core.Presentation.Graph.dll”	Xenko.GameStudio.Tests	D:\Project\xenko\sources\editor\Xenko.GameStudio.Tests\CSC	1	活动
错误	CS0006	未能找到元数据文件“D:\Project\xenko\sources\editor\Xenko.GameStudio\bin\Debug\net472\Xenko.GameStudio.exe”	Xenko.GameStudio.Tests	D:\Project\xenko\sources\editor\Xenko.GameStudio.Tests\CSC	1	活动
错误	CS0006	未能找到元数据文件“D:\Project\xenko\sources\editor\Xenko.Assets.Presentation\bin\Debug\net472\Xenko.Assets.Presentation.dll”	Xenko.Samples.Tests	D:\Project\xenko\samples\Tests\CSC	1	活动
错误	CS0006	未能找到元数据文件“D:\Project\xenko\sources\presentation\Xenko.Core.Presentation.Graph\bin\Debug\net472\Xenko.Core.Presentation.Graph.dll”	Xenko.Samples.Tests	D:\Project\xenko\samples\Tests\CSC	1	活动
错误	CS0006	未能找到元数据文件“D:\Project\xenko\sources\editor\Xenko.Assets.Presentation\bin\Debug\net472\Xenko.Assets.Presentation.dll”	Xenko.VisualStudio.Package.Tests	D:\Project\xenko\sources\tools\Xenko.VisualStudio.Package.Tests\CSC	1	活动
错误	CS0006	未能找到元数据文件“D:\Project\xenko\sources\presentation\Xenko.Core.Presentation.Graph\bin\Debug\net472\Xenko.Core.Presentation.Graph.dll”	Xenko.VisualStudio.Package.Tests	D:\Project\xenko\sources\tools\Xenko.VisualStudio.Package.Tests\CSC	1	活动
错误	MSB3073	命令“"..\..\core\Xenko.Core.Tasks\bin\Debug\net472\Xenko.Core.Tasks.exe" locate-devenv "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"”已退出，代码为 9009。	Xenko.VisualStudio.Package.Tests	D:\Project\xenko\sources\tools\Xenko.VisualStudio.Package.Tests\Xenko.VisualStudio.Package.Tests.csproj	70	
错误	MC1000	未知的生成错误“Could not find assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly.”	Xenko.Core.Presentation.Graph	C:\windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets	268	
错误	MC1000	未知的生成错误“Could not find assembly 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly.”	Xenko.Assets.Presentation	C:\windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets	268	
错误	MC1000	未知的生成错误“Could not find assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly.”	Xenko.GameStudio	C:\windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets	268	
@limocute

**Comment by Eideren** [comment]
This is most likely caused by the user lacking GIT LFS, install git and in the installer make sure that Large File Storage is enabled.
