### ISSUE TITLE
Stale Microsoft.SourceLink.GitHub prevents building from private mirror repo

### ISSUE THREAD

**Issue by tamlin-mike** [stride3d/stride#613]
https://github.com/xenko3d/xenko/blob/3777bf3b05ad3d5ce06ffa87dce31cae03b8b174/sources/targets/Xenko.Core.GlobalSettings.targets#L137

Consider changing to `Version="1.0.0"`.

2018-07-27 was release date for 1.0.0-beta-63127-02
2019-11-27 was release date for 1.0.0.

Switching to 1.0.0 allows building if you check out your working tree from a (bare) mirror of the Xenko repo. The old beta fails.

ref: https://www.nuget.org/packages/Microsoft.SourceLink.GitHub/

**Comment by Eideren** [comment]
If you have the time to, please, feel free to create a PR for this

**Comment by tamlin-mike** [comment]
That's the patch. Literally. :-)

```
- Version="1.0.0-beta-63127-02"
+ Version="1.0.0"
```

**Comment by Eideren** [comment]
This issue has been resolved through one of the commit before the rename
