### ISSUE TITLE
Parent Objects

### ISSUE THREAD

**Issue by emre1601** [stride3d/stride#632]
When I throw the objects on the unity hierarchy panel to the game screen, the bottom objects appear but not on xenko what is the reason ?

For example, I assign a character model to Unity, the lower parts of the model are visible, but only the object is visible in xenko

**Comment by Kryptos-FR** [comment]
Because they are different engine? I'm having a hard time understanding your issue.

**Comment by Eideren** [comment]
I'll close this one as @emre1601 didn't provide us with more information, feel free to open a new one with more information
