### ISSUE TITLE
DrawOrder question

### ISSUE THREAD

**Issue by CharlesWoodhill** [stride3d/stride#638]
hi,
ive made a gamesystem that also draws debugshapes with lined cubes instead of triangled cubes, 
im doin it similar as GeometricPrimitives does.
i draw them in a draw method override of my GameSystem.
the gui is a seperate scene and a sibling to the "game" scene. both have the root scene as parent.
the shader is a modified version of SpriteEffectShader that uses the vertex color instead of a constant color.

everythings cool, it works, but..
i have a problem with the draw order / pixel depth:
the drawed lines are overdrawing the gui but are not drawn over model entities.
i want it exacly the opposite :)
i need that to debugdraw the octree over my voxel-meshes

so ive 2 problems:

1. how can i make the gui render in front of my lines? 
i already tried:
change UISystem.DrawOrder bigger than mine, but didnt work.

2. how can i make the lines be drawn over the other game content (models)
(preferably switchable at runtime :) but thats not important)
    **[edit] solved this for now (if it dont break the ui overdraw issue :) )
    for others with same problem, this can be used to draw "above" all** 
    `MutablePipelineState.State.DepthStencilState.DepthBufferEnable = false;`

    this seems to solve this issue for now. But using this could eventually draw the lines again over ui,
    once problem 1 is solved.

i dont want to use the debugRenderer thing.

tnx in advance for ur time :)

**Comment by herocrab** [comment]
@CharlesWoodhill Have you looked into accomplishing this within the graphics compositor? I understand you are wanting to do this in code but it seems you could use multiple forward renderers or render group masking, or even render group to render stages to sort this ordering out.

Also, it seems you did find a resolution of sorts, can this be closed?
