### ISSUE TITLE
PhysicsSample crashes on startup

### ISSUE THREAD

**Issue by Flavelius** [stride3d/stride#64]
Win7 Sp1 64bit
Xenko 3.0.0.1
The message is something like: invalid arguments for sharpdx.
(PhysicsSampleApp.Main ->GameBase.Run -> GameWindowForms.Run ->GamePlatform.OnInitCallback -> InitializeBeforeRun -> BeginDraw -> IGraphicsDeviceManager.BeginDraw -> GraphicsDevice.Begin -> SharpDX.Direct3D11.Device.CreateQuery -> E_INVALIDARG)

**Comment by Kryptos-FR** [comment]
Can you check if your graphic card is compatible with Direct3D11? If not you might need to lower the target graphics level to Direct3D10.

**Comment by Flavelius** [comment]
It's the Gtx750, a dx12 GPU

**Comment by Eideren** [comment]
Try another graphics API. I'll close this one since it's unlikely the poster will get back to us but feel free to open a new one
