### ISSUE TITLE
Game Studio Editor docking layout resize bug

### ISSUE THREAD

**Issue by Basewq** [stride3d/stride#659]
**Release Type**: Github

**Version**:  Commit 04bb068ca9eafe3b98dc412e86aba049c2d64cbd onwards (probably)

**Platform(s)**: Windows

**Describe the bug**
Extended.Wpf.Toolkit was updated, but the docking control has a bug.
Resizing a docking panels is buggy, it doesn't always resize to where your last mouse location is when you release the mouse.
It is easier to just see the image as per the open issue https://github.com/xceedsoftware/wpftoolkit/issues/1498

**To Reproduce**
1. Try to resize a layout panel.

**Expected behavior**
Should resize to where the mouse is released.

**Additional context**
As per the open github issue, it is fixed in their paid version and supposedly not going to be released to the open source version until some undetermined time.
Maybe use https://github.com/Dirkster99/AvalonDock instead as per the thread?
Digging through the rabbit hole, perhaps also use https://github.com/dotnetprojects/WpfExtendedToolkit as a whole instead (if any other of the toolkit controls are used)?

**Comment by xwellingtonx** [comment]
@Basewq How did you test this? I tried here and I didn't get the issue.

**Comment by Basewq** [comment]
On the latest commit, resizing this particular resize bar was when I noticed it.
![image](https://user-images.githubusercontent.com/1356956/79915595-56c7cd00-847b-11ea-9870-b58fc351d4ae.png)

It doesn't seem to happen 100% of the time, not sure what the conditions are to make it act buggy.
