### ISSUE TITLE
Folders added in VS don't add in Stride

### ISSUE THREAD

**Issue by bdphil86** [stride3d/stride#663]
**Release Type**: Official Release/GitHub (please choose appropriate option)

Official Release

**Version**: Version number and/or git branch

3.1.0.1

**Platform(s)**: Does the problem occur on Windows, Android...?

Windows

**Describe the bug**

When new folders are added in VS, they don't get added in Stride. This leads to disorganization within Stride. All of the files are created and added to the Assets folder, but they are just there disorganized.

**To Reproduce**
1. add new folders and files in VS.
2. Open solution in Stride.

The new files exist but not the folder structures.

**Expected behavior**

The new folders AND files should exist in VS to maintain organization. I shouldn't have to recreate the folders in both tools.

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)

**Additional context**

**Comment by manio143** [comment]
Ok, so I looked into it. Here's my observations:

- directories show up in the game studio only if they are not empty
    That's because directories are added into the viewmodel by enumerating assets and checking their URLs.
- code has a separate viewmodel (`ProjectCodeViewModel` and `CodeViewModel`) from other assets (`AssetMountpointViewModel` and `AssetViewModel`)
- subfolders of "Assets" are showing up correctly, whereas subfolders for code are skipping one level (for unknown reasons)
    So if I have code in "subfolder" it will show up straight in "Code", but code in "subfolder/puppy" will show up in "Code/puppy".

I'm going to submit a PR for that last one as it is indeed making it hard to find the right class among all scripts in first level subfolders.

Adding non-code assets to new subfolders requires "Reload project" in GameStudio for them to be loaded correctly.

@bdphil86 Could you confirm the behaviour I outlined above? Is my PR for code assets the solution to this bug report?

**Comment by manio143** [comment]
@Eideren I think this can be closed.
