### ISSUE TITLE
Game Studio: Winform events getting delayed when multiple GameForms are open

### ISSUE THREAD

**Issue by timotii48** [stride3d/stride#686]
**Release Type**: Official Release/GitHub (please choose appropriate option)
GitHub
**Version**: Version number and/or git branch
Master
**Platform(s)**: Does the problem occur on Windows, Android...?
Windows 
**Describe the bug**
When you have multiple Embedded Game Forms (scenes, prefabs) open, lets say; main scene and a prefab. 
Then when you are in the main scene and press and hold both keyboard and mouse button (as you do when you want to orbit, ALT+LEFT MOUSE). The events from WinForm gets delayed, more and more as you continue to hold the keys down. So much as letting go of the mouse button after a couple of seconds it then takes another couple of seconds before OnMouseUp in MouseWinForms.cs gets called. 

This seems to happen on every Game form except the last one you opened. So if you have the main scene open and then open two prefabs this issue occurs in the main scene and then also in first prefab opened. Same if you open even more. The last one opened always works as expected. 

I'm sorry if the explanation is poor. If needed I can create a video showing it the steps and issue. 

**To Reproduce**
1. Create a new projects (empty)
2. Create prefab of the sphere
3. Open sphere prefab
4. Return to main scene
5. Try orbiting around for a couple of seconds or pan around with random keyboard key held down

**Expected behavior**
Should be the same behavior interacting with the scene as when no prefabs are open

**Screenshots**
-

**Log and callstacks**
-

**Additional context**
-

**Comment by dfkeenan** [comment]
I have been digging around the embedded game stuff. I did notice in the `GameEngineHost.ForwardMessage` method it doesn't check if it the game is "attached"/visible before forwarding the input events. Not sure if it's necessary. Could be worth investigating though.

**Comment by timotii48** [comment]
Good suggestion. Tried commenting it out real quick to see if it was causing the issue. Unfortunately it did not help.

**Comment by timotii48** [comment]
After seeing Krait's issue on discord I thought it might be related so tried recreating it the same way as this issue. I'm holding down CTRL both at the start and end of the video. The overall issue seems as "simple" as holding down any keyboard key while more then 1 embedded game form is open and the whole game studio input system breaks.  
![issue_686](https://user-images.githubusercontent.com/4416708/80922255-1c640700-8d7c-11ea-8d63-334e5e77f2e3.gif)

**Comment by xen2** [comment]
@Eideren once I disable the `MissingInputHack` added in #181, I don't have the issue anymore.

**Comment by jeske** [comment]
Same here... if I comment out `MissingInputHack`, this issue goes away.

Maybe we need a real fix for whatever that hack was targetting?
