### ISSUE TITLE
Pale 2D Texture

### ISSUE THREAD

**Issue by rds1983** [stride3d/stride#691]
Hello,
I've made very simple sample(attached) that loads and renders a texture.
And it looks pale.
Original texture:
![image](https://user-images.githubusercontent.com/1057289/80858356-0e7e8b00-8c83-11ea-972a-9aa7d92eba18.png)
Sample:
![image](https://user-images.githubusercontent.com/1057289/80858388-3b32a280-8c83-11ea-9f4d-8b32a8b3b482.png)

Question is - did I do something wrong?

[StrideDrawTexture.zip](https://github.com/stride3d/stride/files/4567285/StrideDrawTexture.zip)

**Comment by tebjan** [comment]
Which color space is set in the game settings of your game?

How did you load the texture? Did you enable or disable sRGB sampling?

How is the PostFX section set up? Any color transformation enabled?

**Comment by rds1983** [comment]
> Which color space is set in the game settings of your game?
> 
> How did you load the texture? Did you enable or disable sRGB sampling?
> 
> How is the PostFX section set up? Any color transformation enabled?

```c#
using Stride.Core.Mathematics;
using Stride.Engine;
using Stride.Games;
using Stride.Graphics;
using System.IO;
using System.Threading.Tasks;

namespace StrideDrawTexture
{
	class MyGame: Game
	{
		private Texture _texture;
		private SpriteBatch _spriteBatch;

		public MyGame()
		{
			IsMouseVisible = true;
		}

		protected override Task LoadContent()
		{
			using (var stream = File.OpenRead("image.jpg"))
			{
				_texture = Texture.Load(GraphicsDevice, stream);
			}

			_spriteBatch = new SpriteBatch(GraphicsDevice);

			Window.AllowUserResizing = true;

			return base.LoadContent();
		}

		protected override void Draw(GameTime gameTime)
		{
			base.Draw(gameTime);

			// Clear screen and buffers
			GraphicsContext.CommandList.Clear(GraphicsDevice.Presenter.BackBuffer, Color.Black);
			GraphicsContext.CommandList.Clear(GraphicsDevice.Presenter.DepthStencilBuffer, DepthStencilClearOptions.DepthBuffer | DepthStencilClearOptions.Stencil);

			// Draw texture
			_spriteBatch.Begin(GraphicsContext);
			_spriteBatch.Draw(_texture, Vector2.Zero);
			_spriteBatch.End();
		}
	}
}

```

**Comment by rds1983** [comment]
The issue is fixable by explicitly loading texture in sRGB format.
I.e. by replacing line:
```c#
_texture = Texture.Load(GraphicsDevice, stream);
```
with
```c#
_texture = Texture.Load(GraphicsDevice, stream, TextureFlags.ShaderResource, GraphicsResourceUsage.Immutable, true); // 'true' is value for loadAsSRGB parameter
```

thanks for the help, @tebjan!
