### ISSUE TITLE
Documentation for Color[index] is incorrect

### ISSUE THREAD

**Issue by johang88** [stride3d/stride#693]
**Release Type**: Github
**Version**: master

**Describe the bug**
The documentation states "The index of the component to access. Use 0 for the alpha component, 1 for the red component, 2 for the green component, and 3 for the blue component". 

The actual implementation uses:
```
switch (index)
{
	case 0: return R;
	case 1: return G;
	case 2: return B;
	case 3: return A;
}
```

**Expected behavior**
Documentation should match the implementation

**Comment by Eideren** [comment]
Line in question: https://github.com/stride3d/stride/blob/f2aa3ed9d9077727a2bd1d152340c628932668b1/sources/core/Stride.Core.Mathematics/Color.cs#L222

**Comment by raphaelschmitz00** [comment]
First time working on open source, this seems perfect to check if I can handle the git part :D
I'll have a go!

**Comment by raphaelschmitz00** [comment]
...maybe _too_ easy, this was fixed 3 years ago.

If it's not about more than the single line mentioned by @Eideren, at least.

**Comment by Eideren** [comment]
Yep, sorry about that @raphaelschmitz00 !
