### ISSUE TITLE
editor middle-button-drag often fails to respond

### ISSUE THREAD

**Issue by jeske** [stride3d/stride#701]
**Release Type**: Release
**Version**: 4.0.0.1 beta2 0926
**Platform(s)**: Windows

**Describe the bug**
When middle-button dragging in the Editor Studio 3d view, it often (15-30% of the time?) fails to respond or lags for 1-3 seconds. 

**To Reproduce**
1. In the editor studio, repeatedly middle-button drag the 3d viewport
2. WITNESS: periodically the viewport won't drag, or will freeze for 1-2 seconds before dragging

**Expected behavior**
I expect the 3d viewport to reliably drag/pan when using middle mouse button, just like it reliably rotates when using right mouse button.

**Comment by xen2** [comment]
I can't seem to reproduce.
It doesn't happen with any other button?
Curious, could it be some other interaction? (another software or mouse driver?)

**Comment by xen2** [comment]
Note: I doubt this is it, but if you just opened the scene and move around right after, it might be stuck loading some asset? (most of it is async but there's a small point where it needs to synchronize with game thread)
Or maybe the texture streaming system somehow blocking while moving?

**Comment by Eideren** [comment]
perhaps related to #686

**Comment by jeske** [comment]
It happens no matter how long the scene is open. It happens reliably at least 30% of the time with middle-button or modifier-key drag. RMB alone never exhibits the behavior. 

I don't believe there is any reason for a driver or other software issue. Hard to completely rule out, but my middle button and modifiers don't work funny in any other programs, and I don't have any funky drivers or anything.

I'll do some sleuthing and see if I can figure out what might be going on.

**Comment by jeske** [comment]
Okay, i'm so sorry. this turned out to be a freak hardware failure. My middle button stopped working completely now. I tried another physical mouse and it's fine.

I really did test it in Blender back when I had this problem.. but I guess it was just starting to fail then and it was more intermittent.... weird signals. Anyhow.. no Stride bug. 

I'm going to close this, but also feel free to just delete it.
