### ISSUE TITLE
[Forum] Can't login to https://forums.stride3d.net/ with github account

### ISSUE THREAD

**Issue by rds1983** [stride3d/stride#703]
**Describe the bug**
When I try to login to https://forums.stride3d.net/ with github account, I get "Sorry, there was an error authorizing your account. Please try again.".

**Screenshots**
![image](https://user-images.githubusercontent.com/1057289/81188373-6f89c400-8fdf-11ea-8b68-66880e6ce709.png)

**Comment by StefanJanssen95** [comment]
@rds1983 The issue seems to be solved now. You should be able to login with Github.

**Comment by Eideren** [comment]
Thanks for going through these @StefanJanssen95 , feel free to re-open or create a new one if it didn't work out for you @rds1983

**Comment by rds1983** [comment]
It works for me now. Thanks!
