### ISSUE TITLE
window live-resize

### ISSUE THREAD

**Issue by jeske** [stride3d/stride#709]
**Is your feature request related to a problem? Please describe.**

Currently when `Game.Window.AllowUserResizing=true;`, the window *IS* resizable, but the content in the viewport freezes during the resize, and any exposed regions are black. The experience is quite ugly.

**Describe the solution you'd like**

I'd like the 3d view to keep repainting and live-resize as the user drags. 

Most other 3d game engines and games do live-resize, so it's obviously doable. For example, Unity based game windows repaint and resize the 3d view periodically (though with a lag) while dragging. The more content in the 3d view, the more "lag" there is for the 3d view to catch up.

**Additional context**

I suspect the most expensive part of the 3d resize is re-allocating the render-buffer (and maybe the resulting pipeline flush?). 

From some casual tests with a Unity game window, I don't think they are doing anything super-special, other than obviously not blocking the 3d thread with the window live resize. If you resize the unity window really fast, the 3dview "lags" behind the actual window live resize, showing black regions if the window is getting bigger.. and then 100-200ms later the 3d view "catches up" and resizes to fill the window. Even this mediocre experience feels much better than what Stride is doing today.

**Total Overkill Ideas**

Craftier code could employ strategies to do better, and I suspect some game engines do better than Unity... For example..
- one could defer the render-buffer resize when shrinking the window, repainting a sub-portion of the larger render-buffer
- when resizing larger, one could proactively resize larger than the current window (say 30%?), to allow fast repaints for a while without being immediately forced to reallocate again.
- when resizing larger, one could allow pixels to deporarily scale to defer resizing the buffer for some deviation from desired of buffer-to-screen pixels ratios (might be ugly)
- perhaps there is some buffer trickery one could to do avoid pipeline stalls (though probably not worth it)

**Comment by Kryptos-FR** [comment]
Is it worth it to make the rendering complicated just to enabled redrawing the window for the very short period where the user resize it? Period during which, the user will not in anyway interact with the game.

**Comment by Eideren** [comment]
I think we can expand this enhancement to also prevent freezing while users drag the window around, hold it in place, etc.
Let's first get this to a place where the view continues to update while resizing and see if there is a need to optimize it further.
Investigating a bit on the SDL side, not sure about winforms and windows store thingy.
I was able to update the view while resizing through a fairly trivial, while hack-y, change:
```cs
SDLMessageLoop.Run()
{
    [...]
    SDL.SDL_SetEventFilter((userData, sdlEventPtr) =>
    {
        unsafe
        {
            SDL.SDL_Event e = *(SDL.SDL_Event*)sdlEventPtr;
            if (e.type == SDL.SDL_EventType.SDL_WINDOWEVENT 
                && e.window.windowEvent == SDL.SDL_WindowEventID.SDL_WINDOWEVENT_RESIZED)
            {
                renderCallback();
            }
        }
        
        return 1;
    }, IntPtr.Zero);
    [...]
}
```
But ``SDL_SetEventFilter`` never fires while the user holds the mouse button without moving it around, so not quite in a place that I feel warrants a PR.

**Comment by Eideren** [comment]
Closing this given that there has been activity in a duplicate (#1485)
