### ISSUE TITLE
Game Studio code editor broken

### ISSUE THREAD

**Issue by Basewq** [stride3d/stride#711]
**Release Type**: GitHub

**Version**: Some commit AFTER 4536bba6c37255f693d783352c5f0f3d9e12e8cd

**Platform(s)**: Windows

**Describe the bug**
On the latest commit, when you open any C# file in Game Studio, it'll only display as an empty file.
Afterwards, you can no longer open any new assets (most likely the editor has internally crashed the docking manager/WPF to the point of no return).

**To Reproduce**
1. Open a C# file in any project.

**Expected behavior**
Allow opening C# file.

**Additional context**
I have tested my commit 4536bba6c37255f693d783352c5f0f3d9e12e8cd, and it was still working.
Unfortunately, I could not narrow down the specific commit that caused this issue, as some of the subsequent commits aren't buildable on my machine (though the latest is buildable again).
The most likely cause is commit cd751d675fb64f9494df91cf54b57be747476966 (PR #667), however I can't make a build just prior to this commit to confirm this, maybe someone will have better luck trying to narrow down which commit/file is causing this issue.

**Comment by Kryptos-FR** [comment]
I'm also having some issues. I'll try a `git bisect` to pinpoint the exact regression.
