### ISSUE TITLE
Keyboard input demo the blue pot stuck at Y 90 degrees

### ISSUE THREAD

**Issue by aunpyz** [stride3d/stride#725]
**Release Type**: Official Release

**Version**: 4.0.0.1-beta02-0926

**Platform(s)**: Windows

**Describe the bug**
C# beginner project in keyboard input demo when I press 1 to rotate a blue pot, it'll always end up stuck at rotation Y = 90

**To Reproduce**
1. Create a new C# Beginner project
2. Run the project
3. Go to keyboard input demo and press 1, wait until blue pot rotated for ~90 degrees and it'll be stuck at that angle

**Expected behavior**
The blue pot should be rotated past 90 degrees just like yellow and green pots

**Screenshots**
![Capture](https://user-images.githubusercontent.com/14342782/81902807-f4ca3580-95ea-11ea-9ea8-3a40a6329416.PNG)

**Additional context**
The other 2 pots use 
```c#
PotEntity.Transform.Rotation *= Quaternion.RotationY(value)
```
instead of 
```
PotEntity.Transform.RotationEulerXYZ += new Vector3(0, value, 0)
```

**Comment by Kryptos-FR** [comment]
Maybe that's the point, i.e. to illustrate what doesn't work 😜 

If not, it could be done this way. I think it is good to show common mistakes.

**Comment by aunpyz** [comment]
How can I assign myself to this issue? I'll just change that line of code and create PR

**Comment by xen2** [comment]
@aunpyz Thanks for looking into it!
Maybe, let's wait for @Aggror answer to make sure it wasn't done on purpose?

**Comment by Kryptos-FR** [comment]
I jokingly said it could have been on purpose. But even if so, we should have the correct line commented out below the incorrect line.
And maybe add another comment explaining why it doesn't work (or an accompanying readme.md).

**Comment by Aggror** [comment]
It wasn't done on purpose so feel free to update it!  Be sure to run the game to see if things still work. 
:)
