### ISSUE TITLE
Transparency not working with texture alpha in .DDS file. From Amazons Bistro model.

### ISSUE THREAD

**Issue by antonyjones67** [stride3d/stride#726]
**Release Type**: Official Release/GitHub (please choose appropriate option)
Master Branch

**Version**: Version number and/or git branch
4.0.0.1 beta 3

**Platform(s)**: Does the problem occur on Windows, Android...?
Windows Editor

**Describe the bug**
DDS file has Alpha not rendering as transparency.

**To Reproduce**
Just apply the texture to a plane.

**Screenshots**

[Foliage_Bux_Hedges46_BaseColor.zip](https://github.com/stride3d/stride/files/4637798/Foliage_Bux_Hedges46_BaseColor.zip)

**Comment by Basewq** [comment]
Did you enable transparency on the material, as well?
https://doc.stride3d.net/latest/en/manual/graphics/materials/misc-attributes.html#transparency

**Comment by antonyjones67** [comment]
It worked for me by changing the material transparency to CutOff. Thank you for your help.
