### ISSUE TITLE
Add support for Flatpak packages

### ISSUE THREAD

**Issue by LeandroStanger** [stride3d/stride#73]
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by Kryptos-FR** [comment]
Can you provide more information?

What are those packages? What benefit would Xenko have to support them? What are the limitations? Etc.

**Comment by jayrulez** [comment]
Xenko Editor does not run on Linux currently so I assume you mean publishing the game as a flatpak package for Linux?

**Comment by Eideren** [comment]
Closing as not applicable / lacking information
