### ISSUE TITLE
og:image in website still embeds the xenko logo

### ISSUE THREAD

**Issue by m9dfukc** [stride3d/stride#739]
<meta property="og:image" content="/images/og/ogp.jpg">

[https://stride3d.net/images/og/ogp.jpg](https://stride3d.net/images/og/ogp.jpg)

**Comment by StefanJanssen95** [comment]
This issue should be in the website project: https://github.com/stride3d/stride-website

**Comment by tebjan** [comment]
This seems to be fixed. Close?

**Comment by herocrab** [comment]
@Eideren @tebjan Please close.
