### ISSUE TITLE
GameTime needs more options

### ISSUE THREAD

**Issue by Basewq** [stride3d/stride#749]
**Is your feature request related to a problem? Please describe.**
Maybe or maybe not the GameTime class itself, but there needs to be more features to control the 'timer' of a game.
A game needs options be able to pause a game, scale the timer (eg. for slow motion).
This also needs to be affect the physics engine, model animation, but NOT the UI (though not sure if UI has any built in animations?).
Not sure how Sound should be affected.

While you can just create your own "GameTime" object that your own scripts can use, this doesn't affect physics/animation since they specifically use GameTime.
Physics only has `Simulation.DisableSimulation`, but no time scale, though there is a `FixedTimeStep` field, but not sure if that is really the appropriate thing to change for time scaling.

**Describe the solution you'd like**
Honestly don't know what the solution is for this.
I know Unity uses a static field (bleh!) `Time.timeScale`.
Perhaps be able to set it directly on the GameTime object itself, or maybe via a service/game system?
One thing that needs to be clear if done is ensuring there's a distinction between the _current_ time's scale and the _requested change_ in time scale.

**Comment by ykafia** [comment]
I'll have a go on this issue and see what i can do.

**Comment by herocrab** [comment]
This looks to be merged, were we waiting on the docs to be updated before closing?

**Comment by Basewq** [comment]
Closed, as per #785
