### ISSUE TITLE
Right shift key doesn't work

### ISSUE THREAD

**Issue by HordeResurrection** [stride3d/stride#754]
**Release Type**: Official Release

**Version**: 3.1.0.1

**Platform(s)**: Windows 8 x64

**Describe the bug**
Right shift key doesn't work.

**To Reproduce**
1. Create sample project "TouchInput"
2. Press the right shift key

**Comment by HordeResurrection** [comment]
Workaround:

`using(_game = new Game()) _game.Run(GameContextFactory.NewGameContextSDL());`

Thx to Eideren

**Comment by bmello4688** [comment]
This seems resolved. I'm assuming this doesn't happen on windows 10?

**Comment by HordeResurrection** [comment]
> This seems resolved. I'm assuming this doesn't happen on windows 10?

No this is not resolved. I retested this issue in "Stride 4.0.0.1-beta04-1317" on windows 10.
But I watch same behavior. "Left Shift" is works, but "Right Shift" is not.

Also I noticed a new detail. Field "Key pressed/released" has a "Left Shift" text when I press "Right Shift"
See that gif (it's so fast but you can see)
![2020-11-24_20-10-58](https://user-images.githubusercontent.com/65279361/100128583-4aeb2180-2e35-11eb-98fc-5171cb3d9a2e.gif)

And same gif for the real "Left shift" pressing
![2020-11-24_20-11-26](https://user-images.githubusercontent.com/65279361/100128657-63f3d280-2e35-11eb-86d4-928addd4acc8.gif)

**Comment by Eideren** [comment]
See #929 for more info
