### ISSUE TITLE
Interface member that is a component doesn't get serialized properly

### ISSUE THREAD

**Issue by manio143** [stride3d/stride#764]
**Release Type**: Official Release

**Version**: beta03

**Platform(s)**: Any

**Describe the bug**
I have a public member on a script that accepts an interface implementation.
If the implementing class inherits from ScriptComponent it is serialized as a reference and not a new instance. Therefore it's not instantiated, because it refers to something that is defined nowhere.

**To Reproduce**
1. Create an interface

        public interface ITest { }
2. Create a script implementing it

        public class Test : ScriptComponent, ITest { }
3. Create a script that uses the interface as a public member

        public class Runner : StartupScript
        {
            public ITest test;
            public override void Start()
            {
                if (test == null) throw new Exception();
            }
        }
4. In Game Studio create an entity with Runner script. From dropdown of field test choose Test.
5. Run game, get an exception

**Expected behavior**
The script `Test` is serialized as a new object, thus the field is properly deserialized and not null.

**Attached example project**
[IFaceBugRepro.zip](https://github.com/stride3d/stride/files/4807990/IFaceBugRepro.zip)

**Comment by xen2** [comment]
Please try to add `[DataContract]` on `ITest`

**Comment by manio143** [comment]
`[DataContract]` is only valid for classes, structs, enums and delegates.

**Comment by manio143** [comment]
I thought about it a bit more and here are possible ways to handle this:

* Disallow assigning Entity Components as interfaces, because components should be tied to Entities and not instantiated as parts of other components
* Allow only Components that implement the interface and are already on the Entity
* When the Entity doesn't have a component implementing that interface, but it is selected in another component and serialized as a new object, this component will be added to the Entity during deserialization

What is my particular use case?
I have an interface for character input. It can be either using `Input` from `ScriptComponent` to get input or use some other logic (AI) to produce input.

Current workaround:
I have a public, serializable field of type `InputController` (my script) on the class implementing the interface. So in Game Studio I choose the implementation from the dropdown and than have to drag'n'drop the same entity to the field to get that `ScriptComponent` reference I need.

**Comment by xen2** [comment]
Sorry, my bad. The correct solution should be more along those lines:
- Add `[DataContract]` on `Test` class
- Add `[DataMember]` on `Runner.test` member (not sure that one is necessary)

Does that work better?
That's what we do for things like `LightComponent.Light` which is a `ILight`.

**Comment by manio143** [comment]
`Test` already inherits `[DataContract]` from `ScriptComponent` and every public field on `Runner` behaves as if it had `[DataMember]` on it.

The issue is that when setting a value of type deriving from `EntityComponent` it is always treated as a reference to an existing component on an existing Enity.
Here in [EntityHierarchyElementChangePropagator.cs#L22](https://github.com/stride3d/stride/blob/bd140806379507c1101ed13bcca8a002fec35ebe/sources/editor/Stride.Assets.Presentation/AssetEditors/EntityHierarchyEditor/ViewModels/EntityHierarchyElementChangePropagator.cs#L22) we can see the different behaviour between a class that is an `EntityComponent` and one that isn't. But since that component is created without an Entity, on line 30 we get a `NullReferenceException`. This exception is swallowed without notifying the user. In result the property gets serialized with a reference GUID that isn't pointing to anything and during the deserialization we get an error and set the field to `null`.

**Comment by xen2** [comment]
Ha sorry I didn't realize/skipped over the fact `Test` is an `EntityComponent`.
You're right, we make some assumptions that they always belong to an actual component.
And exception being swallowed isn't great either...
