### ISSUE TITLE
Allow components to have required members and warn when the asset value for such member is null

### ISSUE THREAD

**Issue by manio143** [stride3d/stride#778]
### Feature description
**Is your feature request related to a problem? Please describe.**
It is good practice to find bugs during the compilation steps rather than in runtime. When designing components it may be a good idea to put a `[NotNull]` attribute on a required field or property. However, currently there is no check in place that would actually validate that an asset fulfills such promise.

**Describe the solution you'd like**
The Game Studio and more importantly the Asset Compiler should emit a warning when the asset for a required field is `null`.

**Describe alternatives you've considered**
The alternative is observing a runtime exception to find out an asset is missing.

### Additional context
I wanted to submit a PR, but then I read I should discuss the solution in an issue first.

In order to handle this situation I have created a step in the `YamlAssetSerializer` that checks each serialized/deserialized member for the `[NotNull]` attribute and if they have it whether they're equal to `null`. If so a warning is emitted.
You can see the changes here: [manio143/stride: asset_null_warning](https://github.com/manio143/stride/commit/6e236d6202e1132086c6f7f5b2c697788d2689c3)

The Asset Compiler reads assets and the Game Studio reads assets when opening project and writes assets when saving it.
My current solution seems fine for the Asset Compiler, but may be a bit too verbose for Game Studio as seen on the GIF below.

![asset_compiler_null_warning](https://user-images.githubusercontent.com/10709060/86479504-99940400-bd4c-11ea-9a26-4bbb3b540516.png)

![asset_null_warning](https://user-images.githubusercontent.com/10709060/86474260-b75c6b80-bd42-11ea-8655-307037286660.gif)

### Discussion topics

* Is `[NotNull]` a good attribute to be used here (there already are Stride components with members marked with it) or maybe a `[MemberRequired]` would be a better choice?
* Performance - is checking an attribute for every serialized/deserialized member going to have a performance impact? It would be interesting to test it on a bigger project.
* What is the best way to signal this warning in Game Studio?
    My current approach cannot give additional details about which Scene/Entity has the component with a missing asset.
* Should this validation process happen during serialization or be separately invoked?
* Similar approach for `[ItemNotNull]` in collections?

**Comment by MechWarrior99** [comment]
I like this. Seems to me that `[MemberRequired]` is a more descriptive name, for what the desired outcome is. Not having entity info is going to make it hard to debug. Not sure where, it should be called though.

**Comment by xen2** [comment]
I always understood `[NotNull]` as: it can **never** be null (enforced in constructor for example).
Since your example object can easily be initialized in a state where it's `null` (or set to `null` again later), it doesn't seem to fit the bill.

So we probably need another attribute which basically express an asset can't be compiled unless the property is not null. We might even want to customize behavior (should it be an error or just a warning?).

It might be possible to make it either during serialization pass.
But a likely much better option would be to do it during a specific (non-serialization) pass which is done only at compile time. That way, serialization code is not made more complex/slower due to this feature, and it would avoid coupling serialization code with such a feature.
Either way, it shouldn't affect deserialization.

**Comment by manio143** [comment]
I started working on a proper solution. I moved the code from serialization into a proper asset compiler step. I also created a new attribute. You can check the exact code here: https://github.com/manio143/stride/commit/4ff9c2863b64abbf321b63d8aa2aea9027222e52
_Note: before I submit a PR I want to rework this a little and complete a TODO in the modified class_

So you can do the following:
```csharp
using Stride.Core;
using Stride.Core.Annotations;
using Stride.Engine;

namespace DevTest
{
    [DataContract]
    public class MemberScript : ScriptComponent
    {
        [MemberRequired(ReportAs = MemberRequiredReportType.Error)]
        public Entity YoMama { get; set; }

        [MemberRequired(ReportAs = MemberRequiredReportType.Warning)]
        public Entity YoDaddy;

        [DataMember]
        [MemberRequired]
        private Entity YoSon { get; set; }
    }
}
```

The default value for `ReportAs` is a warning.

You can normally save the scene in GameStudio and you won't get any notification. But when you try to build, it will activate the checks and signal the following:
```
Warning: [SceneAssetCompiler] The component MemberScript on entity [MainScene:Ground] is missing a value on a required field 'YoDaddy'.
Error: [SceneAssetCompiler] The component MemberScript on entity [MainScene:Ground] is missing a value on a required field 'YoMama'.
Warning: [SceneAssetCompiler] The component MemberScript on entity [MainScene:Ground] is missing a value on a required field 'YoSon'.
Error: [AssetCompiler] BuildStep Asset build steps [SceneAsset:'MainScene'] (0 items) failed.
```
