### ISSUE TITLE
Stride VSX Integration Crashes Visual Studio 2019

### ISSUE THREAD

**Issue by devjarmo** [stride3d/stride#779]
**Release Type**: Official

**Version**: Stride 4.0.0.1-beta04-1207 Launcher v5.0.1

**Platform(s)**: Windows 10

**Describe the bug**
I install the VSX plugin, if I open a project I've been working on and then launch VS, VS crashes shortly after loading, likely when it's loading the plugin. Also happens if I open VS first and then open a .sln for a Stride game.

I was able to create a new project with game studio and open it in VS. The VSX integration worked. It must be something with my project causing the crashing, wasn't happening before the upgrade. Any guidance is appreciated.

I also noticed that my Stride nuget packages do not appear to be upgraded, even though I upgraded the launcher and can open the project. Normally I'm prompted to upgrade them but that did not appear to happen.

I attached the ActivityLog.xml in zip format.

**To Reproduce**
1. Install Stride VSX
2. Open Visual Studio

**Expected behavior**
I expect the integration to work.

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)
[ActivityLog.zip](https://github.com/stride3d/stride/files/4874313/ActivityLog.zip)

**Additional context**

**Comment by devjarmo** [comment]
I was able to resolve the issue by manually upgrading nuget files. Not sure why I wasn't originally prompted, but after upgrading it seems VSX is working again. :D

**Comment by xen2** [comment]
Good, thanks for the update!
