### ISSUE TITLE
cannot gen android project

### ISSUE THREAD

**Issue by qianqians** [stride3d/stride#780]
![image](https://user-images.githubusercontent.com/1223332/86550188-50be9400-bf74-11ea-9512-9b63d5b51a3d.png)

**Comment by bmello4688** [comment]
Duplicate

**Comment by Eideren** [comment]
But it isn't really though unless there's something I'm missing. This one refers to a missing ``Resource.Designer.cs`` that, probably, should have been generated through some build tools while #827 refers to a missing ``Xamarin.Android.CSharp.targets`` in the build tool installation directory...

**Comment by tebjan** [comment]
I think it's ok to gather both problems in #827 so if someone has time to look at android builds, both get fixed.
