### ISSUE TITLE
Does Navigation Mesh Incorporate Navigation Component Entities?

### ISSUE THREAD

**Issue by herocrab** [stride3d/stride#787]
# Question and/or Comment

The navigation mesh does not appear to work for anything but StaticColliderComponents. It doesn't appear to detect any other type of components, including characters. This means Characters will try to path through each other.

I attempted to add static colliders and manually update position but this approach resulted in duplicate collider UID when instantiating from Prefab.

Is the Navigation Mesh pathfinding intended to evaluate the colliders of other navigation component entities in the navigation group mesh and this is a bug, or is this by design?

**Comment by devjarmo** [comment]
In attempting to work around this, the following does not appear to work:

PhysicsComponent.Entity.Transform.Position += PhysicsComponent.Entity.Transform.Position + Vector3.UnitX;
PhysicsComponent.Entity.Transform.UpdateWorldMatrix();
PhysicsComponent.UpdatePhysicsTransformation();

From:
https://doc.stride3d.net/latest/en/manual/physics/static-colliders.html

**Comment by bmello4688** [comment]
This seems like the correct behavior. I'm going to close this unless you are looking for a feature request
