### ISSUE TITLE
Importing the xenko terrain demo crashes the editor

### ISSUE THREAD

**Issue by SeleDreams** [stride3d/stride#804]
**Release Type**: Latest official Stride release

**Version**: 4.0.0.1-beta04-1254

**Platform(s)**: Windows

**Describe the bug**
I tried to import the xenko terrain demo that can be found here https://github.com/TomGroner/XenkoTerrain however it made Stride crash, it seems to have a 100% reproduction rate

**To Reproduce**
1. download the xenkoterrain demo
2. Try to open it with Stride by letting it upgrade its packages

**Expected behavior**
The project should open, maybe with some issues to fix due to the new version but still without crashing

**Screenshots**
![image](https://user-images.githubusercontent.com/16335601/88521271-fce41f80-cff4-11ea-84d4-89a1a7bb6832.png)

**Log and callstacks**
[exception-stacktrace.log](https://github.com/stride3d/stride/files/4980873/exception-stacktrace.log)

**Comment by Eideren** [comment]
That's a third party project, I'm not sure this issue should be filed here unless you know for sure that it's related to the engine itself

**Comment by SeleDreams** [comment]
> That's a third party project, I'm not sure this issue should be filed here unless you know for sure that it's related to the engine itself

technically the editor should crash when opening a project I think even if the project is third party, it should mostly display an error when opening it

**Comment by Eideren** [comment]
Right, yes definitely.

**Comment by salahchafai** [comment]
![Capture1](https://user-images.githubusercontent.com/64394387/125477909-f1372b04-c9f0-43dd-ae2c-831a7bdc7632.PNG)
![Capture2](https://user-images.githubusercontent.com/64394387/125477917-6c23aebe-1a1c-4964-8de9-f84e52fcd214.PNG)
doesn't seem to crash in Stride 4.1.0.1459-beta
maybe it should be closed ?

**Comment by Eideren** [comment]
Yep, the other issues seems specific to that repo, feel free to open a new issue if it isn't though.
