### ISSUE TITLE
"An error occurred while trying to open a web browser" message when clicking on links in the Stride Launcher

### ISSUE THREAD

**Issue by grandslammer** [stride3d/stride#809]
- Fresh install of Stride (new user here!)
- Happens on both the "Getting Started" and "News" tabs
- My Windows configuration is good (default browser is selected, I'm getting no issues with opening links from other applications)
- See screenshot

![Screenshot_1](https://user-images.githubusercontent.com/18541062/88800331-e3cba200-d19f-11ea-8391-ab4610d1f04b.png)

**Comment by Mojay1664** [comment]
Same problem here.

**Comment by laske185** [comment]
I've the same when tring to open Visual Studio in the IDE.

**Comment by domjancik** [comment]
Similar error upon clicking on links in the Release notes as well
![image](https://user-images.githubusercontent.com/9571934/90630865-178b6c00-e222-11ea-82a7-84ba9a5531ba.png)

**Comment by jcvw75** [comment]
Getting the same problem here. When clicking create project, getting the same error message in issue title. This engine has been a bane ever since xenko 3.1 , either vs extension issue and now this, i've never been able to properly evaluate it.
