### ISSUE TITLE
Creating new game or from template fails

### ISSUE THREAD

**Issue by civortech** [stride3d/stride#810]
**Release Type**: Official Release

**Version**: 4.0.0.1-beta04-1254

**Platform(s)**: Windows 10 pro  v2004, os build 19041.388

**Describe the bug**

**To Reproduce**
1.  .net core 3.1 is pre-selected
2. Start 4.0.0.1-beta...
3. project selection->Template:first-person shooter
4. press  select
5. select platform-> Windows already selected
6. Ok
7. creating session  window gives an Operation cancelled with logs below...

**Expected behavior**
create simple fps template project

**Screenshots**

**Log and callstacks**
Verbose: Process dependencies for FirstPersonShooter3.Game...
Info: Upgrading project [FirstPersonShooter3.Game] to use [Stride.Core] from version [4.0.0.1-beta04] to [4.0.0.1-beta04-1254] will be required
Verbose: Restore NuGet packages for FirstPersonShooter3.Game...
Verbose: Loading Assets from Package [Stride.Engine.sdpkg]
Verbose: Loading Assets from Package [Stride.Graphics.sdpkg]
Verbose: Loading Assets from Package [Stride.Particles.sdpkg]
Verbose: Loading Assets from Package [Stride.Rendering.sdpkg]
[C:\Program Files\dotnet\sdk\3.1.400-preview-015203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5)]: Error: The "ResolvePackageAssets" task failed unexpectedly.
System.MissingFieldException: Field not found: 'NuGet.ProjectModel.LockFileItem.AliasesProperty'.
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.<WriteCompileTimeAssemblies>b__39_1(LockFileTargetLibrary package, LockFileItem asset)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteItems[T](LockFileTarget target, Func`2 getAssets, Func`2 filter, Action`2 writeMetadata)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteCompileTimeAssemblies()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteItemGroup(Action writeItems)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.Write()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteToCacheFile()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
Error: Unable to build assembly reference [C:\Users\yanko\Documents\Stride Projects\FirstPersonShooter3\FirstPersonShooter3.Game\bin\Debug\netstandard2.0\FirstPersonShooter3.Game.dll]
Verbose: Loading Assets from Package [FirstPersonShooter3.Game.sdpkg]
Warning: Could not deserialize object of type 'FirstPersonShooter3.EffectController'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'FirstPersonShooter3.FpsCamera'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'FirstPersonShooter3.Player.WeaponScript'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'FirstPersonShooter3.Player.PlayerController'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'FirstPersonShooter3.Player.PlayerInput'; replacing it with an object implementing IUnloadable (...)
Warning: Could not deserialize object of type 'FirstPersonShooter3.Player.AnimationController'; replacing it with an object implementing IUnloadable (...)
Verbose: Compiling game assemblies...
Verbose: Game assemblies compiled...
Verbose: Generating FirstPersonShooter3.Windows...
Verbose: Process dependencies for FirstPersonShooter3.Windows...
Verbose: Restore NuGet packages for FirstPersonShooter3.Windows...
Verbose: Loading Assets from Package [FirstPersonShooter3.Windows.sdpkg]

**Additional context**
I tired selecting many project types, same issue.

**Comment by tthss** [comment]
I have the same problem, and I have no idea how to fix it.

**Comment by manio143** [comment]
I did a quick search and there's not much about it. There was one similar issue [here](https://developercommunity.visualstudio.com/content/problem/481018/resolvepackageassets-task-failed.html). So my guess is it could be connected to the version of .NET Core SDK you have installed.
@civortech I see in your log you're using `3.1.400-preview-015203`. Could you try disabling the preview version and running it with the official 3.1 release?

**Comment by civortech** [comment]
It only gave me one option of the .net core.
There must be a way to force a different version.
I will research and try. And get back to you.
Thx.

**Comment by civortech** [comment]
So I had to remove Visual Studio 2019 Preview so that it removed the .net 3.1 400 preview. really sucks that the Stride launcher does not have a config file or even to show all the .net core versions compatible...

is the stride launcher open sourced?

**Comment by tebjan** [comment]
@civortech yes, sure. would be great if someone would have a look at it:

https://github.com/stride3d/stride/tree/master/sources/launcher

**Comment by civortech** [comment]
i just pulled the code, once I get a chance I will try to see if I can do it. might help other to at least filter out preview core sdk.

p.s. if you use .net framework, it works fine!

**Comment by domjancik** [comment]
The incompatible .NET Core 3.1.400 is now out of preview and is what comes with the latest VS2019 (and I've recently updated 😭).

Downgrading seems to be a bit of an issue, there's this list of older version bootstrappers but it only covers Enterprise and Professional editions, not Community which I'm using:
https://docs.microsoft.com/en-us/visualstudio/releases/2019/history#installing-an-earlier-release

So I guess for anyone installing fresh VS2019 Community, the only option is to use .NET Framework?

**Comment by civortech** [comment]
Actually, you have to uninstall the Stride (make sure to remove any stride ref in ...\.nuget\packages\stride*), than change the sdk version to a previous version not preview versions..
dotnet new globaljson --sdk-version #.#.#
and than reinstall stride.
hope this works for you.

**Comment by TheGracekale** [comment]
If someone need a old version of VS, you can download it from here https://web.archive.org/web/20200801052203/https://visualstudio.microsoft.com/downloads/

**Comment by xen2** [comment]
Thanks for the report.
I think it happens because it tries to use our `NuGet.ProjectModel` rather than the one it expects.
This is quite important to fix that to avoid any future assembly mixup.
I will look into it.
