### ISSUE TITLE
Can't make a new project or open most old projects

### ISSUE THREAD

**Issue by CodingSea** [stride3d/stride#815]
**Release Type**:  Official Release

**Version**: All versions

**Platform(s)**: Windows 10

**Describe the bug**
can't make new projects/templates and can't open most of the my old projects.
and it gives me different error logs for New game template.

**To Reproduce**
A ->
    1. select a template -> Template first-person-shooter
    2. create the project

B ->
    1. select a template -> New game
    2. create the project

**Expected behavior**
A ->
    create a simple fps template project

B ->
    create a new game project

**Screenshots**

**Log and callstacks**
A ->

> Error: An exception occurred while generating the template.
> UnauthorizedAccessException: Access to the path 'C:/Users/Hp/Desktop/Stride/Projects/FirstPersonShooter7/Resources/Bullets.png' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
>    at Stride.Assets.Presentation.Templates.TemplateSampleGenerator.Generate(SessionTemplateGeneratorParameters parameters)
>    at Stride.Core.Assets.Editor.Components.TemplateDescriptions.SessionTemplateGenerator.Run(SessionTemplateGeneratorParameters parameters)
>    at Stride.Core.Assets.Editor.Components.TemplateDescriptions.TemplateGeneratorHelper.<>c__DisplayClass0_0`1.<RunTemplateGeneratorSafe>b__0()

B ->

> Verbose: Generating MyGame16...
> Verbose: Process dependencies for MyGame16...
> Verbose: Restore NuGet packages for MyGame16...
> Verbose: Loading Assets from Package [Stride.Engine.sdpkg]
> Verbose: Loading Assets from Package [Stride.Graphics.sdpkg]
> Verbose: Loading Assets from Package [Stride.Particles.sdpkg]
> Verbose: Loading Assets from Package [Stride.Rendering.sdpkg]
> Verbose: Loading Assets from Package [Stride.Video.sdpkg]
> Verbose: Generating MyGame16.Windows...
> Verbose: Process dependencies for MyGame16.Windows...
> Verbose: Restore NuGet packages for MyGame16.Windows...
> [C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4955,5)]: Error: Could not write lines to file "obj\Debug\netstandard2.0\MyGame16.csproj.FileListAbsolute.txt". Access to the path 'C:\Users\Hp\Desktop\Stride\Projects\MyGame16\MyGame16\obj\Debug\netstandard2.0\MyGame16.csproj.FileListAbsolute.txt' is denied.
> [C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(5199,5)]: Error: Could not write lines to file "obj\Debug\netstandard2.0\MyGame16.csproj.FileListAbsolute.txt". Access to the path 'C:\Users\Hp\Desktop\Stride\Projects\MyGame16\MyGame16\obj\Debug\netstandard2.0\MyGame16.csproj.FileListAbsolute.txt' is denied.
> Error: Unable to build assembly reference [C:\Users\Hp\Desktop\Stride\Projects\MyGame16\MyGame16\bin\Debug\netstandard2.0\MyGame16.dll]
> Verbose: Loading Assets from Package [MyGame16.sdpkg]
> Verbose: Loading Assets from Package [MyGame16.Windows.sdpkg]
> Warning: Can't load Game assembly
> Verbose: Compiling game assemblies...
> Verbose: Game assemblies compiled...

**Additional context**
i was able to use stride with no problem for months before this problem, i think it's because of stride latest update, and i tried to uninstall and install stride but it still gives me the same problem, also i tried to download stride in another pc and it was working.

**Comment by tebjan** [comment]
> also i tried to download stride in another pc and it was working.

This seems to suggest that something is not correctly set up on your PC.  Both error messages say that you don't have access to the files in the specific folder. 
You try to move the` Stride Projects` folder somewhere else. Also, check the registered users on your Windows and make sure they have read and write access to the `Stride Projects` folder.

**Comment by CodingSea** [comment]
I just changed my account type to Administrator and it's now working, thx.
