### ISSUE TITLE
[Graphics] Template games don't render

### ISSUE THREAD

**Issue by Eideren** [stride3d/stride#825]
**Release Type**: Github

**Version**: Latest as of writing

**Platform(s)**: Most likely all of them

**Describe the bug**
The game doesn't render, a warning related to camera slot is reported to the console.

**To Reproduce**
1. Build template
2. Play template
3. Observe the console warning and black screen

**Expected behavior**
Renders as it did before.

**Additional context**
This issue is most likely related to #805 could you take a look @azeno ?

**Comment by azeno** [comment]
Argh sorry will have a look.

**Comment by Eideren** [comment]
Thanks azeno ! 
This issue should be fixed through #826 , feel free to reopen if it isn't
