### ISSUE TITLE
Custom Shaders not visible in Node Browser

### ISSUE THREAD

**Issue by vvvv-dottore** [stride3d/stride#830]
**Release Type**: cloned GitHub repository 

**Version**: 0.7 develop commit: 5519d332da07aeb0a20b679013444b3f3a28dad0
vl version: 2020.2.0-0217

**Platform(s)**: Windows

**Describe the bug**
In order to write my own shaders I cloned the repo and added a folder with my shaders in vl.stride.runtime/effects
when i run vl.stride and gamma opens none of the shaders in the Effects folder is available in the node browser

**To Reproduce**
1. clode vl.stride
2. add a folder in vl.stride.runtime/effects
3. create a shader in vl.stride.runtime/effects/MyCustomFolder (the shader correctly a .cs filde and the keys)
4. set VL:Stride as sturtup project
5. Run
6. open nodebrowser in gamma and search for any shader

**Expected behavior**
I would esxpect to find the shaders in nodebrowser. maybe some reference missing?

**Screenshots**
![image](https://user-images.githubusercontent.com/6460926/90748030-f1bda000-e2d1-11ea-8257-72ff3af27cd2.png)

![image](https://user-images.githubusercontent.com/6460926/90747841-b3c07c00-e2d1-11ea-9850-eb9a9a687242.png)

**Log and callstacks**

**Additional context**

**Comment by tebjan** [comment]
You need to use the post fix _VLNode

**Comment by vvvv-dottore** [comment]
pls can you point me to the right repository?
where do i need to put the post fix _VLNode? in the shader name?
tnx

**Comment by vvvv-dottore** [comment]
argh! I see now what you mean ahaha
ok, I'll move this issue to VL.Stride repo.
sorry for this.
