### ISSUE TITLE
No screen modes found error.

### ISSUE THREAD

**Issue by PrettyCoolDude987** [stride3d/stride#831]
**Release Type**: Official Release

**Version**: 4.0.0.1-beta04-1265

**Platform(s)**: Windows

**Describe the bug**
I am following the C# beginner tutorials Ep. 1. As soon as I build the project I get an `[Game]: Error: Unexpected exception. System.InvalidOperationException: No screen modes found` error.

**To Reproduce**
1. Create C# Beginner tutorial project.
2. Build and run project.

**Expected behavior**
I expected it to build and then run the sample project.

**Screenshots**
![Screenshot (31)_LI](https://user-images.githubusercontent.com/59175770/91516112-4bb0fd80-e8b0-11ea-9940-c4867240d1ca.jpg)

**Log and callstacks**
[Build.txt](https://github.com/stride3d/stride/files/5139775/Build.txt)
[StrideOutput.txt](https://github.com/stride3d/stride/files/5139778/StrideOutput.txt)

**Additional context**
I am a complete beginner at Stride, and just started today. It looks really promising and would really like to use it. I am also using a fairly old computer.

**Comment by Eideren** [comment]
Weird that the editor works but not the game, could you try other values for the ``Default Graphics Profile`` property inside the ``GameSettings`` asset ? What cpu and gpu is in that computer ? What resolution and refresh rate does your screen support ?

**Comment by PrettyCoolDude987** [comment]
When I change he `Default Graphics Profile` to Direct3D 10 and below I get a black screen. Whenever I click on it it doesn't respond and crashes. Anything above Direct3D 10 and I get a console error.

My CPU is an Intel Core i7-2620M @ 2.70GHz. I have an Intel HD Graphics 3000 and a GeForce GT 540M. The resolution is 1920 x 1080 and the refresh rate is 60Hz.

**Comment by PrettyCoolDude987** [comment]
@Eideren Is there a way to play the game in the Game Studio like Unity?

**Comment by Eideren** [comment]
@PrettyCoolDude987 not yet #333 
Debugging this issue without similar hardware doesn't seem very feasible and there's not a lot of people on this project, sorry but you're more likely to fix this issue on your side before anyone else can even take a stab at it.

**Comment by PrettyCoolDude987** [comment]
Ok thanks though.
The engine is probably too complicated for me to comprehend, but I'll leave this open for a week just in case.

**Comment by tebjan** [comment]
Did you check on which GPU the game starts?

**Comment by Eideren** [comment]
@PrettyCoolDude987 are you sure this issue is resolved ? I didn't see any pr related to it ? I would rather keep it open for now, either fix it, find a work around or at least present users with some info to fix it on their side.
If this issue is apu/igpu related like tebjan alluded to we'll change the title to reflect that.

**Comment by PrettyCoolDude987** [comment]
@Eideren I’m pretty sure it’s a gpu problem because I’ve had problems with Unreal and Unity before when it comes to playing a build.
