### ISSUE TITLE
Alpha of color behaving strange when MSAA is on

### ISSUE THREAD

**Issue by azeno** [stride3d/stride#835]
**Release Type**: Official Release

**Version**: 4.0.0.1 (latest)

**Platform(s)**: Windows

**Describe the bug**
The alpha of colors behaves rather weired if MSAA is turned on. In my example I have a pure emissive material where the alpha channel of its white color gets increased over time. One would expect a blending with the background in a linear fashion, but when turning on MSAA one gets a kind of step function based on the amount of MSAA levels.

**To Reproduce**
See attached project.
[MyGame5.zip](https://github.com/stride3d/stride/files/5190477/MyGame5.zip)

**Expected behavior**
MSAA should not affect alpha blending.

Does the blend state of the MSAAResolver need to be different? Or is it the shader itself - maybe it shouldn't take the alpha values into account at all - at least the referenced original shader doesn't, only loading rgb (https://github.com/TheRealMJP/MSAAFilter/blob/master/MSAAFilter/Resolve.hlsl#L378) and returning alpha = 1 for the final color value.

**Comment by tebjan** [comment]
Close this now, since #836 is merged?

**Comment by xen2** [comment]
Fixed by #836
