### ISSUE TITLE
Code-only project with latest stride, missing freetype.dll

### ISSUE THREAD

**Issue by WhitePhoera** [stride3d/stride#837]
# Question
I am trying repeat code-only project from Xenko-times. and project crashes at game.Run with error 
Could not load native library freetype.dll from path [\bin\Debug\netcoreapp3.1\x64\freetype.dll] using CPU architecture x64.

And there is no such file at all.

Packages used.
```xml    
    <PackageReference Include="Stride" Version="4.0.0.1-beta04-1265" />
    <PackageReference Include="Stride.Engine" Version="4.0.0.1-beta04-1265" />
    <PackageReference Include="Stride.UI" Version="4.0.0.1-beta04-1265" />
    <PackageReference Include="Stride.Video" Version="4.0.0.1-beta04-1265" />```
Do i miss something?

**Comment by Zeroto** [comment]
Make sure you add the runtimeidentifier to the project(or build it using it). The default compile doesn't add platform specific files. This is only needed for .net core projects.

e.g. add `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` to your project file.

**Comment by WhitePhoera** [comment]
ty. really missed that part.

**Comment by ericwj** [comment]
Can this be reopened? It isn't fixed.
