### ISSUE TITLE
Xenko 3.1 Could not find a compatible version of MSBuild.

### ISSUE THREAD

**Issue by pogsdbest** [stride3d/stride#847]
Release Type: Xenko 3.1

Version: Xenko 3.1

Platform(s): Windows 10

Describe the bug
Installer goes through perfectly - no complaints, but when trying to launch Stride, I get an error dialog with the text: Could not find a compatible version of MSBuild.

To Reproduce

1. Install Stride from here https://stride3d.net/download/
2. Run installer and let it complete
3. Try to Install Xenko 3.1, Visual Studio Plugin : Stride and Xenko
Expected behavior
I expected the Game Studio to launch.

Screenshots
![Capture](https://user-images.githubusercontent.com/2561538/93512350-c7094a80-f956-11ea-8d34-c7a06d5d1f3f.PNG)

Log and callstacks
If any, please attach here any log or callstack (preferably in a .txt file using GitHub drag and drop)
[Logs.txt](https://github.com/stride3d/stride/files/5241156/Logs.txt)

Additional context
I have latest VS Professional 2019 installed v16.7.3, with .NET desktop development, .NET core cross-platform development workloads. also Installed 4.0.0.1-beta04-1265 and it works perfectly. but my team are using 3.1.0.1 we don't rely on beta.

**Comment by xen2** [comment]
It should be fixed in 3.1.0.2
