### ISSUE TITLE
Once choose never ask, script will never be reloaded.

### ISSUE THREAD

**Issue by seelikes** [stride3d/stride#875]
**Release Type**: Official Release

**Version**:  Launcher v5.0.2 Xenko 3.1.0.2

**Platform(s)**:  Windows 10

**Describe the bug**
I use Jetbrains Rider editing the code, when i changed the code with rider, Xenko Studio will always ask me whether to reload or not,  which i think is very annoying, so i choose never to ask, maybe choose reload after. after that, i had to close the project then restart it from the launcher, then the changed code can be reloaded.

**To Reproduce**
1.  change the code with some other ide, like Jetbrains Rider
2. come back to Game Studio and choose reload and never ask

**Expected behavior**
i think if you guys really consider external changes as nothing, you should at least give a way to reload code, a button maybe. and i searched through the studio menu, can not reset this choice, making game studio a great hurt when editing scripts from outside.

**Screenshots**
No need

**Log and callstacks**

**Additional context**

**Comment by manio143** [comment]
Can you verify that after rebuilding the game project in Rider you don't have the option to reload assemblies?
![stride_reload_asm_button](https://user-images.githubusercontent.com/10709060/95891886-99f55f80-0d7d-11eb-94fc-aa12cab43f1f.png)

**Comment by seelikes** [comment]
@manio143 after build, everything ok, thank you
