### ISSUE TITLE
[Build] .NET 5/VS 2019 preview preventing project loading

### ISSUE THREAD

**Issue by Eideren** [stride3d/stride#881]
**Release Type**: GitHub

**Version**: Latest

**Platform(s)**: Gamestudio

**Describe the bug**
See title, issue was reported through discord so I don't have much data on it.

**To Reproduce**
1. Install .net 5 rc1+ ?
2. Open a project through the gamestudio ?

**Expected behavior**
Uses .net that we support or work with latest

**Log and callstacks**
Here's a partial log from a user:
[Error.txt](https://github.com/stride3d/stride/files/5397209/Error.txt)

**Comment by Megasware128** [comment]
Seems to be fixed in the latest version

**Comment by xen2** [comment]
Yes, it should have been fixed with 095ce7a2 (included in latest beta)
