### ISSUE TITLE
Static Mesh (Trimesh) Collider For Stride

### ISSUE THREAD

**Issue by herocrab** [stride3d/stride#890]
**Is your feature request related to a problem? Please describe.**
Stride currently has no trimesh collider. This has been a capability that has been tough to work around when designing 3d levels. The convex hull capability is not able to accurately create colliders for models.

**Describe the solution you'd like**
A trimesh collider shape that can be created from a mesh/model.

**Describe alternatives you've considered**
I've attempted to tune the convex hull collider to create a collider to suit my purpose, but this rarely works and is reliant on simplicity of the original mesh.

**Additional context**

**Comment by Eideren** [comment]
I ended up replying on discord before seeing this issue, so I'll be mostly repeating what I wrote over there.
It's partially implemented right now, there's no editor-facing component for it yet, see PR #479 and discussions in pr #289 for more info. You can go ahead and finish the implementation in my stead if you want to, do go through the discussions we had on the previous pr regarding that issue though (#289)

**Comment by herocrab** [comment]
I added a bounty to this: 

https://www.bountysource.com/issues/93609264-trimesh-collider-for-stride

**Comment by sboron** [comment]
Working on a pr. Its my first project as an contributor for stride. It will take a while. I was creating the templates and classes for the new TrimeshColliderShape and linked to BvhTriangleMeshShape. As soon as the PR is finished, I'll let you know, so you're welcome to test it.

**Comment by sboron** [comment]
Mby its better to call it also by the right name? "Concave Polygon Shape"

**Comment by sboron** [comment]
![image](https://user-images.githubusercontent.com/76991284/145107580-c2907aab-92a5-4b6d-bf08-26bb84084c23.png)

here we go..

**Comment by tebjan** [comment]
Great stuff going on here... :-)

**Comment by sboron** [comment]
Yeah godot sucks.. need a new challenge

**Comment by sboron** [comment]
![image](https://user-images.githubusercontent.com/76991284/145115897-32c7c832-a45b-437b-b51f-91bf75772734.png)
and here we are

**Comment by Eideren** [comment]
Nice, you might want to add support to create those colliders straight from ``Mesh``, I elaborated quite a bit on that point in the second post of this page.

> Mby its better to call it also by the right name? "Concave Polygon Collider Shape"

We already support convex hull for convex meshes, those don't look convex to me ?

**Comment by sboron** [comment]
> We already support convex hull for convex meshes, those don't look convex to me ?

What u mean with this @Eideren ?
Convex Shapes are not Concave Shapes..

**Comment by ykafia** [comment]
Can't tri-mesh colliders be convex too ?

**Comment by sboron** [comment]
Fore sure we can also do it with convex shapes. But usually these are not detailed enough. So its better to support Concave Shapes to. A typical trimesh collider use a concave shape which contains all faces of an mesh. For sure trimesh colliders are slower. But they are more detailed.

**Comment by sboron** [comment]
Typicaly u store the mesh shape data inside an extra file (what i do currently). Because otherwise u have to generate everytime the faces again.

**Comment by Eideren** [comment]
Ignore my comment, I am tired and thought you were talking about convex polygon collider but you clearly wrote the opposite

**Comment by sboron** [comment]
Okay, let's put it under the first communication problems :-)

**Comment by sboron** [comment]
@Eideren there is guideline for prs? cant find it..

**Comment by sboron** [comment]
What as next a terrain tool editor mby? :-)
