### ISSUE TITLE
Installer privacy link doesn't work 

### ISSUE THREAD

**Issue by manu-st** [stride3d/stride#891]
When installing Stride, you can see a link to the Stride's privacy page. Unfortunately clicking on it does not work as you can see below:

![image](https://user-images.githubusercontent.com/13194660/97061007-2e17b180-154a-11eb-91ca-d8d7ffcec4e2.png)

I expected this to open my web browser

**Comment by Zeroto** [comment]
This looks like to be the same problem as I fixed in #877 for the launcher. However, I can't seem to find where the installer source is stored.

**Comment by manio143** [comment]
@Zeroto There's a separate solution for the launcher `/build/Stride.Launcher.sln` and the project is under `/sources/launcher`

**Comment by manio143** [comment]
I think this might be the `\sources\editor\Stride.PrivacyPolicy` project and this is the hyperlink:
```xml
<Hyperlink TextDecorations="Underline" CommandParameter="{x:Static crashReport:CrashReportForm.PrivacyPolicyUrl}"
            Command="{x:Static sd:UtilityCommands.OpenHyperlinkCommand}">
  <Run Text="{x:Static crashReport:CrashReportForm.PrivacyPolicyUrl}" />
</Hyperlink>
```
You might need to find where this command is defined and fix it there.

**Comment by Zeroto** [comment]
That command is already fixed. I don't know if that is used in the actual installer though. It might just be the case that a new version of the installer needs to be build and deployed.

**Comment by xen2** [comment]
Launcher was fixed and released but this is part of GameStudio startup (which has not been released since PR was merged).

**Comment by Eideren** [comment]
It's been a while now, I'm sure this has been released by now, should I close this one then ?

**Comment by Kryptos-FR** [comment]
@Eideren @xen2 should this issue be closed?

I couldn't find any instance of Process.Start that doesn't set the `UseShellExecute` property to `true` when needed.
