### ISSUE TITLE
Stride.OpenTK isn't including correct OpenTK.dll for Linux

### ISSUE THREAD

**Issue by manio143** [stride3d/stride#900]
**Release Type**: Official Release & GitHub

**Version**: beta04

**Platform(s)**: Linux

**Describe the bug**
The Stride.OpenTK NuGet package is a proxy which references a "dummy" OpenTK.dll, but substitutes it for platform specific versions. On Linux rather than including the proper library `/deps/OpenTK/CoreCLR/Linux` the dummy one is used, which throws `NotImplementedException` on any method call in `GL` class.

**Expected behavior**
The Stride.OpenTK contains correct packages per platform.

**Workaround**
For now you can just copy over the correct library to the output folder of your game. You also need the dll.config file for shared library mapping.

**Comment by manio143** [comment]
Actually I'm experiencing the same thing for Windows. How is Stride.OpenTK built/packaged?

**Comment by Eideren** [comment]
We've migrated from OpenTK, this issue is no longer relevant
