### ISSUE TITLE
Particle worker thread crash after looping particle system has been stopped.

### ISSUE THREAD

**Issue by SoulRider** [stride3d/stride#903]
**4.0.0.1-beta04-1265**: Official Release

**Windows**

After stopping a looping particle, if a worker thread has already begun work on the particle it can crash with an object not found error.

**To Reproduce**
1. Stop a looping particle system.

It doesn't occur all the time, but often enough to be a problem, I have created a small demo project that quickly swaps highlights to prove the crash.

**Expected behavior**
The game not to crash.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/1388684/98289464-24596980-1fa0-11eb-94a9-27cc5aba20ed.png)

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)

**Additional context**
Please see the small project here - https://www.dropbox.com/s/jiekvq1lap7to2i/ParticleTesting.zip?dl=0

This runs alternate stop / play on two looping particle systems at high speed to create the crash.  High speed is not relevant for the crash it is just the specific timing of when stop is called in relation to where the particle worker thread is in call stack.

Note in this code the two particles are both on at load time and one is stopped in the initial start.  This will sometimes cause the crash immediately on startup.

**Comment by Eideren** [comment]
``System.Timers.Timer`` calls the delegate you pass in from another thread, most of stride's systems are not thread-safe leading to the behavior you see here, this is expected behavior.

**Comment by SoulRider** [comment]
Is there anyway I can protect against this in my code? Or will I have to forget particles and come up with a new highlighting system that doesn't require a loop?

**Comment by Eideren** [comment]
Yes, loads of them but since you seem lost let's keep this simple.
#### Switch to ``AsyncScript``
Taking ``ParticleTest`` as a base, inherit from ``AsyncScript`` and replace the start function with:
```cs
public override async Task Execute()
{
    particleScripts.Add(particleA);
    particleScripts.Add(particleB);

    while (true)
    {
        await Task.Delay(10);
        SwitchHighlight(null, null);
    }
}
```
#### Accumulate delta time
Taking ``ParticleTest`` as a base again, inherit from ``SyncScript`` and replace the start function with:
```cs
private float timeInMsAccumulate;

public override void Start()
{
    particleScripts.Add(particleA);
    particleScripts.Add(particleB);
}

public override void Update()
{
    timeInMsAccumulate += (float)Game.UpdateTime.Elapsed.TotalMilliseconds;
    while (timeInMsAccumulate > 10)
    {
        timeInMsAccumulate -= 10f;
        SwitchHighlight(null, null);
    }
}
```

**Comment by SoulRider** [comment]
My game loop runs off the timer, so I will have to rewrite the core logic to do this, but I'll give it a try.
