### ISSUE TITLE
UWP App can not be built in 4.0.0.1-beta4-1265 with .Net Framework 4.7.2

### ISSUE THREAD

**Issue by Agredo** [stride3d/stride#904]
**Release Type**: Official Release/GitHub (please choose appropriate option)
Official Release

**Version**: Version number and/or git branch
4.0.0.1-beta4-1265

**Platform(s)**: Does the problem occur on Windows, Android...?
UWP

**Describe the bug**
Building an UWP app fails with the followig error
![image](https://user-images.githubusercontent.com/16531090/98406676-b16af400-206e-11eb-8718-ff79b40597f9.png)

**To Reproduce**
1. Create a .Net Framework project 4.7.2
2. Select Windows and UWP 
3. Open project in Visual Studio and build the UWP project

**Expected behavior**
UWP can run 

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)
![image](https://user-images.githubusercontent.com/16531090/98406845-f858e980-206e-11eb-8698-515d8db4b3f9.png)

**Log and callstacks**
-

**Additional context**
-

**Comment by manio143** [comment]
This might be caused, because .NET Core build tools are used instead of MSBuild.
A good starting point to investigate: https://github.com/stride3d/stride/blob/8d285b44fa159e0ed3adb226370d4b03e3416d17/sources/assets/Stride.Core.Assets/PackageSessionPublicHelper.cs#L30-L46

**Comment by manio143** [comment]
Actually I gave it more thought and it seems that for projects that aren't targeting either .NET Core or .NET Framework, we fallback to using .NET Core AssetCompiler over .NET Framework.

https://github.com/stride3d/stride/blob/6494dcf7884bd30e8a44fd258720c26a6f90ca5c/sources/assets/Stride.Core.Assets.CompilerApp/build/Stride.Core.Assets.CompilerApp.targets#L119-L121

Can you try swapping those two lines (in `~/.nuget/packages/stride.core.asset.compilerapp/<ver>/build`) and see if it would fix the compilation error?

**Comment by xen2** [comment]
Good point, it should probably fallback to `net472` when compiling UWP/iOS/Android (until supported by .NET 6).
I guess it shows how much people are using those platforms...

**Comment by Agredo** [comment]
@manio143 this did not fixed it

**Comment by manio143** [comment]
My bad, you actually should be modifying the same file but in `buildTransitive` instead (when I PR it's gonna be fixed in both).
