### ISSUE TITLE
Directional Light in the Game Studio

### ISSUE THREAD

**Issue by antongit** [stride3d/stride#909]
**Is your feature request related to a problem? Please describe.**
It's not possible to understand the direction of the Directional Light until one selects its Gizmo AND rotates the View so, that the Gizmo doesn't overlap (hide) the vector.

Here are some pictures.

![image](https://user-images.githubusercontent.com/1189037/99087993-b6c6c200-25cb-11eb-8e63-a52567cf5583.png)

![image](https://user-images.githubusercontent.com/1189037/99088032-c219ed80-25cb-11eb-909e-7719e1f94f57.png)

**Describe the solution you'd like**
Would it be possible to have another Gizmo for the Directional Light (instead of the default Sun Icon) that shows the direction?

This is how they do it in Maya:

![image](https://user-images.githubusercontent.com/1189037/99088058-cc3bec00-25cb-11eb-88ed-89e18e316e65.png)

**Comment by parhamgholami** [comment]
I'm interested in tackling this issue. There are a couple of different ways we could communicate the direction.

One way would be to adopt the Maya/Unity approach (as mentioned in the original post), where there are lines denoting the direction:
![image](https://github.com/stride3d/stride/assets/7075456/fd25db69-7bf1-42ce-8479-a5aea6344e51)

Alternatively, we could do something similar to Unreal:
![image](https://github.com/stride3d/stride/assets/7075456/98e1b61d-6e18-487d-9bf7-5d7987bcfd38)

Based on my understanding of the gizmos, the latter would be trivial to implement. Jack already did the necessary work, but I don't know why the branch was deleted.

With all that in mind, is there any preference for how we show the direction of the light?
