### ISSUE TITLE
New projects ignore creation settings, are incomplete and fail to build/run correctly, or open in Visual Studio

### ISSUE THREAD

**Issue by ericwj** [stride3d/stride#911]
**Release Type**: Official Release

**Version**: 4.0.0.1-beta04-1317

**Platform(s)**: The problem occurs on Windows

**Describe the bug**
Stride Game Studio cannot open Visual Studio.

Also, the project is not created the way it was requested and does not build or run correctly from Visual Studio without first modifying the project file.

**To Reproduce**
1. With 4.0.0.1-beta04-1317 I can create New Game MyGame and run it unmodified, but 
2. *Open in IDE* will give me **An error occurred while starting Visual Studio**. I have Community 2019 and Community Preview and Build Tools 2019 installed. 
3. Then I can open the solution manually in Preview after which *Open in IDE* will nicely switch to the open instance of VS.
4. However build doesn't work: **[AssetCompiler] The SDK 'Microsoft.Net.SDK' specified could not be found.**
5. Doesn't matter whether my `global.json` lists SDK 5.0.100 or 3.1.404. I was told to install .NET Framework 4.7.2 but yeah I get 4.6.2 in the project file.
6. Changing `MyGame.Windows.csproj` by double clicking it in Visual Studio and setting `<TargetFramework>netcoreapp3.1</TargetFramework>` it builds and runs, but crashes over not finding `freetype.dll` - which doesn't exist in my solution folder at all.
7. Changing `MyGame.Windows.csproj` by double clicking it in Visual Studio and setting `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` it builds and runs.

**Expected behavior**
* *Open in IDE* works.
* The project created is .NET Core 3.1 since I created it with that setting. The project certainly should not be `net461` or the documentation should list this as a prerequisite. The docs list `net472` as prerequisite instead.
* The project created has a runtime identifier, since that appears to fix the issue of the missing *freetype.dll*.
* The solution created explicitly sets the SDK version in a **global.json** for me, since it does not simply work using the latest .NET SDK.

**Comment by ericwj** [comment]
Checkout [VisualStudioShell](https://www.powershellgallery.com/packages/VisualStudioShell/0.4.0-beta) for a fair bit of information how to reliably find and open Visual Studio. It is in PowerShell, but that is an implementation detail.

**Comment by manio143** [comment]
TODO:
- [ ] Fix _Open in IDE_ - if you click the dropdown and select VS 2019 it works correctly
- [ ] Parameterize `sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.Windows/$ProjectName$.csproj.t4` to use `net461`/`netcoreapp3.1` depending on GameStudio runtime platform. (Note for .NET Framework: while we can target 4.6.1, the asset compiler requires 4.7.2 to run).
- [x] Add RID to Windows executable project by default (see #910)
- [ ] Discover which .NET Core SDK is used for running GameStudio and generate a global.json file with that version in project's solution folder.

**Comment by ericwj** [comment]
> if you click the dropdown and select VS 2019 it works correctly

Which dropdown? I was using the menu. I'd say remove the default such that there is always an explicit choice to make if there is more than one Visual Studio installed and make that a project user setting. I might consistently use Preview for months and then get fed up with the speed or get issues and use RTM for months until the next minor version for example. Ideally if the user setting isn't set, ask for the version explicitly unless there is only one installed?
