### ISSUE TITLE
Stride cannot run becouse version of MSBuild is not 16.0 or later

### ISSUE THREAD

**Issue by snaulX** [stride3d/stride#918]
**Release Type**: Official Release

**Version**: 4.0.0.1-beta04-1317

**Platform(s)**: Windows

**Describe the bug**
Stride cannot run becouse version of MSBuild is not 16.0 or later but I have MSBuild version 16.8.2.56705

**Expected behavior**
I deleted one of my projects from disk and removed it from list in Stride Launcher and started Stride.

**Screenshots**
![image](https://user-images.githubusercontent.com/43488179/100070720-4d587600-2e4b-11eb-9104-3ff40d65df6d.png)

**Log and callstacks**
Could not find a compatible version of MSBuild.
Check that you have a valid installation with the required workloads, or go to www.visualstudio.com/downloads to install a new one.
System.InvalidOperationException: Could not find a MSBuild installation (expected 16.0 or later) at Stride.Core.Assets.PackageSessionPublicHelper.FindAndSetMSBuildVersion() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\PackageSessionPublicHelper.cs:line 51 at Stride.GameStudio.Program.Startup(UFile initialSessionPath) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.GameStudio\Program.cs:line 242

**Comment by Grafcube** [comment]
This is happening to me too. It happened after I updated Visual Studio 2019 to the latest version and reinstalling did nothing.

**Comment by DirkRinge** [comment]
I could solve this issue by manually installing .NET Core 3.1 SDK from https://dotnet.microsoft.com/download/dotnet-core/3.1

**Comment by bmello4688** [comment]
@snaulX does this fix your problem?

**Comment by snaulX** [comment]
> @snaulX does this fix your problem?

I have latest version of Visual Studio 2019 and run Stride using this version and I don't found solutions to fix this problem

**Comment by ArcadeArchie** [comment]
**Release Type**: Official Release

**Version**: 4.0.0.1-beta04-1366

**Platform(s)**: Windows
**Visual Studio Version**: VS Enterprise 2019 Preview 16.9.0 Preview 2.0

I have encountered the same problem, but fixed by manually reinstalling the .NET 5 & .NET Core 3.1 SDKs

**Comment by snaulX** [comment]
I fixed this with downloading of new update of Stride. Thanks to all for helping!
