### ISSUE TITLE
Incorrect test build - StrideGraphicsApiDependentBuildAll not renamed.

### ISSUE THREAD

**Issue by thargy** [stride3d/stride#940]
**Release Type**: Official Release and GitHub

**Version**: 4.0.0.1-beta03-1036+

**Platform(s)**: Any

**Describe the bug**
Whilst trying to understand why the current beta does not include platforms other than Direct3D11 on Windows, I discovered this line:

https://github.com/stride3d/stride/blob/6f8a265a5ab8c666341e0150df64e033c9b6be3e/sources/targets/Stride.UnitTests.targets#L12

Where `StrideGraphicsApiDependentBuildAll` was not renamed to `StrideGraphicsApisDependentBuildAll` as it was everywhere else.  The incorrect property name persists in the latest beta.

**Comment by xen2** [comment]
Good catch, thanks!
