### ISSUE TITLE
Cannot serialize a list of custom classes  OR a dictionary<CustomClass, otherType>

### ISSUE THREAD

**Issue by Shpendicus** [stride3d/stride#960]
**Release Type**: Official Release/GitHub 

**Version**: 4.0.0.1-beta04-1347  with .NET 5.0.01

**Platform(s)**: For now only in Windows.

**Describe the bug**
Cannot serialize a list of custom classes OR a dictionary<CustomClass, otherType>.

**To Reproduce**
1. Open existing .cs scriptt (i. e CharachterScript)
2. create a custom class/struct with simple fields and properties
3. create a List<CustomClass> OR dictionary<CustomClass, otherType>.
4. save solution

**Expected behavior**
The collection should be fully serialized into the inspector with that customclass, since serializing a customclass/struct works perfectly fine only a Collection of those isnt serialized

**Screenshots**
not needed since Logoutput is enough if you ask me.

**Log and callstacks**
_[(0,0)]: Info: Patch for assembly [SpaceEscape.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
[(0,0)]: Info: System.InvalidOperationException: Could not process serialization for member System.Collections.Generic.List`1<SpaceEscape.CharacterScript/Person> SpaceEscape.CharacterScript::Bla
[(0,0)]: Info:  ---> System.InvalidOperationException: Could not find serializer for generic dependent type SpaceEscape.CharacterScript/Person when processing System.Collections.Generic.List`1<SpaceEscape.CharacterScript/Person>
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.Serializers.CecilSerializerContext.AddSerializableType(TypeReference dataType, SerializableTypeInfo serializableTypeInfo, String profile) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\Serializers\CecilSerializerContext.cs:line 540
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.Serializers.CecilSerializerContext.GenerateSerializer(TypeReference type, Boolean force, String profile, Boolean generic) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\Serializers\CecilSerializerContext.cs:line 153
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.Serializers.CecilSerializerContext.ProcessComplexSerializerMembers(TypeReference type, SerializableTypeInfo serializableTypeInfo, String profile) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\Serializers\CecilSerializerContext.cs:line 215
[(0,0)]: Info:    --- End of inner exception stack trace ---
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.Serializers.CecilSerializerContext.ProcessComplexSerializerMembers(TypeReference type, SerializableTypeInfo serializableTypeInfo, String profile) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\Serializers\CecilSerializerContext.cs:line 229
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.Serializers.CecilSerializerContext.FindSerializerInfo(TypeReference type, Boolean generic) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\Serializers\CecilSerializerContext.cs:line 365
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.Serializers.CecilComplexClassSerializerProcessor.ProcessType(CecilSerializerContext context, TypeDefinition type) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\Serializers\CecilComplexClassSerializerProcessor.cs:line 28
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.Serializers.CecilComplexClassSerializerProcessor.ProcessSerializers(CecilSerializerContext context) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\Serializers\CecilComplexClassSerializerProcessor.cs:line 18
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.ComplexSerializerRegistry..ctor(PlatformType platform, AssemblyDefinition assembly, TextWriter log) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\ComplexSerializerRegistry.cs:line 124
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.SerializationProcessor.Process(AssemblyProcessorContext context) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\SerializationProcessor.cs:line 31
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.AssemblyProcessorApp.Run(AssemblyDefinition& assemblyDefinition, Boolean& readWriteSymbols, Boolean& modified, Nullable`1& serializationHash) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\AssemblyProcessorApp.cs:line 262
[(0,0)]: Info: Unexpected error
[C:\Users\shho3\.nuget\packages\stride.core\4.0.0.1-beta04-1347\buildTransitive\Stride.Core.targets(100,5)]: Error: Failed to run assembly processor with parameters: --auto-notify-property --parameter-key --auto-module-initializer --serialization --add-reference="C:\Users\shho3\.nuget\packages\stride.core\4.0.0.1-beta04-1347\ref\netstandard2.0\Stride.Core.dll" --add-reference="C:\Users\shho3\.nuget\packages\stride.engine\4.0.0.1-beta04-1347\lib\netstandard2.0\Stride.Engine.dll" --add-reference="C:\Users\shho3\.nuget\packages\stride.particles\4.0.0.1-beta04-1347\lib\netstandard2.0\Stride.Particles.dll" --add-reference="C:\Users\shho3\.nuget\packages\stride.ui\4.0.0.1-beta04-1347\ref\netstandard2.0\Stride.UI.dll" --references-file="obj\Debug\netstandard2.0\StrideReferences.cache" --platform=Windows --targetFramework= "obj\Debug\netstandard2.0\SpaceEscape.Game.dll"
[C:\Users\shho3\.nuget\packages\stride.core\4.0.0.1-beta04-1347\buildTransitive\Stride.Core.targets(100,5)]: Error: Check the previous logs_

**Additional context**
Nope.

**Comment by manio143** [comment]
In order to serialize a class/struct you need to put a `Stride.Core.DataContractAttribute` on it, so that during compilation a serializer for that type is generated.
I don't know if dictionaries with non-scalar (i.e. scalars = numbers, strings) key types are supported for serialization (esp. when using YAML serialization which has a limited syntax for dictionaries). But values can be custom classes/structs if attributed properly.

**Comment by Shpendicus** [comment]
Sadly tho, you cannot serialize a List of CustomStructs either, so this wont work:

`
       [DataContract]
        public struct Person
        {
            string a;
            int b;
            DateTime c;
        }       
`

` public List<Person> s = new List<Person>();`
![empty list](https://user-images.githubusercontent.com/28008874/102125768-7072b600-3e4a-11eb-909c-971429cb1a77.png)

changed signaturew of Person to class and it doesnt still serialize properly the list the only thing it does it serializes  isthe classtypename "Person" to the textbox but not the actuall class data: (see image)

**Comment by manio143** [comment]
Did you use the right `[DataContract]` from `Stride.Core` and not the system one?

**Comment by Shpendicus** [comment]
Yea my bad, it works! i forgot to set fields to public, had a longg day today haha

**Comment by manio143** [comment]
Can you close this issue? The relevant discussion regarding dictionaries is in the other one.

**Comment by Shpendicus** [comment]
Done!
