### ISSUE TITLE
Wrong description in Stride installer when missing Visual Studio component

### ISSUE THREAD

**Issue by Basewq** [stride3d/stride#985]
**Release Type**: Official Installer

**Version**: (?)

**Platform(s)**: Windows

**Describe the bug**
When installing Stride, if you are missing the Development Tools component, the installer says ".NET Core 2.1 Runtime (LTS)" is missing and needs to be installed, however this is incorrect.

As per this line
https://github.com/stride3d/stride/blob/b73b2a956422171c4173cecc7d5433d2d9c67d36/sources/tools/Stride.PackageInstall/Program.cs#L25
the installer is looking for `Microsoft.NetCore.ComponentGroup.DevelopmentTools.2.1`, but this is called `Development Tools plus .NET Core 2.1` as seen in this link https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2019

The closest match to the description `.NET Core 2.1 Runtime (LTS)` is the one with ID `Microsoft.Net.Core.Component.SDK.2.1` as per this link https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019

**Expected behavior**
Need the installer to state the correct missing/required component.

**Comment by frionx** [comment]
I noticed this too, I got really confused while installing because of this. I installed like 10gb of .net runtimes and sdks and it finally worked so.

**Comment by cstdbool** [comment]
Corrected and merged with PR #988 (commit 065b78b61219b41651eb813f8b29e1767305cc09). The issue can be closed.

**Comment by Basewq** [comment]
> 
> 
> Corrected and merged with PR #988 (commit [065b78b](https://github.com/stride3d/stride/commit/065b78b61219b41651eb813f8b29e1767305cc09)). The issue can be closed.

Thanks.
FYI, if you write something like `Fixes #985` in the PR, Github can usually detect the link and auto-close the issue.
