### ISSUE TITLE
[Build] 'Edit and Continue' broken on standard2.1/net5.0

### ISSUE THREAD

**Issue by Eideren** [stride3d/stride#997]
**Release Type**: Nugget

**Version**: 4.0.1.1381-beta

**Platform(s)**: Windows

**Describe the bug**
Run with your IDE open, modify logic and applying those changes won't come through, it'll report this error:
```
Failed to emit module 'name of the assembly': Changing the version of an assembly reference is not allowed during debugging: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' changed version to '2.1.0.0'.
```
Standard 2.0 works as expected though.

**To Reproduce**
1. Download and extract [Temp.zip](https://github.com/stride3d/stride/files/5825503/Temp.zip)
2. Open and run ``Temp.csproj``
3. While the process runs, edit the ``WriteLine`` content and use the 'Edit and Continue' feature to apply those changes
4. Notice the error your IDE outputs.

**Expected behavior**
It just works.

*If you've got any idea why this would occur feel free to chime in.*

Edit: Updated the archive with an even simpler version of the issue.

**Comment by Eideren** [comment]
Looks like the source of the issue lies between ``Stride.Core`` and ``Stride.Engine``, here's a repro where I gutted most of ``Stride.Engine`` to a minimal state.
[TestEnC.zip](https://github.com/stride3d/stride/files/5825757/TestEnC.zip)
Repro:
1. Open the sln
2. Build and run
3. Break/pause execution, add another writeline to ``program.cs`` and continue execution of the program
4. Notice the error.

From that repro you can change ``Stride.Engine.csproj`` to use ``Stride.Core_dumb`` instead of the official.
'dumb' is stripped of all of the additional build stuff to validate that the issue here doesn't come from the code itself but probably something coming with how it's built or its content ?

When ``Stride.Engine`` exists within a project (don't even need to use it in any way in your project, just adding the package is enough) it brings ``Stride.Core`` with him which for some reason prevents that feature from working, I don't know if it's because it runs some logic that it shouldn't when edit and continue is triggered or what.

Is there anything special with that project @xen2 ? Sure there's a bunch of stuff with serialization but perhaps you've got more of an idea as to why it would break ...

**Comment by NicusorN5** [comment]
Is this still possible in the latest official release?

**Comment by Eideren** [comment]
It works in latest, yeah
